#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Deleting existing data in target database"
run_sqlplus ${SOURCE_DB_NAME} ${TESTS_DIR}/oracle-tests/utils/delete_full_schema

echo "Initialising source database"
run_sqlplus ${SOURCE_DB_NAME} ddl/schema

echo "Populating data in source database"
run_sqlplus ${SOURCE_DB_NAME} dml/data
