#!/usr/bin/env python3

import yb
import collections

def main():
	yb.run_checks(migration_completed_checks)

def migration_completed_checks(tgt):
  
	# Logic to check the sequences migrated
	fetched_sequences = tgt.get_objects_of_type("VIEW", "public")
	print(f"Returned sequences are - {fetched_sequences}")
	assert len(fetched_sequences) == 16

if __name__ == "__main__":
	main()