#!/usr/bin/env bash

set -e
set -x

export TEST_NAME="import-file"

export REPO_ROOT="${PWD}"
export SCRIPTS="${REPO_ROOT}/migtests/scripts"
export TESTS_DIR="${REPO_ROOT}/migtests/tests/import-file-tests"
export TEST_DIR="${TESTS_DIR}/${TEST_NAME}"
export EXPORT_DIR=${EXPORT_DIR:-"${TEST_DIR}/export-dir"}
export TARGET_DB_HOST=${TARGET_DB_HOST:-"10.9.118.29"}
export TARGET_DB_PASSWORD=${TARGET_DB_PASSWORD:-"password"}
export TARGET_DB_NAME=${TARGET_DB_NAME:-"csv_migration_test"}

export PYTHONPATH="${REPO_ROOT}/migtests/lib"

export DATA_FILE_NAME="csv-migration-test/annual-enterprise-survey-2021-financial-year-provisional-csv.csv"

source ${SCRIPTS}/yugabytedb/env.sh
source ${SCRIPTS}/functions.sh

export TARGET_DB_NAME="migrate_csv"
export TARGET_TABLE_NAME="csv_table"

CMD="CREATE TABLE ${TARGET_TABLE_NAME} (
    Industry_Year INT,
    Industry_Aggregation_Level VARCHAR(100),
    Industry_Code VARCHAR(10),
    Industry_Type TEXT,
    Dollar_Percentage TEXT,
    Industry_name CHAR(10),
    Variable_Sub_Category VARCHAR(100),
    Variable_Category VARCHAR(100),
    Industry_Valuation TEXT,
    Industry_Class TEXT
);"

main() {
	mkdir -p ${EXPORT_DIR}

	pushd ${TEST_DIR}

	step "Create target database."
	run_ysql yugabyte "DROP DATABASE IF EXISTS ${TARGET_DB_NAME};"
	run_ysql yugabyte "CREATE DATABASE ${TARGET_DB_NAME}"

	step "Create target table."
	run_ysql ${TARGET_DB_NAME} "${CMD}"

	step "Import data file"
	import_data_file --data-dir ${TEST_DIR} --format text --delimiter ',' \
		--file-table-map "${DATA_FILE_NAME}:${TARGET_TABLE_NAME}"

	step "Run validations."
	 "${TEST_DIR}/validate" FILE_IMPORT_DONE
}

main
