#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Deleting ${SOURCE_DB_NAME} database on source"
run_psql postgres "DROP DATABASE ${SOURCE_DB_NAME};"

# Optionally delete source replica (fall forward)
if [ -n "${SOURCE_REPLICA_DB_NAME}" ]; then
    echo "Deleting ${SOURCE_REPLICA_DB_NAME} database"
    run_psql postgres "DROP DATABASE ${SOURCE_REPLICA_DB_NAME};"
fi