#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Assigning permissions to the validate files"
chmod +x ${TEST_DIR}/validate
chmod +x ${TEST_DIR}/validateAfterChanges

echo "Creating ${SOURCE_DB_NAME} database on source"
run_psql postgres "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_psql postgres "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Initializing source database with schema and data."
run_psql ${SOURCE_DB_NAME} "\i snapshot_schema.sql;"
run_psql ${SOURCE_DB_NAME} "\i snapshot_data.sql;"

# Optionally initialize source replica (fall forward)
if [ -n "${SOURCE_REPLICA_DB_NAME}" ] && [ "${SOURCE_REPLICA_DB_NAME}" != "${SOURCE_DB_NAME}" ]; then
    echo "Creating ${SOURCE_REPLICA_DB_NAME} database (for fall forward)"
    run_psql postgres "DROP DATABASE IF EXISTS ${SOURCE_REPLICA_DB_NAME};"
    run_psql postgres "CREATE DATABASE ${SOURCE_REPLICA_DB_NAME};"
    run_psql ${SOURCE_REPLICA_DB_NAME} "\i snapshot_schema.sql;"
fi