#!/usr/bin/env python3

import os
import yb
import collections
import common

def main():
    test_type_flags = common.valparser()

    migration_completed_checks_yb()

    if test_type_flags['ff_enabled'] == 'true':
        migration_completed_checks_ff()

    if test_type_flags['fb_enabled'] == 'true':
        migration_completed_checks_fb()


# Define expected row count for tables in both schemas
EXPECTED_ROW_COUNT = {
    'public': {
        'single_unique_index': 5,
        'multi_unique_index': 5,
        'different_columns_unique_constraint_and_index': 5,
        'subset_columns_unique_constraint_and_index': 5
    },
    'non_public': {
        'single_unique_constraint': 5,
        'multi_unique_constraint': 5,
        'same_column_unique_constraint_and_index': 5
    }
}

# Define expected final varchar state for all unique constraint/index columns
EXPECTED_FINAL_STATE_VARCHAR = {
    'non_public': {
        'single_unique_constraint': {
            'email': [
                'user2@example.com', 
                'updated_user4@example.com', 
                'user4@example.com', 
                'updated_user5@example.com', 
                'user5@example.com'
            ]
        },
        'multi_unique_constraint': {
            'first_name': ['John', 'Tom', 'Bob', 'Updated_Alice', 'Alice'],
            'last_name': ['Doe', 'Smith', 'Johnson', 'Williams', 'Clark']
        },
        'same_column_unique_constraint_and_index': {
            'email': [
                'user2@example.com', 
                'updated_user4@example.com', 
                'user4@example.com', 
                'updated_user5@example.com', 
                'user5@example.com'
            ]
        }
    },
    'public': {
        'single_unique_index': {
            'ssn': [
                'SSN2', 
                'updated_SSN4', 
                'SSN4', 
                'updated_SSN5', 
                'SSN5'
            ]
        },
        'multi_unique_index': {
            'first_name': ['Jane', 'Updated_Tom', 'Tom', 'Updated_Alice', 'Alice'],
            'last_name': ['Smith', 'Clark', 'Williams']
        },
        'different_columns_unique_constraint_and_index': {
            'email': [
                'user3@example.com', 
                'updated_user4@example.com', 
                'user4@example.com', 
                'user5@example.com', 
                'user1@example.com'
            ],
            'phone_number': [
                '555-555-5552', 
                '555-555-5554', 
                '555-555-5561', 
                '555-555-5558', 
                '555-555-5555'
            ]
        },
        'subset_columns_unique_constraint_and_index': {
            'first_name': ['John', 'Updated_Bob', 'Bob', 'Updated_Alice', 'Alice'],
            'last_name': ['Doe', 'Smith', 'Johnson', 'Williams'],
            'phone_number': ['123-456-7890', '123-456-7892', '123-456-7893']
        }
    }
}

def migration_completed_checks_yb():
    print("Running tests on YB")
    yb.run_checks(migration_completed_checks)

def migration_completed_checks_ff():
    print("Running tests on PG source replica")
    yb.run_checks(migration_completed_checks, db_type="source_replica")

def migration_completed_checks_fb():
    print("Running tests on PG source")
    yb.run_checks(migration_completed_checks, db_type="source")

def migration_completed_checks(tgt):
    schema_names = ["public", "non_public"]

    # Loop through each schema and run validation checks
    for schema_name in schema_names:
        print(f"Running validation checks for schema: {schema_name}")
        
        # Validation to check for matching row counts
        got_row_count = tgt.row_count_of_all_tables(schema_name)
        expected_row_count = EXPECTED_ROW_COUNT.get(schema_name, {})

        for table_name, row_count in expected_row_count.items():
            print(f"Schema: {schema_name}, Table: {table_name}, Expected Row Count: {row_count}, Got Row Count: {got_row_count[table_name]}")
            assert row_count == got_row_count[table_name], f"Row count mismatch for {table_name} in schema {schema_name}"
        
        # Validation for final varchar state (unique values)
        final_varchar_state = EXPECTED_FINAL_STATE_VARCHAR.get(schema_name, {})
        for table_name, column_final_state in final_varchar_state.items():
            print(f"Schema: {schema_name}, Table: {table_name}")
            for column, expected_values in column_final_state.items():
                actual_values = tgt.get_distinct_values__of_column_of_table(table_name, column, schema_name)
                assert sorted(actual_values) == sorted(expected_values), (
                    f"Unique values mismatch in {column} of {table_name}: "
                    f"Expected {expected_values}, Got {actual_values}"
                )
                print(f"Validation passed for {column} in {schema_name}.{table_name}")

if __name__ == "__main__":
    main()