#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)

EXPECTED_M_VIEW = ["employee_mv_immediate", "warranty_orders", "my_warranty_orders", "all_customers"]

#=============================================================================

def migration_completed_checks(tgt):
	table_list = tgt.get_objects_of_type("MVIEW")
	assert len(table_list) == len(EXPECTED_M_VIEW)
	assert set(table_list) == set(EXPECTED_M_VIEW)

	# REFRESH MATERIALIZED VIEW employee_mv_immediate;
	REFRESH_M_VIEW_QUERY = "REFRESH MATERIALIZED VIEW public.employee_mv_immediate;"
	tgt.run_query_and_chk_error(REFRESH_M_VIEW_QUERY, None)
	mv_row_count = tgt.get_row_count("employee_mv_immediate")
	print("Employee Immediate MView row count: {}".format(mv_row_count))
	assert mv_row_count == 12
 
	# Validating the rows in the fast refreshable materialized view
	warranty_orders_row_count = tgt.get_row_count("warranty_orders")
	print("Warranty Orders MView row count: {}".format(warranty_orders_row_count))
	assert warranty_orders_row_count == 621
 
	# Validating the number of rows in the nested materialized view
	my_warranty_orders_row_count = tgt.get_row_count("my_warranty_orders")
	print("My Warranty Orders MView row count: {}".format(my_warranty_orders_row_count))
	assert my_warranty_orders_row_count == 3105
 
	# Validating the number of rows in the auto refresh materialized view
	all_customers_row_count = tgt.get_row_count("all_customers")
	print("All customers MView row count: {}".format(all_customers_row_count))
	assert mv_row_count == 392
	INSERT_DATA_INTO_CUSTOMERS = "insert into customers (CUSTOMER_ID,EMAIL_ADDRESS,FULL_NAME) values (393,'adam.miller_dup@internalmail','Adam Miller Dup');"
	tgt.execute_query(INSERT_DATA_INTO_CUSTOMERS);
	print("Customers table row count after insert : {}".format(tgt.get_row_count("all_customers")))
	all_customers_row_count_after_insert = tgt.get_row_count("all_customers")
	assert all_customers_row_count_after_insert == 392
 
if __name__ == "__main__":
	main()
