#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database"
run_sqlplus ${SOURCE_DB_NAME} schema

echo "Creating the views on source database"
run_sqlplus ${SOURCE_DB_NAME} view_definition

echo "Populating data in source database"
run_sqlplus ${SOURCE_DB_NAME} customers_data
run_sqlplus ${SOURCE_DB_NAME} products_data
run_sqlplus ${SOURCE_DB_NAME} stores_data
run_sqlplus ${SOURCE_DB_NAME} orders_data
run_sqlplus ${SOURCE_DB_NAME} shipments_data
run_sqlplus ${SOURCE_DB_NAME} order_items
run_sqlplus ${SOURCE_DB_NAME} inventory

echo "Checking the row counts once data is created on the source DB"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM customers;"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM stores;"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM products;"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM orders;"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM shipments;"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM order_items;"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM inventory;"