#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database"
run_sqlplus ${SOURCE_DB_NAME} ddl/schema

echo "Creating the views on source database"
run_sqlplus ${SOURCE_DB_NAME} ddl/view_definition

echo "Populating data in source database"
run_sqlplus ${SOURCE_DB_NAME} dml/customers_data
run_sqlplus ${SOURCE_DB_NAME} dml/products_data
run_sqlplus ${SOURCE_DB_NAME} dml/stores_data
run_sqlplus ${SOURCE_DB_NAME} dml/orders_data
run_sqlplus ${SOURCE_DB_NAME} dml/shipments_data
run_sqlplus ${SOURCE_DB_NAME} dml/order_items
run_sqlplus ${SOURCE_DB_NAME} dml/inventory

echo "Checking the row counts once data is created on the source DB"
run_sqlplus ${SOURCE_DB_NAME} row_count_source_db