#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Assigning permissions to the validate files"
chmod +x ${TEST_DIR}/validate
chmod +x ${TEST_DIR}/validateAfterChanges

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i load_schema.sql;"
run_psql ${SOURCE_DB_NAME} "\i load_data.sql;"

if [ -n "${SOURCE_REPLICA_DB_NAME}" ];
then
	echo "Initialising FF database"
    run_psql ${SOURCE_REPLICA_DB_NAME} "\i load_schema.sql;"
fi