#!/usr/bin/env bash
# This script is used to run the migration tests on the jenkins testing pipeline.
# A few environment variables are required to be set before running the run-test
# script which is done by jenkins-wrapper.

export LD_LIBRARY_PATH=${LDLIBRARYPATH}
export TARGET_DB_HOST=${TARGET_DB_HOST}
export TARGET_DB_PORT=${TARGET_DB_PORT}
export TARGET_DB_USER=${TARGET_DB_USER}
export TARGET_DB_PASSWORD=${TARGET_DB_PASSWORD}
export TARGET_DB_ADMIN_USER=${TARGET_DB_ADMIN_USER}
export TARGET_DB_ADMIN_PASSWORD=${TARGET_DB_ADMIN_PASSWORD}
export TARGET_DB_SCHEMA=${TARGET_DB_SCHEMA}

bash "$@"
