#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."
psql_import_file ${SOURCE_DB_NAME}  pg_codependent_schemas.sql

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM primary_test;"
