#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Creating ${SOURCE_DB_NAME} database on source"
run_psql postgres "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_psql postgres "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Initialising source database."
psql_import_file ${SOURCE_DB_NAME} schema.sql
