#!/usr/bin/env python3

import os
import sys
import fileinput

with open("pgdatadir") as f:
    datadir=f.readline()

os.remove("pgdatadir")

with fileinput.input(datadir+"/postgresql.conf", inplace=True) as f:
    for line in f:
        new_line = line.replace("#ssl = off", "ssl = on")
        print(new_line, end='')