#!/usr/bin/env python3

import os
import sys
import fileinput
config_files=[]
with open("pgconfig") as f:
    for line in f:
        config_file=line.strip(" \n")
        config_files.append(config_file)
os.remove("pgconfig")

for config_file in config_files:
    print(f"Changing conf file {config_file}.")
    try:
        with open(config_file, 'r') as file:
            content = file.read()
    

        content = content.replace('#ssl = off', 'ssl = on')

        with open(config_file, 'w') as file:
            file.write(content)
    except:
        continue
