#!/usr/bin/env python3

import os
import sys
import fileinput

with open("pgconfig") as f:
    config_file=f.readline().strip(" \n")
os.remove("pgconfig")

with open(config_file, 'r') as file:
  content = file.read()

content = content.replace('#ssl = off', 'ssl = on')

with open(config_file, 'w') as file:
  file.write(content)