#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh


echo "Creating ${SOURCE_DB_NAME} database on source"
run_psql postgres "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_psql postgres "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i pg_ssl_automation.sql;"


echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM ssl_table1;"

echo "Enabling SSL connectivity."
run_psql ${SOURCE_DB_NAME} "show data_directory;" | head -n 3 | tail -n 1 > pgdatadir
sudo python3 enable-ssl
sudo systemctl list-units | grep postgres