#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_ROW_COUNT = {
	'sequence_check_1': 7,
	'sequence_check_2': 7,
	'sequence_check_3': 8
}

EXPECTED_TABLE_SUM = {
	'sequence_check_1': 28,
	'sequence_check_2': 371,
	'sequence_check_3': 1963
}

def migration_completed_checks(tgt):
	table_list = tgt.get_table_names("public")
	print("table_list:", table_list)
	assert len(table_list) == 3

	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	for table_name, _ in EXPECTED_ROW_COUNT.items():
		sum_column_values = tgt.get_sum_of_column_of_table(table_name, "id")
		print(f"table_name: {table_name}, sum_column_values: {sum_column_values}")
		assert sum_column_values == EXPECTED_TABLE_SUM[table_name]


if __name__ == "__main__":
	main()