#!/usr/bin/env python3

import common
import os
import oracle
import yb

def main():
	test_type_flags = common.valparser()

	migration_completed_checks_yb()
	
	if test_type_flags['ff_enabled'] == 'true':
		change_expected_values()
		migration_completed_checks_ff()

EXPECTED_ROW_COUNT = {
	'order_items_range_partitioned': 79,
	'order_items_range_partitioned_p1': 49,
	'order_items_range_partitioned_p2': 20,
 	'order_items_range_partitioned_p3': 10,
	'accounts_list_partitioned': 42,
	'accounts_list_partitioned_p_northcentral': 5,
	'accounts_list_partitioned_p_northeast': 11,
	'accounts_list_partitioned_p_northwest': 6,
	'accounts_list_partitioned_p_southcentral': 6,
	'accounts_list_partitioned_p_southeast': 7,
	'accounts_list_partitioned_p_southwest': 7,
	'orders_interval_partition': 105,
	'orders_interval_partition_interval_partition_less_than_2015': 1,
	'orders_interval_partition_interval_partition_less_than_2016': 13,
	'orders_interval_partition_interval_partition_less_than_2017': 79,
	'orders_interval_partition_interval_partition_less_than_2018': 12,
	'sales_hash': 30,
	'sales_hash_p1': 17,
	'sales_hash_p2': 7,
	'sales_hash_p3': 6,
	'sales_hash_p4': 0,
	'sub_par_test': 22,
	'sub_par_test_p1': 6,
	'sub_par_test_p1_sp1': 2,
	'sub_par_test_p1_sp11': 4,
	'sub_par_test_p2': 5,
	'sub_par_test_p2_sp2': 1,
	'sub_par_test_p2_sp22': 4,
	'sub_par_test_p3': 5,
	'sub_par_test_p3_sp3': 1,
	'sub_par_test_p3_sp33': 4,
	'sub_par_test_p4': 5,
	'sub_par_test_p4_sp4': 1,
	'sub_par_test_p4_sp44': 4,
	'sub_par_test_p5': 1,
	'sub_par_test_p5_sp5': 1,
}

EXPECTED_ROW_COUNT_FF = {
	'order_items_range_partitioned': 79,
	'accounts_list_partitioned': 42,
	'orders_interval_partition': 105,
	'sales_hash': 30,
	'sub_par_test': 22,
}


INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION = {
	"List" : {
		"insert_query": "INSERT INTO ACCOUNTS_LIST_PARTITIONED values (600, 106, 16,210,'NJ','I');",
		"delete_query": "DELETE FROM ACCOUNTS_LIST_PARTITIONED WHERE ACCOUNT_ID = 600;",
		"partition_table_name": "accounts_list_partitioned_p_northeast",
	},
	"Range" : {
		"insert_query": "INSERT INTO ORDERS_INTERVAL_PARTITION(ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (1000,1,'Pending',54,to_date('17-NOV-17','DD-MON-YY'));",
		"delete_query": "DELETE FROM ORDERS_INTERVAL_PARTITION WHERE ORDER_ID = 1000;",
		"partition_table_name": "orders_interval_partition_interval_partition_less_than_2018",
	},
	"Range_Column" : {
		"insert_query": "INSERT INTO ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (65,to_timestamp('04-FEB-2018 13.20.22.245676861','DD-MON-YYYY HH24.MI.SS.FF'),9,1,'CANCELLED');",
		"delete_query": "DELETE FROM ORDER_ITEMS_RANGE_PARTITIONED WHERE ORDER_ID = 65;",
		"partition_table_name": "order_items_range_partitioned_p2",
	},
	"Hash" : {
		"insert_query": " Insert into SALES_HASH values (400, to_date('26-NOV-03','DD-MON-YY'), 104, 2129.55);",
		"delete_query": "DELETE FROM SALES_HASH WHERE S_PRODUCTID = 400 AND S_CUSTID = 104;",
		"partition_table_name": "sales_hash_p4",
	},
	"Sub_Partition": {
		"insert_query": " Insert into sub_par_test values (23,'emp_23','OTHERS',TO_DATE('18-08-2006', 'dd-mm-yyyy')); ",
		"delete_query": "DELETE FROM sub_par_test WHERE id = 23;",
		"partition_table_name": "sub_par_test_p5_sp5",
	}
}

INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION_FF = {
	"List" : {
		"insert_query": "INSERT INTO ACCOUNTS_LIST_PARTITIONED values (600, 106, 16,210,'NJ','I')",
		"delete_query": "DELETE FROM ACCOUNTS_LIST_PARTITIONED WHERE ID = 600",
		"partition_table_name": "accounts_list_partitioned",
	},
	"Range" : {
		"insert_query": "INSERT INTO ORDERS_INTERVAL_PARTITION(ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (1000,1,'Pending',54,to_date('17-NOV-17','DD-MON-YY'))",
		"delete_query": "DELETE FROM ORDERS_INTERVAL_PARTITION WHERE ORDER_ID = 1000",
		"partition_table_name": "orders_interval_partition",
	},
	"Range_Column" : {
		"insert_query": "INSERT INTO ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (65,to_timestamp('04-FEB-2018 13.20.22.245676861','DD-MON-YYYY HH24.MI.SS.FF'),9,1,'CANCELLED')",
		"delete_query": "DELETE FROM ORDER_ITEMS_RANGE_PARTITIONED WHERE ORDER_ID = 65",
		"partition_table_name": "order_items_range_partitioned",
	},
	"Hash" : {
		"insert_query": "Insert into SALES_HASH values (400, to_date('26-NOV-03','DD-MON-YY'), 104, 2129.55)",
		"delete_query": "DELETE FROM SALES_HASH WHERE SALE_ID = 400",
		"partition_table_name": "sales_hash",
	},
	"Sub_Partition": {
		"insert_query": "Insert into sub_par_test values (23,'emp_23','OTHERS',TO_DATE('18-08-2006', 'dd-mm-yyyy')) ",
		"delete_query": "DELETE FROM sub_par_test WHERE id = 23",
		"partition_table_name": "sub_par_test",
	}
}
#=============================================================================

def migration_completed_checks_yb():
	print("Running tests on YB")
	global db_schema
	db_schema="public"
	yb.run_checks(migration_completed_checks)
# 	yb.run_checks(YB_specific_checks)

# def YB_specific_checks(tgt):
# 	yb.verify_colocation(tgt, "oracle")

def migration_completed_checks_ff():
	print("Running tests on Oracle source replica")
	global db_schema
	db_schema = os.environ.get("SOURCE_REPLICA_DB_SCHEMA")
	oracle.run_checks(migration_completed_checks, db_type="source_replica")

def change_expected_values():
	keys_to_delete = []
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		if table_name not in EXPECTED_ROW_COUNT_FF:
			keys_to_delete.append(table_name)

	for key in keys_to_delete:
		del EXPECTED_ROW_COUNT[key]

	for partition_type, query_and_table in INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION_FF.items():
		INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION[partition_type]["insert_query"] = query_and_table["insert_query"]
		INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION[partition_type]["delete_query"] = query_and_table["delete_query"]
		INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION[partition_type]["partition_table_name"] = query_and_table["partition_table_name"]
	

def migration_completed_checks(tgt):
	got_row_count = tgt.row_count_of_all_tables(db_schema)
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	for partition_type, query_and_table in INSERT_QUERIES_INTO_TABLE_VERIFY_PARTITION.items():
		run_insert_query_and_chk_incr_cnt_of_partition_table(tgt, query_and_table["insert_query"], query_and_table["delete_query"], query_and_table["partition_table_name"], db_schema)

def run_insert_query_and_chk_incr_cnt_of_partition_table(tgt, insert_query, delete_query, partition_table_name, schema_name):
	chk_error_returned = tgt.run_query_and_chk_error(insert_query, None)
	print(f"error returned while insert ({insert_query}) query - {chk_error_returned}")
	assert chk_error_returned == False

	count_partition_table = tgt.get_row_count(partition_table_name, schema_name)
	print(f"count returned for partition ({partition_table_name}) - {count_partition_table} ")
	assert count_partition_table == EXPECTED_ROW_COUNT[partition_table_name] + 1

	chk_error_returned = tgt.run_query_and_chk_error(delete_query, None)
	print(f"error returned while delete ({delete_query}) query - {chk_error_returned}")
	assert chk_error_returned == False

if __name__ == "__main__":
	main()