/*
Copyright (c) YugabyteDB, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
This package has all logic related to detecting issues in queries (DDL or DML).
Entry point is ParserIssueDetector, which makes use queryparser pkg to parse
the query and multiple detectors to figure out issues in the parseTree.
*/
package queryissue

import (
	"github.com/yugabyte/yb-voyager/yb-voyager/src/issue"
)

type QueryIssue struct {
	issue.Issue
	ObjectType   string // TABLE, FUNCTION, DML_QUERY?
	ObjectName   string // table name/function name/etc
	SqlStatement string
	Details      map[string]interface{} // additional details about the issue
}

func newQueryIssue(issue issue.Issue, objectType string, objectName string, sqlStatement string, details map[string]interface{}) QueryIssue {
	return QueryIssue{
		Issue:        issue,
		ObjectType:   objectType,
		ObjectName:   objectName,
		SqlStatement: sqlStatement,
		Details:      details,
	}
}

var MigrationCaveatsIssues = []string{
	ALTER_TABLE_ADD_PK_ON_PARTITIONED_TABLE,
	FOREIGN_TABLE,
	POLICY_WITH_ROLES,
}

var UnsupportedDatatypesInLiveMigrationIssues = []string{
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_POINT,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_LINE,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_LSEG,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_BOX,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_PATH,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_POLYGON,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_CIRCLE,
}

var UnsupportedDatatypesInLiveMigrationIssuesWithFForFBIssues = []string{
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_WITH_FF_FB_ARRAY_OF_ENUM,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_WITH_FF_FB_USER_DEFINED,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_WITH_FF_FB_TSQUERY,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_WITH_FF_FB_TSVECTOR,
	UNSUPPORTED_DATATYPE_LIVE_MIGRATION_WITH_FF_FB_HSTORE,
}

var PerformanceOptimizationIssues = []string{
	HOTSPOTS_ON_DATE_INDEX,
	HOTSPOTS_ON_TIMESTAMP_INDEX,
	REDUNDANT_INDEXES,
	LOW_CARDINALITY_INDEXES, 
	MOST_FREQUENT_VALUE_INDEXES,
	NULL_VALUE_INDEXES,
}

var IssueTypesForModifyingIssueNameWithExtraDetails = []string{
	LOW_CARDINALITY_INDEXES,
	MOST_FREQUENT_VALUE_INDEXES,
	NULL_VALUE_INDEXES,
}

var UnsupportedSystemColumnsIssueTypes = []string{
	SYSTEM_COLUMN_XMIN,
	SYSTEM_COLUMN_XMAX,
	SYSTEM_COLUMN_CMIN,
	SYSTEM_COLUMN_CMAX,
	SYSTEM_COLUMN_CTID,
}

type IssueTypeAndName struct {
	IssueType string
	IssueName string
}

var PkOrUkOnComplexDatatypesIssues = []IssueTypeAndName{
	{PK_UK_ON_CITEXT_DATATYPE, PK_UK_ON_CITEXT_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_TSVECTOR_DATATYPE, PK_UK_ON_TSVECTOR_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_TSQUERY_DATATYPE, PK_UK_ON_TSQUERY_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_JSONB_DATATYPE, PK_UK_ON_JSONB_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_INET_DATATYPE, PK_UK_ON_INET_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_JSON_DATATYPE, PK_UK_ON_JSON_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_MACADDR_DATATYPE, PK_UK_ON_MACADDR_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_MACADDR8_DATATYPE, PK_UK_ON_MACADDR8_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_CIDR_DATATYPE, PK_UK_ON_CIDR_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_BIT_DATATYPE, PK_UK_ON_BIT_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_VARBIT_DATATYPE, PK_UK_ON_VARBIT_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_DATERANGE_DATATYPE, PK_UK_ON_DATERANGE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_TSRANGE_DATATYPE, PK_UK_ON_TSRANGE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_TSTZRANGE_DATATYPE, PK_UK_ON_TSTZRANGE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_NUMRANGE_DATATYPE, PK_UK_ON_NUMRANGE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_INT4RANGE_DATATYPE, PK_UK_ON_INT4RANGE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_INT8RANGE_DATATYPE, PK_UK_ON_INT8RANGE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_INTERVAL_DATATYPE, PK_UK_ON_INTERVAL_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_CIRCLE_DATATYPE, PK_UK_ON_CIRCLE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_BOX_DATATYPE, PK_UK_ON_BOX_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_LINE_DATATYPE, PK_UK_ON_LINE_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_LSEG_DATATYPE, PK_UK_ON_LSEG_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_POINT_DATATYPE, PK_UK_ON_POINT_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_PGLSN_DATATYPE, PK_UK_ON_PGLSN_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_PATH_DATATYPE, PK_UK_ON_PATH_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_POLYGON_DATATYPE, PK_UK_ON_POLYGON_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_TXID_SNAPSHOT_DATATYPE, PK_UK_ON_TXID_SNAPSHOT_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_ARRAY_DATATYPE, PK_UK_ON_ARRAY_DATATYPE_ISSUE_NAME},
	{PK_UK_ON_USER_DEFINED_DATATYPE, PK_UK_ON_USER_DEFINED_DATATYPE_ISSUE_NAME},
}

var IndexOnComplexDatatypesIssues = []IssueTypeAndName{
	{INDEX_ON_CITEXT_DATATYPE, INDEX_ON_CITEXT_DATATYPE_ISSUE_NAME},
	{INDEX_ON_TSVECTOR_DATATYPE, INDEX_ON_TSVECTOR_DATATYPE_ISSUE_NAME},
	{INDEX_ON_TSQUERY_DATATYPE, INDEX_ON_TSQUERY_DATATYPE_ISSUE_NAME},
	{INDEX_ON_JSONB_DATATYPE, INDEX_ON_JSONB_DATATYPE_ISSUE_NAME},
	{INDEX_ON_INET_DATATYPE, INDEX_ON_INET_DATATYPE_ISSUE_NAME},
	{INDEX_ON_JSON_DATATYPE, INDEX_ON_JSON_DATATYPE_ISSUE_NAME},
	{INDEX_ON_MACADDR_DATATYPE, INDEX_ON_MACADDR_DATATYPE_ISSUE_NAME},
	{INDEX_ON_MACADDR8_DATATYPE, INDEX_ON_MACADDR8_DATATYPE_ISSUE_NAME},
	{INDEX_ON_CIDR_DATATYPE, INDEX_ON_CIDR_DATATYPE_ISSUE_NAME},
	{INDEX_ON_BIT_DATATYPE, INDEX_ON_BIT_DATATYPE_ISSUE_NAME},
	{INDEX_ON_VARBIT_DATATYPE, INDEX_ON_VARBIT_DATATYPE_ISSUE_NAME},
	{INDEX_ON_DATERANGE_DATATYPE, INDEX_ON_DATERANGE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_TSRANGE_DATATYPE, INDEX_ON_TSRANGE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_TSTZRANGE_DATATYPE, INDEX_ON_TSTZRANGE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_NUMRANGE_DATATYPE, INDEX_ON_NUMRANGE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_INT4RANGE_DATATYPE, INDEX_ON_INT4RANGE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_INT8RANGE_DATATYPE, INDEX_ON_INT8RANGE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_INTERVAL_DATATYPE, INDEX_ON_INTERVAL_DATATYPE_ISSUE_NAME},
	{INDEX_ON_CIRCLE_DATATYPE, INDEX_ON_CIRCLE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_BOX_DATATYPE, INDEX_ON_BOX_DATATYPE_ISSUE_NAME},
	{INDEX_ON_LINE_DATATYPE, INDEX_ON_LINE_DATATYPE_ISSUE_NAME},
	{INDEX_ON_LSEG_DATATYPE, INDEX_ON_LSEG_DATATYPE_ISSUE_NAME},
	{INDEX_ON_POINT_DATATYPE, INDEX_ON_POINT_DATATYPE_ISSUE_NAME},
	{INDEX_ON_PG_LSN_DATATYPE, INDEX_ON_PG_LSN_DATATYPE_ISSUE_NAME},
	{INDEX_ON_PATH_DATATYPE, INDEX_ON_PATH_DATATYPE_ISSUE_NAME},
	{INDEX_ON_POLYGON_DATATYPE, INDEX_ON_POLYGON_DATATYPE_ISSUE_NAME},
	{INDEX_ON_TXID_SNAPSHOT_DATATYPE, INDEX_ON_TXID_SNAPSHOT_DATATYPE_ISSUE_NAME},
	{INDEX_ON_ARRAY_DATATYPE, INDEX_ON_ARRAY_DATATYPE_ISSUE_NAME},
	{INDEX_ON_USER_DEFINED_DATATYPE, INDEX_ON_USER_DEFINED_DATATYPE_ISSUE_NAME},
}
