#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_ROW_COUNT = {
	'view_table1': 11,
	'view_table2': 9,
	'v1': 6,
	'v2': 9,
	'v3': 9,
	'mv1': 4,
}

def migration_completed_checks(tgt):
	table_list = tgt.get_table_names("test_case")
	print("table_list:", table_list)
	assert len(table_list) == 2

	view_list = tgt.get_objects_of_type("VIEW", "test_case")
	print("view_list:", view_list)
	assert len(view_list) == 3

	materialized_view_list = tgt.get_objects_of_type("MVIEW", "test_case")
	print("materialized_view_list:", view_list)
	assert len(materialized_view_list) == 1
	
	chk_err_while_refresh_mview = tgt.run_query_and_chk_error("REFRESH MATERIALIZED VIEW test_case.mv1;", None)
	print(f"Refreshing materialised views error chk returned - {chk_err_while_refresh_mview}")
	assert chk_err_while_refresh_mview == False

	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		cnt = tgt.get_row_count(table_name, "test_case")
		print(f"table_name: {table_name}, row_count: {cnt}")
		assert row_count == cnt


if __name__ == "__main__":
	main()