#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Deleting existing data in target database"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TESTS_DIR}/oracle/utils/delete_full_schema

echo "Initialising source database & inserting data"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} oracle_assessment_report.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../partitions/partition_schema.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../partitions/partition_data.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../misc-tests/schema.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../views-mviews/views_schema_data.sql
