#!/usr/bin/env bash
source migtests/scripts/postgresql/env.sh
source migtests/scripts/functions.sh

# cmd="CREATE USER ${SOURCE_DB_USER} PASSWORD '${SOURCE_DB_PASSWORD}';"
cmd="SELECT 'CREATE USER ${SOURCE_DB_USER} PASSWORD ''${SOURCE_DB_PASSWORD}'''
WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${SOURCE_DB_USER}')\gexec"
run_psql "postgres" "${cmd}"
