#!/usr/bin/env bash
source migtests/scripts/postgresql/env.sh
source migtests/scripts/functions.sh

cmd="CREATE USER ${SOURCE_DB_USER} PASSWORD '${SOURCE_DB_PASSWORD}';"
run_psql "postgres" "${cmd}"
	