export SOURCE_DB_HOST=${SOURCE_DB_HOST:-"127.0.0.1"}
export SOURCE_DB_PORT=${SOURCE_DB_PORT:-5435}
export SOURCE_DB_USER=${SOURCE_DB_USER:-"postgres"}
export SOURCE_DB_PASSWORD=${SOURCE_DB_PASSWORD:-'postgres'}
export SOURCE_DB_ADMIN_USER=${SOURCE_DB_ADMIN_USER:-"postgres"}
export SOURCE_DB_ADMIN_PASSWORD=${SOURCE_DB_ADMIN_PASSWORD:-"postgres"}
