export SOURCE_DB_HOST=${SOURCE_DB_HOST:-"10.9.84.34"}
export SOURCE_DB_PORT=${SOURCE_DB_PORT:-5432}
export SOURCE_DB_USER=${SOURCE_DB_USER:-"ybvoyager"}
export SOURCE_DB_PASSWORD=${SOURCE_DB_PASSWORD:-'password'}
export SOURCE_DB_ADMIN_USER=${SOURCE_DB_ADMIN_USER:-"yugabyte"}
export SOURCE_DB_ADMIN_PASSWORD=${SOURCE_DB_ADMIN_PASSWORD:-"password"}
