export SOURCE_REPLICA_DB_NAME=${SOURCE_REPLICA_DB_NAME:-"ff_db"}
export SOURCE_REPLICA_DB_HOST=${SOURCE_REPLICA_DB_HOST:-"127.0.0.1"}
export SOURCE_REPLICA_DB_PORT=${SOURCE_REPLICA_DB_PORT:-"5435"}
export SOURCE_REPLICA_DB_USER=${SOURCE_REPLICA_DB_USER:-"postgres"}
export SOURCE_REPLICA_DB_PASSWORD=${SOURCE_REPLICA_DB_PASSWORD:-"postgres"}