
CREATE TABLE test_timezone(id integer primary key, dtts TIMESTAMP(9));
ALTER TABLE test_timezone add constraint test_cc1 check((dtts = trunc(dtts)));

INSERT INTO test_timezone values (1,'2-NOV-92');


CREATE TABLE "group" (
    id int PRIMARY KEY,
    name varchar(10)
);

CREATE TABLE reserved_column (
    "user" int,
    "case" varchar(10)
);

CREATE TABLE "check" (
    "user" int,
    "case" varchar(10)
);

INSERT into "group" values(1, 'abc');
INSERT into "group" values(2, 'abc');
INSERT into "group" values(3, 'abc');
INSERT into "group" values(4, 'abc');
INSERT into "group" values(5, 'abc');

INSERT into reserved_column values(1, 'abc');
INSERT into reserved_column values(2, 'abc');
INSERT into reserved_column values(3, 'abc');
INSERT into reserved_column values(4, 'abc');
INSERT into reserved_column values(5, 'abc');

INSERT into "check" values(1, 'abc');
INSERT into "check" values(2, 'abc');
INSERT into "check" values(3, 'abc');
INSERT into "check" values(4, 'abc');
INSERT into "check" values(5, 'abc');

drop table if exists session_log;

create table session_log 
( 
   userid int not null, 
   phonenumber int
); 


create table session_log1 
( 
   userid int not null, 
   phonenumber int
); 


create table session_log2 
( 
   userid int not null, 
   phonenumber int
); 

create table session_log3 
( 
   userid int not null, 
   phonenumber int
); 

create table session_log4 
( 
   userid int not null, 
   phonenumber int
); 

CREATE OR REPLACE PROCEDURE insert_session_logs AS
    i INT := 1;
BEGIN
    WHILE i <= 100 LOOP
        INSERT INTO session_log VALUES (i, i);
        INSERT INTO session_log1 VALUES (i, i);
        INSERT INTO session_log2 VALUES (i, i);
        INSERT INTO session_log3 VALUES (i, i);
        INSERT INTO session_log4 VALUES (i, i);
        i := i + 1;
    END LOOP;
END insert_session_logs;
/

-- Call the procedure
BEGIN
    insert_session_logs;
END;
/

CREATE TABLE "Mixed_Case_Table_Name_Test" (
	id int GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(50) not null,
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);
insert into "Mixed_Case_Table_Name_Test" (first_name, last_name, email, gender, ip_address) values ('Modestine', 'MacMeeking', 'mmacmeeking0@zimbio.com', 'Female', '208.44.58.185');
insert into "Mixed_Case_Table_Name_Test" (first_name, last_name, email, gender, ip_address) values ('Genna', 'Kaysor', 'gkaysor1@hibu.com', 'Female', '202.48.51.58');
insert into "Mixed_Case_Table_Name_Test" (first_name, last_name, email, gender, ip_address) values ('Tess', 'Wesker', 'twesker2@scientificamerican.com', 'Female', '177.153.32.186');
insert into "Mixed_Case_Table_Name_Test" (first_name, last_name, email, gender, ip_address) values ('Magnum', 'Danzelman', 'mdanzelman3@storify.com', 'Bigender', '192.200.33.56');
insert into "Mixed_Case_Table_Name_Test" (first_name, last_name, email, gender, ip_address) values ('Mitzi', 'Pidwell', 'mpidwell4@shutterfly.com', 'Female', '216.4.250.71');
insert into "Mixed_Case_Table_Name_Test" (first_name, last_name, email, gender, ip_address) values ('Milzie', 'Rohlfing', 'mrohlfing5@java.com', 'Female', '230.101.87.42');

CREATE TABLE "Case_Sensitive_Columns" (
	id int GENERATED BY DEFAULT AS IDENTITY,
	"First_Name" VARCHAR(50) not null,
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	ip_address VARCHAR(20)
);
insert into "Case_Sensitive_Columns" ("First_Name", last_name, email, gender, ip_address) values ('Modestine', 'MacMeeking', 'mmacmeeking0@zimbio.com', 'Female', '208.44.58.185');
insert into "Case_Sensitive_Columns" ("First_Name", last_name, email, gender, ip_address) values ('Genna', 'Kaysor', 'gkaysor1@hibu.com', 'Female', '202.48.51.58');
insert into "Case_Sensitive_Columns" ("First_Name", last_name, email, gender, ip_address) values ('Tess', 'Wesker', 'twesker2@scientificamerican.com', 'Female', '177.153.32.186');
insert into "Case_Sensitive_Columns" ("First_Name", last_name, email, gender, ip_address) values ('Magnum', 'Danzelman', 'mdanzelman3@storify.com', 'Bigender', '192.200.33.56');
insert into "Case_Sensitive_Columns" ("First_Name", last_name, email, gender, ip_address) values ('Mitzi', 'Pidwell', 'mpidwell4@shutterfly.com', 'Female', '216.4.250.71');
insert into "Case_Sensitive_Columns" ("First_Name", last_name, email, gender, ip_address) values ('Milzie', 'Rohlfing', 'mrohlfing5@java.com', 'Female', '230.101.87.42');

create table c(id int, c char(100),nc nchar(100));

insert into c values(1,'abc','abc');
insert into c values(2,'\a','\a'); 
insert into c values(3,'null','NULL');
insert into c values(4,'
','tt');
insert into c values(5,'	','abc');
insert into c values(6,'abc	abc','abc'); 
insert into c values(7,'abc
abc','abc');
insert into c values(8,'"abc"','ab"');
insert into c values(9,'"abc"','"abcn''"');
insert into c values(10,'abc abc','abc abc'); 
insert into c values(11,NULL,'abc');
insert into c values(12,'abc',null);


create table c1(id int, vc varchar2(100),nvc nvarchar2(100));
insert into c1 values(4,'
','tt');
insert into c1 values(5,'	','abc');