#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

# Run the schema SQL script
psql_import_file ${SOURCE_DB_NAME} schema-perf-optimization.sql

echo "End of script"