    --RANGE PARTITION DATA

BEGIN
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (1,to_timestamp('04-FEB-2018 13.20.22.245676861','DD-MON-YYYY HH24.MI.SS.FF'),3,1,'CANCELLED');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (2,to_timestamp('08-FEB-2018 20.58.10.472721115','DD-MON-YYYY HH24.MI.SS.FF'),45,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (3,to_timestamp('09-FEB-2018 23.17.07.242517323','DD-MON-YYYY HH24.MI.SS.FF'),18,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (4,to_timestamp('10-FEB-2018 13.43.36.061928731','DD-MON-YYYY HH24.MI.SS.FF'),45,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (5,to_timestamp('11-FEB-2018 18.01.30.906119035','DD-MON-YYYY HH24.MI.SS.FF'),2,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (6,to_timestamp('13-FEB-2018 20.11.48.702319539','DD-MON-YYYY HH24.MI.SS.FF'),74,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (7,to_timestamp('22-FEB-2018 00.57.11.011114421','DD-MON-YYYY HH24.MI.SS.FF'),9,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (8,to_timestamp('22-FEB-2018 15.00.52.003836100','DD-MON-YYYY HH24.MI.SS.FF'),109,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (9,to_timestamp('23-FEB-2018 13.25.26.824165229','DD-MON-YYYY HH24.MI.SS.FF'),127,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (10,to_timestamp('23-FEB-2018 14.02.10.185866897','DD-MON-YYYY HH24.MI.SS.FF'),106,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (11,to_timestamp('24-FEB-2018 02.05.31.903891365','DD-MON-YYYY HH24.MI.SS.FF'),68,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (12,to_timestamp('24-FEB-2018 09.54.16.110488621','DD-MON-YYYY HH24.MI.SS.FF'),127,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (13,to_timestamp('24-FEB-2018 11.44.43.690930433','DD-MON-YYYY HH24.MI.SS.FF'),99,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (14,to_timestamp('24-FEB-2018 17.50.02.729015363','DD-MON-YYYY HH24.MI.SS.FF'),101,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (15,to_timestamp('26-FEB-2018 17.43.17.366895115','DD-MON-YYYY HH24.MI.SS.FF'),119,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (16,to_timestamp('26-FEB-2018 23.42.54.082180815','DD-MON-YYYY HH24.MI.SS.FF'),119,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (17,to_timestamp('27-FEB-2018 07.47.46.606030496','DD-MON-YYYY HH24.MI.SS.FF'),16,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (18,to_timestamp('28-FEB-2018 18.42.54.719578735','DD-MON-YYYY HH24.MI.SS.FF'),39,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (19,to_timestamp('01-MAR-2018 06.09.26.634522376','DD-MON-YYYY HH24.MI.SS.FF'),49,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (20,to_timestamp('01-MAR-2018 10.07.32.467335385','DD-MON-YYYY HH24.MI.SS.FF'),3,3,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (21,to_timestamp('01-MAR-2018 18.38.27.438668681','DD-MON-YYYY HH24.MI.SS.FF'),144,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (22,to_timestamp('01-MAR-2018 22.55.29.698737465','DD-MON-YYYY HH24.MI.SS.FF'),80,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (23,to_timestamp('02-MAR-2018 11.52.28.359515482','DD-MON-YYYY HH24.MI.SS.FF'),67,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (24,to_timestamp('02-MAR-2018 15.53.19.496456408','DD-MON-YYYY HH24.MI.SS.FF'),81,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (25,to_timestamp('03-MAR-2018 06.39.48.533448772','DD-MON-YYYY HH24.MI.SS.FF'),42,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (26,to_timestamp('03-MAR-2018 09.30.59.972993409','DD-MON-YYYY HH24.MI.SS.FF'),126,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (27,to_timestamp('03-MAR-2018 16.28.34.339865950','DD-MON-YYYY HH24.MI.SS.FF'),148,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (28,to_timestamp('05-MAR-2018 00.33.33.690222408','DD-MON-YYYY HH24.MI.SS.FF'),139,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (29,to_timestamp('06-MAR-2018 11.03.10.204845586','DD-MON-YYYY HH24.MI.SS.FF'),55,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (30,to_timestamp('06-MAR-2018 17.53.59.405863523','DD-MON-YYYY HH24.MI.SS.FF'),206,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (31,to_timestamp('07-MAR-2018 10.12.11.248485798','DD-MON-YYYY HH24.MI.SS.FF'),122,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (32,to_timestamp('07-MAR-2018 19.55.05.581612443','DD-MON-YYYY HH24.MI.SS.FF'),32,3,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (33,to_timestamp('08-MAR-2018 01.20.10.569196457','DD-MON-YYYY HH24.MI.SS.FF'),65,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (34,to_timestamp('09-MAR-2018 00.16.29.279807968','DD-MON-YYYY HH24.MI.SS.FF'),71,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (35,to_timestamp('09-MAR-2018 13.25.35.573762816','DD-MON-YYYY HH24.MI.SS.FF'),31,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (36,to_timestamp('10-MAR-2018 02.51.51.860595535','DD-MON-YYYY HH24.MI.SS.FF'),217,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (37,to_timestamp('10-MAR-2018 21.37.23.229443857','DD-MON-YYYY HH24.MI.SS.FF'),116,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (38,to_timestamp('11-MAR-2018 15.23.33.673327449','DD-MON-YYYY HH24.MI.SS.FF'),131,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (39,to_timestamp('12-MAR-2018 00.53.54.816639885','DD-MON-YYYY HH24.MI.SS.FF'),193,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (40,to_timestamp('12-MAR-2018 07.14.13.124763728','DD-MON-YYYY HH24.MI.SS.FF'),194,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (41,to_timestamp('12-MAR-2018 13.27.22.180940468','DD-MON-YYYY HH24.MI.SS.FF'),115,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (42,to_timestamp('12-MAR-2018 16.57.16.442468392','DD-MON-YYYY HH24.MI.SS.FF'),184,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (43,to_timestamp('12-MAR-2018 23.47.56.795113310','DD-MON-YYYY HH24.MI.SS.FF'),121,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (44,to_timestamp('13-MAR-2018 05.28.48.295881349','DD-MON-YYYY HH24.MI.SS.FF'),162,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (45,to_timestamp('13-MAR-2018 14.51.24.003858043','DD-MON-YYYY HH24.MI.SS.FF'),81,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (46,to_timestamp('14-MAR-2018 00.26.31.884618245','DD-MON-YYYY HH24.MI.SS.FF'),73,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (47,to_timestamp('14-MAR-2018 09.59.09.696949426','DD-MON-YYYY HH24.MI.SS.FF'),115,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (48,to_timestamp('14-MAR-2018 14.54.16.350538742','DD-MON-YYYY HH24.MI.SS.FF'),71,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (49,to_timestamp('14-MAR-2018 15.59.04.218807998','DD-MON-YYYY HH24.MI.SS.FF'),121,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (50,to_timestamp('15-MAR-2018 08.04.35.364043188','DD-MON-YYYY HH24.MI.SS.FF'),135,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (51,to_timestamp('15-MAR-2018 08.40.04.771303774','DD-MON-YYYY HH24.MI.SS.FF'),65,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (52,to_timestamp('15-MAR-2018 13.35.30.310001854','DD-MON-YYYY HH24.MI.SS.FF'),229,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (53,to_timestamp('16-MAR-2018 01.21.22.224575262','DD-MON-YYYY HH24.MI.SS.FF'),224,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (54,to_timestamp('16-MAR-2018 17.21.33.275456267','DD-MON-YYYY HH24.MI.SS.FF'),227,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (55,to_timestamp('17-MAR-2018 06.01.16.749462958','DD-MON-YYYY HH24.MI.SS.FF'),62,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (56,to_timestamp('17-MAR-2018 09.37.37.836100633','DD-MON-YYYY HH24.MI.SS.FF'),84,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (57,to_timestamp('18-MAR-2018 03.02.21.657881523','DD-MON-YYYY HH24.MI.SS.FF'),168,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (58,to_timestamp('18-MAR-2018 04.07.52.903345273','DD-MON-YYYY HH24.MI.SS.FF'),61,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (59,to_timestamp('19-MAR-2018 12.14.18.810205139','DD-MON-YYYY HH24.MI.SS.FF'),244,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (60,to_timestamp('20-MAR-2018 00.07.13.591683621','DD-MON-YYYY HH24.MI.SS.FF'),23,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (61,to_timestamp('21-MAR-2018 05.14.10.770541062','DD-MON-YYYY HH24.MI.SS.FF'),162,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (62,to_timestamp('22-MAR-2018 00.08.19.213828219','DD-MON-YYYY HH24.MI.SS.FF'),200,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (63,to_timestamp('22-MAR-2018 06.17.24.214467602','DD-MON-YYYY HH24.MI.SS.FF'),3,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (64,to_timestamp('22-MAR-2018 06.48.22.843491687','DD-MON-YYYY HH24.MI.SS.FF'),219,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (65,to_timestamp('22-MAR-2018 17.38.04.080685865','DD-MON-YYYY HH24.MI.SS.FF'),161,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (66,to_timestamp('22-MAR-2018 17.50.53.273051181','DD-MON-YYYY HH24.MI.SS.FF'),60,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (67,to_timestamp('23-MAR-2018 05.10.28.203691156','DD-MON-YYYY HH24.MI.SS.FF'),187,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (68,to_timestamp('23-MAR-2018 06.23.19.410046289','DD-MON-YYYY HH24.MI.SS.FF'),86,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (69,to_timestamp('24-MAR-2018 02.01.00.119936812','DD-MON-YYYY HH24.MI.SS.FF'),155,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (70,to_timestamp('24-MAR-2018 10.38.02.420847000','DD-MON-YYYY HH24.MI.SS.FF'),96,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (71,to_timestamp('25-MAR-2018 01.40.29.672465543','DD-MON-YYYY HH24.MI.SS.FF'),247,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (72,to_timestamp('26-MAR-2018 21.12.19.453775963','DD-MON-YYYY HH24.MI.SS.FF'),80,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (73,to_timestamp('27-MAR-2018 04.56.01.176469127','DD-MON-YYYY HH24.MI.SS.FF'),258,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (74,to_timestamp('27-MAR-2018 07.48.10.178559686','DD-MON-YYYY HH24.MI.SS.FF'),235,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (75,to_timestamp('27-MAR-2018 08.54.31.232771918','DD-MON-YYYY HH24.MI.SS.FF'),146,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (76,to_timestamp('27-MAR-2018 20.02.49.082218724','DD-MON-YYYY HH24.MI.SS.FF'),249,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (77,to_timestamp('28-MAR-2018 08.53.58.780133710','DD-MON-YYYY HH24.MI.SS.FF'),294,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (78,to_timestamp('28-MAR-2018 09.56.00.702240909','DD-MON-YYYY HH24.MI.SS.FF'),20,1,'COMPLETE');
  Insert into ORDER_ITEMS_RANGE_PARTITIONED (ORDER_ID,ORDER_DATETIME,CUSTOMER_ID,STORE_ID,ORDER_STATUS) values (79,to_timestamp('29-MAR-2018 03.35.02.671013150','DD-MON-YYYY HH24.MI.SS.FF'),14,1,'COMPLETE');
END;
/

--LIST PARTITIONED DATA

DECLARE
    TYPE REGARRAY is VARRAY(14) OF VARCHAR2(2);
    TYPE BRANCHARRAY IS VARRAY(10) OF NUMBER;
    TYPE STATUSARRAY IS VARRAY(3) OF VARCHAR2(2);
    region REGARRAY;
    branch BRANCHARRAY;
    status STATUSARRAY;
BEGIN
    region := REGARRAY('OR','WA','AZ', 'UT', 'NM','NY', 'VM', 'NJ','FL', 'GA','SD', 'WI','OK', 'TX');
    branch := BRANCHARRAY(100,101,102,200,201,202,300,301,302,400);
    status := STATUSARRAY('C', 'I', 'P');
    FOR i in 1..1000000 
    LOOP
        Insert into ACCOUNTS_LIST_PARTITIONED values (i, i+100, i+10,branch(dbms_random.value(1,10)),region(dbms_random.value(1,14)),status(dbms_random.value(1,3))); 
        If mod(i, 10000) = 0 then 
        Commit; 
        End if; 
    END LOOP; 
END;
/

--INTERVAL PARTITION DATA

Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (105,1,'Pending',54,to_date('17-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (44,2,'Pending',55,to_date('20-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (101,3,'Pending',55,to_date('03-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (1,4,'Pending',56,to_date('15-OCT-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (5,5,'Canceled',56,to_date('09-APR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (28,6,'Canceled',57,to_date('15-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (87,7,'Canceled',57,to_date('01-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (4,8,'Shipped',59,to_date('09-APR-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (41,9,'Shipped',59,to_date('11-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (82,44,'Shipped',60,to_date('03-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (102,45,'Shipped',61,to_date('20-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (26,46,'Shipped',62,to_date('16-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (43,47,'Shipped',62,to_date('02-MAY-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (53,48,'Shipped',62,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (81,49,'Shipped',62,to_date('13-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (83,16,'Shipped',62,to_date('02-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (93,17,'Shipped',62,to_date('27-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (94,1,'Shipped',62,to_date('27-OCT-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (79,2,'Shipped',64,to_date('14-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (80,3,'Shipped',64,to_date('13-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (2,4,'Shipped',null,to_date('26-APR-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (3,5,'Shipped',null,to_date('26-APR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (6,6,'Shipped',null,to_date('09-APR-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (7,7,'Shipped',null,to_date('15-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (8,8,'Shipped',null,to_date('14-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (9,9,'Shipped',null,to_date('14-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (10,44,'Pending',null,to_date('24-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (11,45,'Shipped',null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (12,46,'Shipped',null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (13,47,'Shipped',null,to_date('29-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (14,48,'Shipped',null,to_date('28-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (15,49,'Shipped',null,to_date('27-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (16,16,'Pending',null,to_date('27-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (17,17,'Shipped',null,to_date('27-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (18,18,'Shipped',null,to_date('16-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (19,19,'Shipped',null,to_date('27-MAY-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (20,20,'Shipped',null,to_date('27-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (21,21,'Pending',null,to_date('27-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (22,22,'Canceled',null,to_date('26-MAY-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (23,23,'Shipped',null,to_date('07-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (24,41,'Shipped',null,to_date('07-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (25,42,'Shipped',null,to_date('24-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (27,43,'Canceled',null,to_date('16-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (29,44,'Shipped',null,to_date('14-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (30,45,'Shipped',null,to_date('12-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (31,46,'Canceled',null,to_date('12-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (32,47,'Shipped',null,to_date('09-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (33,48,'Shipped',null,to_date('07-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (34,49,'Shipped',null,to_date('12-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (35,50,'Shipped',null,to_date('05-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (36,51,'Shipped',null,to_date('05-SEP-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (37,52,'Shipped',null,to_date('19-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (38,53,'Canceled',57,to_date('31-MAY-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (39,54,'Shipped',62,to_date('22-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (40,55,'Shipped',62,to_date('11-MAY-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (42,56,'Canceled',64,to_date('03-MAY-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (45,57,'Shipped',64,to_date('20-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (46,58,'Pending',62,to_date('20-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (47,59,'Canceled',62,to_date('10-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (48,60,'Canceled',64,to_date('10-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (49,61,'Shipped',55,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (50,62,'Pending',55,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (51,63,'Shipped',59,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (52,64,'Shipped',60,to_date('02-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (54,65,'Shipped',56,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (55,66,'Pending',59,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (56,67,'Canceled',55,to_date('29-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (57,68,'Shipped',57,to_date('24-AUG-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (58,69,'Shipped',57,to_date('24-AUG-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (59,70,'Shipped',59,to_date('29-JUN-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (60,1,'Shipped',62,to_date('30-JUN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (61,2,'Shipped',54,to_date('30-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (62,3,'Shipped',62,to_date('30-JUN-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (63,4,'Shipped',61,to_date('30-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (64,5,'Shipped',64,to_date('21-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (65,6,'Shipped',64,to_date('21-JUN-13','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (66,7,'Canceled',61,to_date('21-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (67,8,'Canceled',61,to_date('14-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (68,9,'Pending',null,to_date('13-JUN-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (69,44,'Canceled',54,to_date('17-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (70,45,'Canceled',61,to_date('21-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (71,46,'Shipped',54,to_date('21-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (72,47,'Shipped',64,to_date('17-FEB-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (73,48,'Shipped',null,to_date('17-FEB-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (74,49,'Shipped',64,to_date('10-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (75,16,'Shipped',null,to_date('10-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (76,17,'Shipped',55,to_date('10-FEB-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (77,1,'Shipped',60,to_date('02-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (78,2,'Pending',64,to_date('14-DEC-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (84,3,'Shipped',64,to_date('01-DEC-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (85,4,'Pending',55,to_date('01-DEC-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (86,5,'Pending',60,to_date('30-NOV-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (88,6,'Shipped',61,to_date('01-NOV-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (89,7,'Shipped',55,to_date('27-OCT-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (90,8,'Pending',55,to_date('28-OCT-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (91,9,'Pending',56,to_date('28-OCT-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (92,44,'Shipped',59,to_date('28-OCT-15','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (95,45,'Shipped',59,to_date('19-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (96,46,'Shipped',56,to_date('14-SEP-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (97,47,'Canceled',60,to_date('12-JUL-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (98,48,'Shipped',55,to_date('18-MAR-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (99,49,'Shipped',60,to_date('07-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (100,16,'Pending',54,to_date('05-JAN-17','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (103,17,'Pending',64,to_date('08-FEB-16','DD-MON-RR'));
Insert into ORDERS_INTERVAL_PARTITION (ORDER_ID,CUSTOMER_ID,STATUS,SALESMAN_ID,ORDER_DATE) values (104,18,'Shipped',60,to_date('01-FEB-17','DD-MON-RR'));


--HASH PARTITION DATA
DECLARE
    rand_date DATE;
    rand_price NUMBER;
    TYPE PRODARRAY IS VARRAY(20) OF NUMBER;
    product PRODARRAY;
BEGIN
    product := PRODARRAY(1,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20);
    FOR i in 1..2000000 
    LOOP
        SELECT TO_DATE(
              TRUNC(
                   DBMS_RANDOM.VALUE(TO_CHAR(DATE '2000-01-01','J')
                                    ,TO_CHAR(DATE '2022-09-30','J')
                                    )
                    ),'J'
               ) INTO rand_date FROM DUAL; 
        SELECT TRUNC(dbms_random.value(0.01, 9999.99),2) INTO rand_price FROM dual;
        Insert into sales_hash values (product(dbms_random.value(1,20)), rand_date, i+100, rand_price); 
        If mod(i, 20000) = 0 then 
        Commit; 
        End if; 
    END LOOP; 
END;
/

COMMIT;