#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)

EXPECTED_ROW_COUNT = {
	'trunc_test': 1,
 	'test_timezone': 1,
	'group':5,
	'check':5,
	'reserved_column':5,
	'mixed_case_table_name_test':6,
	'case_sensitive_columns':6,
	'c': 12,
	'c1': 2,
	'employees': 3
}

def migration_completed_checks(tgt):
	# Validation to check for matching row counts
	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]
	
	view_list = tgt.get_objects_of_type("VIEW", "public")
	print("view_list:", view_list)
	assert len(view_list) == 1

	functions = tgt.fetch_all_function_names("public")
	assert set(functions) == set(["trunc_date", "trunc_time_stamp", "insert_session_logs"])

if __name__ == "__main__":
	main()
