#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

psql_import_file ${SOURCE_DB_NAME} rec_employee_hierarchy/0.sql

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM emps;"
