#!/usr/bin/env bash

# script to tar zip a directory after every commit 
PARENT_DIR="yb-voyager/src/srcdb/data/gather-assessment-data/"
DIR_NAME="gather-assessment-data"
OUTPUT_TAR="yb-voyager/src/srcdb/data/gather-assessment-data.tar.gz"
REPO_ROOT=$(git rev-parse --show-toplevel)

pushd "$REPO_ROOT/$PARENT_DIR/.." > /dev/null

tar -czf "$REPO_ROOT/$OUTPUT_TAR" $DIR_NAME

popd > /dev/null

echo "created tarball: ${OUTPUT_TAR}"

if [ ! -f "$OUTPUT_TAR" ]; then
    echo "Error: $OUTPUT_TAR File does not exist."
    exit 1
fi

# Check if the file is not tracked or is tracked but not staged
if ! git ls-files --error-unmatch "$OUTPUT_TAR" &> /dev/null || ! git diff --quiet "$OUTPUT_TAR"; then
    git add "$OUTPUT_TAR"
    git commit -m "Added or updated gather-assessment-data tar.gz"
    echo "$OUTPUT_TAR file added and committed."
fi