#!/usr/bin/env bash

# script to tar zip a directory after every commit 
PARENT_DIR="yb-voyager/src/srcdb/data/gather-assessment-data/"
DIR_NAME="gather-assessment-data"
OUTPUT_TAR="yb-voyager/src/srcdb/data/gather-assessment-data.tar.gz"
REPO_ROOT=$(git rev-parse --show-toplevel)

pushd "$REPO_ROOT/$PARENT_DIR/.." > /dev/null

tar -czf "$REPO_ROOT/$OUTPUT_TAR" $DIR_NAME

popd > /dev/null

echo "created tarball: ${OUTPUT_TAR}"