export SOURCE_DB_TYPE="oracle"
export SOURCE_DB_SCHEMA=${SOURCE_DB_SCHEMA:-"TEST_SCHEMA"}
export TARGET_DB_NAME=${TARGET_DB_NAME:-"trunc_function_test"}
export SOURCE_DB_USER_SCHEMA_OWNER=${SOURCE_DB_USER_SCHEMA_OWNER:-"TEST_SCHEMA"}
export SOURCE_DB_USER_SCHEMA_OWNER_PASSWORD=${SOURCE_DB_USER_SCHEMA_OWNER_PASSWORD:-"password"}
export SOURCE_DB_USER_SYS=${SOURCE_DB_USER_SYS:-"SYS"}
export SOURCE_DB_USER_SYS_PASSWORD=${SOURCE_DB_USER_SYS_PASSWORD:-"password"}
