-- setting variables for current session
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SEQUENCE public."Case_Sensitive_Columns_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Case_Sensitive_Columns_id_seq" OWNED BY public."Case_Sensitive_Columns".id;


CREATE SEQUENCE public."Mixed_Case_Table_Name_Test_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Mixed_Case_Table_Name_Test_id_seq" OWNED BY public."Mixed_Case_Table_Name_Test".id;


CREATE SEQUENCE public."Recipients_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Recipients_id_seq" OWNED BY public."Recipients".id;


CREATE SEQUENCE public."WITH_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WITH_id_seq" OWNED BY public."WITH".id;


CREATE SEQUENCE public.bigint_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bigint_multirange_table_id_seq OWNED BY public.bigint_multirange_table.id;


CREATE SEQUENCE public.date_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.date_multirange_table_id_seq OWNED BY public.date_multirange_table.id;


CREATE SEQUENCE public.employees2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employees2_id_seq OWNED BY public.employees2.id;


CREATE SEQUENCE public.employees_employee_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employees_employee_id_seq OWNED BY public.employees.employee_id;


CREATE SEQUENCE public.employeesforview_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employeesforview_id_seq OWNED BY public.employeesforview.id;


CREATE SEQUENCE public.ext_test_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ext_test_id_seq OWNED BY public.ext_test.id;


CREATE SEQUENCE public.int_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.int_multirange_table_id_seq OWNED BY public.int_multirange_table.id;


CREATE SEQUENCE public.mixed_data_types_table1_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mixed_data_types_table1_id_seq OWNED BY public.mixed_data_types_table1.id;


CREATE SEQUENCE public.mixed_data_types_table2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mixed_data_types_table2_id_seq OWNED BY public.mixed_data_types_table2.id;


CREATE SEQUENCE public.numeric_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.numeric_multirange_table_id_seq OWNED BY public.numeric_multirange_table.id;


CREATE SEQUENCE public.orders2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.orders2_id_seq OWNED BY public.orders2.id;


CREATE SEQUENCE public.ordersentry_order_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ordersentry_order_id_seq OWNED BY public.ordersentry.order_id;


CREATE SEQUENCE public.parent_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.parent_table_id_seq OWNED BY public.parent_table.id;


CREATE SEQUENCE public.timestamp_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.timestamp_multirange_table_id_seq OWNED BY public.timestamp_multirange_table.id;


CREATE SEQUENCE public.timestamptz_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.timestamptz_multirange_table_id_seq OWNED BY public.timestamptz_multirange_table.id;


ALTER TABLE public.ts_query_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ts_query_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE SEQUENCE public.with_example1_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.with_example1_id_seq OWNED BY public.with_example1.id;


CREATE SEQUENCE public.with_example2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.with_example2_id_seq OWNED BY public.with_example2.id;


CREATE SEQUENCE schema2."Case_Sensitive_Columns_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2."Case_Sensitive_Columns_id_seq" OWNED BY schema2."Case_Sensitive_Columns".id;


CREATE SEQUENCE schema2."Mixed_Case_Table_Name_Test_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2."Mixed_Case_Table_Name_Test_id_seq" OWNED BY schema2."Mixed_Case_Table_Name_Test".id;


CREATE SEQUENCE schema2."Recipients_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2."Recipients_id_seq" OWNED BY schema2."Recipients".id;


CREATE SEQUENCE schema2."WITH_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2."WITH_id_seq" OWNED BY schema2."WITH".id;


CREATE SEQUENCE schema2.bigint_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.bigint_multirange_table_id_seq OWNED BY schema2.bigint_multirange_table.id;


CREATE SEQUENCE schema2.date_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.date_multirange_table_id_seq OWNED BY schema2.date_multirange_table.id;


CREATE SEQUENCE schema2.employees2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.employees2_id_seq OWNED BY schema2.employees2.id;


CREATE SEQUENCE schema2.employeesforview_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.employeesforview_id_seq OWNED BY schema2.employeesforview.id;


CREATE SEQUENCE schema2.ext_test_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.ext_test_id_seq OWNED BY schema2.ext_test.id;


CREATE SEQUENCE schema2.int_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.int_multirange_table_id_seq OWNED BY schema2.int_multirange_table.id;


CREATE SEQUENCE schema2.mixed_data_types_table1_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.mixed_data_types_table1_id_seq OWNED BY schema2.mixed_data_types_table1.id;


CREATE SEQUENCE schema2.mixed_data_types_table2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.mixed_data_types_table2_id_seq OWNED BY schema2.mixed_data_types_table2.id;


CREATE SEQUENCE schema2.numeric_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.numeric_multirange_table_id_seq OWNED BY schema2.numeric_multirange_table.id;


CREATE SEQUENCE schema2.orders2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.orders2_id_seq OWNED BY schema2.orders2.id;


CREATE SEQUENCE schema2.parent_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.parent_table_id_seq OWNED BY schema2.parent_table.id;


CREATE SEQUENCE schema2.timestamp_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.timestamp_multirange_table_id_seq OWNED BY schema2.timestamp_multirange_table.id;


CREATE SEQUENCE schema2.timestamptz_multirange_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.timestamptz_multirange_table_id_seq OWNED BY schema2.timestamptz_multirange_table.id;


CREATE SEQUENCE schema2.with_example1_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.with_example1_id_seq OWNED BY schema2.with_example1.id;


CREATE SEQUENCE schema2.with_example2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE schema2.with_example2_id_seq OWNED BY schema2.with_example2.id;


CREATE SEQUENCE test_views.view_table1_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE test_views.view_table1_id_seq OWNED BY test_views.view_table1.id;


CREATE SEQUENCE test_views.view_table2_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE test_views.view_table2_id_seq OWNED BY test_views.view_table2.id;


