#!/usr/bin/env bash
source migtests/scripts/yugabytedb/env.sh
source migtests/scripts/functions.sh

cmd="CREATE USER ${TARGET_DB_USER} SUPERUSER PASSWORD '${TARGET_DB_PASSWORD}';"
run_ysql "yugabyte" "${cmd}"