export TARGET_DB_HOST=${TARGET_DB_HOST:-"127.0.0.1"}
export TARGET_DB_PORT=${TARGET_DB_PORT:-5433}
export TARGET_DB_USER=${TARGET_DB_USER:-"yugabyte"}
export TARGET_DB_PASSWORD=${TARGET_DB_PASSWORD:-''}
export TARGET_DB_NAME=${TARGET_DB_NAME:-${SOURCE_DB_NAME}}
