#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh


echo "Initialising source database."

run_mysql ${SOURCE_DB_NAME} "SOURCE mysql_constraints_automation.sql;"


echo "Check source database."
run_mysql ${SOURCE_DB_NAME} "SELECT count(*) FROM not_null_check;"
