#!/usr/bin/env bash

set -e
set -x

pushd ${EXPORT_DIR}/schema

#Deleting views as the views are causing the import schema failures
echo "Delete all views."
echo "" > views/view.sql

#Deleting the following line as the contraint creation blocks the import schema
sed -i '/ALTER TABLE products ADD CONSTRAINT products_json_c CHECK ( (CASE WHEN product_details::json IS NULL THEN true ELSE true END));/d' tables/table.sql

#Deleting the following line from table.sql as the foreign key creation with ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE causes import schema failures.
sed -i '/ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE/d' tables/table.sql

