#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Assigning permissions to the validate files"
chmod +x ${TEST_DIR}/validate

echo "Deleting existing data in target database"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TESTS_DIR}/oracle/utils/delete_full_schema

echo "Initialising source database & inserting data"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ssl_schema_data
