#!/usr/bin/env python3

import oracle

def main():
    oracle.run_checks(migration_completed_checks)
    
EXPECTED_ROW_COUNT = {
    'accounts': 100000
}

def migration_completed_checks(tgt):
    # Validation to check for matching row counts
    got_row_count = tgt.get_row_count('accounts', 'TEST_SCHEMA')
    
    assert EXPECTED_ROW_COUNT['accounts'] == got_row_count

if __name__ == "__main__":
	main()
