#!/bin/sh

argv=( "$@" )

if ! which docker > /dev/null; then
   echo "Could not find docker! Please install docker before proceeeding."
   exit 1
fi

i=0
while [ $i -lt $# ]
do
    if [[ ${argv[${i}]} == "--export-dir" || ${argv[${i}]} == "-e" ]]
    then
        j=$(( $i + 1))
        vol="-v ${argv[$j]}:/export-dir"
        argv[$j]='/export-dir'
    fi
    i=$(( $i + 1))
done

dockerCmd="docker run ${vol} -it --network=host --rm --privileged --platform=linux/amd64 yugabytedb/yb-voyager yb-voyager ${argv[*]}"

# echo $dockerCmd

$dockerCmd
