#!/bin/bash

argv=( "$@" )

if ! which docker > /dev/null; then
	echo "Could not find docker! Please install docker before proceeeding."
	exit 1
fi

if [[ $OSTYPE == 'darwin'* ]]
then
	platform="--platform=linux/amd64"
fi

i=0
exported_vars=""

while [ $i -lt $# ]
do
    if [[ ${argv[${i}]} == "--export-dir" || ${argv[${i}]} == "-e" ]]
	then
        j=$(( $i + 1))
		export_dir=${argv[${j}]}

		# If the OS is macOS
		if [[ $OSTYPE == 'darwin'* ]]; then

			# Delete the old volume and create a new one it its place attached to the user's export-dir
			docker volume rm voyager-export-dir
			docker volume create --driver local --opt type=none --opt device="${export_dir}" --opt o=bind voyager-export-dir 
		
			export_vol="-v voyager-export-dir:/export-dir"
		else
			export_vol="-v ${export_dir}:/export-dir"
		fi
		argv[$j]='/export-dir'
    fi
	
	if [[ ${argv[${i}]} == "--data-dir" ]]
	then 
		j=$(( $i + 1))
		data_dir=${argv[${j}]}

		# If the data-dir is an S3 bucket
		if [[ $data_dir == 's3://'* ]]
		then 
			# Check if aws directory exists
			if [ -d "${HOME}/.aws" ]; then
				if [[ $OSTYPE == 'darwin'* ]]; then
					# Delete the old volume and create a new one it its place attached to the user's data-dir
					docker volume rm aws-dir
					docker volume create --driver local --opt type=none --opt device="${HOME}/.aws" --opt o=bind aws-dir
			
					aws_vol="-v aws-dir:/root/.aws"
				else
					aws_vol="-v ${HOME}/.aws:/root/.aws"
				fi
			fi
			# Capture exported variables for aws
			for var in $(env | grep -E '^AWS_'); do
				exported_vars="${exported_vars} -e $var"
			done
		else 
			# If the data-dir is not an S3 bucket
			# If the OS is macOS
			if [[ $OSTYPE == 'darwin'* ]]; then

				# Delete the old volume and create a new one it its place attached to the user's data-dir
				docker volume rm voyager-data-dir
				docker volume create --driver local --opt type=none --opt device="${data_dir}" --opt o=bind voyager-data-dir 
		
				data_vol="${vol} -v voyager-data-dir:/data-dir"
			else
				data_vol="${vol} -v ${data_dir}:/data-dir"
			fi
			argv[$j]='/data-dir'
		fi
	fi	

    i=$(( $i + 1))
done

dockerCmd="docker run ${exported_vars} ${export_vol} ${data_vol} ${aws_vol} -it --network=host --rm --privileged ${platform} yugabytedb/yb-voyager yb-voyager ${argv[*]}"

echo $dockerCmd

$dockerCmd
