#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Downloading dvdrental sample database."
if [ ! -e dvdrental.tar ]
then
  wget -q https://www.postgresqltutorial.com/wp-content/uploads/2019/05/dvdrental.zip
  unzip dvdrental.zip
fi

echo "Initialising source database."
run_pg_restore ${SOURCE_DB_NAME} dvdrental.tar

echo "Adding custom collation."
run_psql ${SOURCE_DB_NAME} "CREATE COLLATION fulah (provider= icu, locale='ff-x-icu');"

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM payment"
