#!/usr/bin/env python3

import yb

def main():
	yb.run_checks({
		"MIGRATION_COMPLETED": migration_completed_checks,
	})

EXPECTED_ROW_COUNT = {
	'numeric_types_number': 4,
	'numeric_types_float': 5,
	'numeric_types_binary_float': 5,
	'numeric_types_binary_double': 5,
	'numeric_types': 8,
	'date_time_types': 10,
	'interval_types': 4,
	'CHAR_TYPES': 6,
	'LONG_TYPE': 3,
	'RAW_TYPE': 6
}

def migration_completed_checks(tgt):
	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

if __name__ == "__main__":
	main()
