#!/usr/bin/env python3

import yb

def main():
    yb.run_checks(text_length_checks)

#===============================================================

EXPECTED_TEXT_LENGTHS = {
    1: 13,
    2: 13,
    3: 14,
    4: 14,
    5: 14,
    6: 16,
    7: 12,
    8: 23,
    9: 23,
    10: 24,
    11: 24,
    12: 24,
    13: 26,
    14: 23,
    15: 22,
    16: 23,
    17: 23,
    18: 23,
    19: 25,
    20: 22,
    21: 22,
    22: 23,
    23: 23,
    24: 23,
    25: 25,
    26: 35,
    27: 35,
    28: 36,
    29: 36,
    30: 36,
    31: 38,
}

def text_length_checks(tgt):
    for i in range(1, 32):
        text_len = tgt.get_text_length("id", i, "value", "foo", "public")
        expected_len = EXPECTED_TEXT_LENGTHS[i]
        print ("Text length for column %d: %d" % (i, text_len))
        assert text_len == expected_len

if __name__ == "__main__":
    main()
