#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh


echo "Initialising source database."

run_mysql ${SOURCE_DB_NAME} "SOURCE schema.sql;"


echo "Check source database."
run_mysql ${SOURCE_DB_NAME} "SELECT count(*) FROM \`order\`;"
run_mysql ${SOURCE_DB_NAME} "SELECT count(*) FROM foo;"
