#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_ROW_COUNT = {
	'order': 5,
	'user': 5,
	'group': 5,
	'check': 5,
	'reserved_column': 5,
	'mixed_case_table_name_test':6,
	'case_sensitive_columns':6
}

def migration_completed_checks(tgt):
	table_list = tgt.get_table_names("misc_tests")
	print("table_list:", table_list)
	assert len(table_list) == 7

	got_row_count = tgt.row_count_of_all_tables("misc_tests")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}, expected row_count: {row_count}")
		assert row_count == got_row_count[table_name]


if __name__ == "__main__":
	main()