#!/usr/bin/env bash

set -e
set -x

pushd ${EXPORT_DIR}/schema

# Changing the datatype of product_details from bytea to TEXT as the check constraint doesn't work with bytea

sed -i -E 's/(product_details[[:space:]]+)bytea/\1TEXT/' tables/table.sql

# Removing the product_reviews view creation as the view creation blocks the import schema
sed -i -E '/CREATE OR REPLACE VIEW product_reviews/,/;/d' views/view.sql

# Changing numeric(38) to bigint as FKeys fail due to datatype mismatch

sed -i '/CREATE TABLE inventory/,/)/ s/product_id numeric(38)/product_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE inventory/,/)/ s/store_id numeric(38)/store_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE orders/,/)/ s/customer_id numeric(38)/customer_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE order_items/,/)/ s/order_id numeric(38)/order_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE order_items/,/)/ s/product_id numeric(38)/product_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE order_items/,/)/ s/shipment_id numeric(38)/shipment_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE shipments/,/)/ s/customer_id numeric(38)/customer_id BIGINT/' tables/table.sql
sed -i '/CREATE TABLE shipments/,/)/ s/store_id numeric(38)/store_id BIGINT/' tables/table.sql

