#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh


echo "Creating ${SOURCE_DB_NAME} database on source"
run_mysql mysql "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_mysql mysql "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Initialising source database."

run_mysql ${SOURCE_DB_NAME} "SOURCE mysql_data_types_automation.sql;"

# TODO: Support GEOMETRIC types.
#run_mysql ${SOURCE_DB_NAME} "ALTER TABLE address DROP COLUMN location;"

echo "Check source database."
run_mysql ${SOURCE_DB_NAME} "SELECT count(*) FROM int_types;"
