#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh


echo "Initialising source database."

run_mysql ${SOURCE_DB_NAME} "SOURCE mysql_data_types_automation.sql;"

# TODO: Support GEOMETRIC types.
#run_mysql ${SOURCE_DB_NAME} "ALTER TABLE address DROP COLUMN location;"

echo "Check source database."
run_mysql ${SOURCE_DB_NAME} "SELECT count(*) FROM int_types;"
