#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

run_psql "${SOURCE_DB_NAME}" "\i pg_assessment_report_uqc.sql"

run_psql "${SOURCE_DB_NAME}" "\i unsupported_query_constructs.sql"

echo "End of init-db script"