#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i pg_views_and_rules_automation.sql;"

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM test_views.view_table1;"
