#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Deleting existing data in target database"
run_sqlplus ${SOURCE_DB_NAME} delete_full_schema

echo "Initialising source database"
run_sqlplus ${SOURCE_DB_NAME} index.sql

echo "Populating data in source database"
run_sqlplus ${SOURCE_DB_NAME} index_data.sql

echo "Checking the row counts once data is created on the source DB"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM members;"