#!/usr/bin/env bash
#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database"
run_sqlplus ${SOURCE_DB_NAME} partition_schema

echo "Populating data in source database"
run_sqlplus ${SOURCE_DB_NAME} partition_data

echo "Checking the row counts once data is created on the source DB"
run_sqlplus ${SOURCE_DB_NAME} "SELECT count(*) FROM ORDER_ITEMS_RANGE_PARTITIONED;
                               SELECT count(*) FROM ACCOUNTS_LIST_PARTITIONED;
                               SELECT count(*) FROM ORDERS_INTERVAL_PARTITION;
                               SELECT count(*) FROM sales_hash;"