#!/usr/bin/env bash

set -e
set -x

pushd ${EXPORT_DIR}

if [ -f debezium.log ]; then
    echo "Printing debezium.log file....."
    cat debezium.log
else
    echo "debezium.log file not found!!"
fi

echo "Printing export_status.json file....."
if [ -f data/export_status.json ]; then
    cat data/export_status.json
else
    echo "data/export_status.json file not found!!"
fi
