#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Downloading sakila sample database."
if [ ! -e sakila-db.zip ]
then
  wget -q https://downloads.mysql.com/docs/sakila-db.zip
  unzip sakila-db.zip
fi

echo "Creating ${SOURCE_DB_NAME} database on source"
run_mysql mysql "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_mysql mysql "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Initialising source database."
run_mysql ${SOURCE_DB_NAME} "SOURCE sakila-db/sakila-schema.sql;"
run_mysql ${SOURCE_DB_NAME} "SOURCE sakila-db/sakila-data.sql;"
# TODO: Support GEOMETRIC types.
run_mysql ${SOURCE_DB_NAME} "ALTER TABLE address DROP COLUMN location;"

echo "Check source database."
run_mysql ${SOURCE_DB_NAME} "SELECT count(*) FROM payment;"
