#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_ROW_COUNT = {
	'desc_index_test': 3,
	'inunique_index_test': 3,
	'mult_index_test': 3,
	'outunique_index_test': 4,
	'primary_index_test': 3,
	'single_index_test': 4
}


def migration_completed_checks(tgt):
	got_row_count = tgt.row_count_of_all_tables("\"TEST_MYSQL_INDEXES\"")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]


if __name__ == "__main__":
	main()