#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

set -e
ARGS_MACOS=$*
ARGS_LINUX=$@

trap on_exit EXIT
LOG_FILE=/tmp/install-yb-voyager-debezium.log
YUM="sudo yum install -y -q"

# Remember to update the S3 repo with the correct version of pre-biult debezium-server, if any change in these values.
DEBEZIUM_TARBALL_VERSION="latest"


on_exit() {
	rc=$?
	set +x
	if [ $rc -eq 0 ]
	then
		echo "Done!"
	else
		echo "Script failed. Check log file ${LOG_FILE} ."
		if [[ ${ON_INSTALLER_ERROR_OUTPUT_LOG:-N} = "Y" ]]
		then
			sudo cat ${LOG_FILE}
		fi
	fi
}

# Output a line to both STDOUT and STDERR. Use this function to output something to
# user as well as in the log file.
output() {
	set +x
	echo $1
	>&2 echo $1
	set -x
}

#=============================================================================
# MAIN
#=============================================================================
main() {
	set -x

	os=$(uname -s)
	case ${os} in
		"Darwin")
			get_passed_options darwin
			install_core_utils_macos
			;;
		"Linux")
			get_passed_options linux
			install_core_utils_linux
			;;
		*)
			echo "ERROR: unsupported os ${os}"
			exit 1
			;;
	esac

	sudo mkdir -p /opt/yb-voyager

	check_java
	install_debezium_server
	output "Installation complete."
}

#=============================================================================
# COMMON
#=============================================================================

get_passed_options() {
	if [ "$1" == "linux" ]
	then
		OPTS=$(getopt -o "l", --long latest --name 'install-yb-voyager-debezium' -- $ARGS_LINUX)
	else
		OPTS=$(getopt  l  $ARGS_MACOS)
	fi

	eval set -- "$OPTS"

	while true; do
		case "$1" in
			-l | --latest ) 
				DEBEZIUM_TARBALL_VERSION="latest"
				shift
				;;
			* ) 
				break 
				;;
		esac
	done
}

# https://stackoverflow.com/a/4025065
# 0 if equal, 1 if $1 > $2, 2 if $2 > $1
vercomp () {
    if [[ $1 == $2 ]]
    then
        echo 0; return;
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            echo 1; return;
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            echo 2; return;
        fi
    done
    echo 0; return;
}

# usage: version_satisfied <minimum_version_required> <actual_version>
version_satisfied() {
    res=$(vercomp $1 $2)
    case $res in
        0) echo 1; return;;
        1) echo 0; return;;
        2) echo 1; return;;
    esac
}

check_binutils_version() {
	output "Checking binutils version."
	min_required_version='2.25'

	# Example output of "ld -v" on CentOS/RHEL:
	# GNU ld version 2.30-113.el8
	# Example output of "ld -v" on Ubuntu:
	# GNU ld (GNU Binutils for Ubuntu) 2.38
	version=$(ld -v | awk '{print $NF}' | awk -F '-' '{print $1}')

	version_ok=$(version_satisfied "$min_required_version" "$version")
	if [[ $version_ok -eq 0 ]]
	then
		echo "ERROR: unsupported binutils version ${version}. Update to binutils version > ${min_required_version} ."
		exit 1
	fi
}

centos_check_base_repo_enabled() {

	output "Checking if base repo is enabled."

	if [[ -z "$(yum repolist enabled | grep base)" ]]
	then 
		echo "ERROR: base repo is not enabled. Enable the repo and retry."
		exit 1
	fi
}

install_core_utils_linux() {
    # Linux
	dist=$(cat /etc/os-release | grep -w NAME | awk -F'=' '{print $2}' | tr -d '"')
	case ${dist} in
		"CentOS Linux")
			install_core_utils_centos
			;;
		"AlmaLinux")
			install_core_utils_centos
			;;
		"Red Hat Enterprise Linux")
			install_core_utils_centos
			;;
		"Red Hat Enterprise Linux Server")
			install_core_utils_centos
			;;
		"Ubuntu")
			install_core_utils_ubuntu
			;;
		*)
			echo "ERROR: unsupported linux distribution: ${dist}"
			exit 1
			;;
	esac
}

#=============================================================================
# CENTOS
#=============================================================================

install_core_utils_centos() {
	check_binutils_version
	centos_check_base_repo_enabled
	$YUM which wget git gcc 1>&2
}

#=============================================================================
# UBUNTU
#=============================================================================

install_core_utils_ubuntu() {
	check_binutils_version
	sudo apt update 1>&2
	sudo apt-get -y install wget 1>&2
}

#=============================================================================
# MacOS
#=============================================================================

install_core_utils_macos() {
	macos_install_brew
	brew install wget 1>&2
}

macos_install_brew() {
	which brew > /dev/null 2>&1
	if [ $? -eq 0 ]
	then
		output "brew is already installed."
	else
		output "Installing brew."
		set +x  # Do not dump the brew install.sh into the log.
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		set -x
	fi
}

#=============================================================================
# Debezium
#=============================================================================

check_java() {
		if [ -z "$JAVA_HOME" ]; then
			JAVA_BINARY="java"
		else
			JAVA_BINARY="$JAVA_HOME/bin/java"
		fi

        MIN_REQUIRED_MAJOR_VERSION='11'
		JAVA_MAJOR_VER=$(${JAVA_BINARY} -version 2>&1 | awk -F '"' '/version/ {print $2}' | awk -F. '{print $1}')
		
        if ([ -n "$JAVA_MAJOR_VER" ] && (( 10#${JAVA_MAJOR_VER} >= 10#${MIN_REQUIRED_MAJOR_VERSION} )) ) #integer compare of versions.
        then
        	output "Found sufficient java version = ${JAVA_MAJOR_VER}"
        else
        	output "ERROR: Java not found or insuffiencient version ${JAVA_MAJOR_VER}. Please install java>=${MIN_REQUIRED_MAJOR_VERSION}"
			exit 1;
        fi
}

install_debezium_server() {
	output "Installing debezium"
	debezium_server_filename="debezium-server-${DEBEZIUM_TARBALL_VERSION}.tar.gz"
	# download
	wget -nv "https://github.com/yugabyte/debezium/releases/download/voyager-debezium/${debezium_server_filename}"
	# move to /opt/yb-voyager/debezium-server
	sudo tar -xzf ${debezium_server_filename} -C /opt/yb-voyager 1>&2
	# cleanup
	rm ${debezium_server_filename}
}

main 2>> $LOG_FILE
{ set +x; } 2> /dev/null
