#!/usr/bin/env bash

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

set -e
trap on_exit EXIT
LOG_FILE=/tmp/install-yb-voyager-debezium.log
YUM="sudo yum install -y -q"

DEBEZIUM_LOCAL_VERSION="2.3.3"
DEBEZIUM_LOCAL_VERSION_1X="1.9.5"
DEBEZIUM_LOCAL_REF=${DEBEZIUM_LOCAL_REF:-"3a8a497a8403794d69ce2f781989ad12c4060131"}
DEBEZIUM_LOCAL_SERVER_REF=${DEBEZIUM_LOCAL_SERVER_REF:-"c4cad64f6d1869bcd15531c8f9cef98c651f86cc"}
DEBEZIUM_LOCAL_REF_1X=${DEBEZIUM_LOCAL_REF_1X:-"78ff67c054bec08bcad060968b24bfc9ba8b2112"}
DEBEZIUM_LOCAL_INSTALLATION_DESTINATION=${DEBEZIUM_LOCAL_INSTALLATION_DESTINATION:-"/opt/yb-voyager"}




on_exit() {
	rc=$?
	set +x
	if [ $rc -eq 0 ]
	then
		echo "Done!"
	else
		echo "Script failed. Check log file ${LOG_FILE} ."
		if [[ ${ON_INSTALLER_ERROR_OUTPUT_LOG:-N} = "Y" ]]
		then
			sudo cat ${LOG_FILE}
		fi
	fi
}

# Output a line to both STDOUT and STDERR. Use this function to output something to
# user as well as in the log file.
output() {
	set +x
	echo "$@"
	>&2 echo "$@"
	set -x
}

#=============================================================================
# MAIN
#=============================================================================
main() {
	set -x

	os=$(uname -s)
	case ${os} in
		"Darwin")
			install_core_utils_macos
			;;
		"Linux")
			install_core_utils_linux
			;;
		*)
			echo "ERROR: unsupported os ${os}"
			exit 1
			;;
	esac

	sudo mkdir -p /opt/yb-voyager

	check_java
	check_install_maven
	clean_debezium
	install_debezium ${DEBEZIUM_LOCAL_REF}
	install_debezium_server ${DEBEZIUM_LOCAL_SERVER_REF}
	install_debezium_server_voyager_plugin "2x"

	install_debezium ${DEBEZIUM_LOCAL_REF_1X}
	install_debezium_server_voyager_plugin "1x"
	install_yb_client
	package_debezium_server
	output "Installation complete."
}

#=============================================================================
# COMMON
#=============================================================================

# https://stackoverflow.com/a/4025065
# 0 if equal, 1 if $1 > $2, 2 if $2 > $1
vercomp () {
    if [[ $1 == $2 ]]
    then
        echo 0; return;
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            echo 1; return;
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            echo 2; return;
        fi
    done
    echo 0; return;
}

# usage: version_satisfied <minimum_version_required> <actual_version>
version_satisfied() {
    res=$(vercomp $1 $2)
    case $res in
        0) echo 1; return;;
        1) echo 0; return;;
        2) echo 1; return;;
    esac
}

check_binutils_version() {
	output "Checking binutils version."
	min_required_version='2.25'

	# Example output of "ld -v" on CentOS/RHEL:
	# GNU ld version 2.30-113.el8
	# Example output of "ld -v" on Ubuntu:
	# GNU ld (GNU Binutils for Ubuntu) 2.38
	version=$(ld -v | awk '{print $NF}' | awk -F '-' '{print $1}')

	version_ok=$(version_satisfied "$min_required_version" "$version")
	if [[ $version_ok -eq 0 ]]
	then
		echo "ERROR: unsupported binutils version ${version}. Update to binutils version > ${min_required_version} ."
		exit 1
	fi
}

centos_check_base_repo_enabled() {

	output "Checking if base repo is enabled."

	if [[ -z "$(yum repolist enabled | grep base)" ]]
	then 
		echo "ERROR: base repo is not enabled. Enable the repo and retry."
		exit 1
	fi
}

install_core_utils_linux() {
    # Linux
	dist=$(cat /etc/os-release | grep -w NAME | awk -F'=' '{print $2}' | tr -d '"')
	case ${dist} in
		"CentOS Linux")
			install_core_utils_centos
			;;
		"AlmaLinux")
			install_core_utils_centos
			;;
		"Red Hat Enterprise Linux")
			install_core_utils_centos
			;;
		"Red Hat Enterprise Linux Server")
			install_core_utils_centos
			;;
		"Ubuntu")
			install_core_utils_ubuntu
			;;
		*)
			echo "ERROR: unsupported linux distribution: ${dist}"
			exit 1
			;;
	esac
}

#=============================================================================
# CENTOS
#=============================================================================

install_core_utils_centos() {
	check_binutils_version
	centos_check_base_repo_enabled
	$YUM which wget git gcc make 1>&2
}

#=============================================================================
# UBUNTU
#=============================================================================

install_core_utils_ubuntu() {
	check_binutils_version
	sudo apt update 1>&2
	sudo apt-get -y install wget make 1>&2
}

#=============================================================================
# MacOS
#=============================================================================

install_core_utils_macos() {
	macos_install_brew
	brew install wget 1>&2
}

macos_install_brew() {
	which brew > /dev/null 2>&1
	if [ $? -eq 0 ]
	then
		output "brew is already installed."
	else
		output "Installing brew."
		set +x  # Do not dump the brew install.sh into the log.
		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
		set -x
	fi
}

#=============================================================================
# Debezium
#=============================================================================

check_java() {
		if [ -z "$JAVA_HOME" ]; then
			JAVAC_BINARY="javac"
		else
			JAVAC_BINARY="$JAVA_HOME/bin/javac"
		fi
        MIN_REQUIRED_MAJOR_VERSION='17'
		JDK_MAJOR_VER=$(${JAVAC_BINARY} -version | awk '{print $2}' | cut -d '.' -f1)

        if ([ -n "$JDK_MAJOR_VER" ] && (( 10#${JDK_MAJOR_VER} >= 10#${MIN_REQUIRED_MAJOR_VERSION} )) ) #integer compare of versions.
        then
        	output "Found sufficient JDK version = ${JDK_MAJOR_VER}"
        else
        	output "ERROR: JDK not found or insuffiencient version ${JDK_MAJOR_VER}. Please install JDK>=${MIN_REQUIRED_MAJOR_VERSION}"
			exit 1;
        fi
}

check_install_maven() {
	MIN_REQUIRED_MAVEN_VERSION='3.8.4'
	MAVEN_VER=$(mvn -version 2>&1 | grep "Apache Maven" | awk '{print $3}')
    version_ok=$(version_satisfied "$MIN_REQUIRED_MAVEN_VERSION" "$MAVEN_VER")
	if [[ $version_ok -eq 1 ]]
	# if ([ -n "$MAVEN_VER" ] && (( 10#${MAVEN_VER} >= 10#${MIN_REQUIRED_MAVEN_VERSION} )) )
        then 
                output "Found sufficient maven version = ${MAVEN_VER}"
        else
                output "Maven not found or not sufficient. Installing..."
                install_maven
        fi
}

install_maven() {
	# if dir already present, assuming it was installed in a previous run
	if [ ! -d "/opt/yb-voyager/yb-debezium-maven-3.8.4" ]
	then
		MAVEN_URL="https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz"
		wget -nv ${MAVEN_URL} -O apache-maven-3.8.4-bin.tar.gz 1>&2
		tar -xzvf apache-maven-3.8.4-bin.tar.gz 1>&2
		sudo mv apache-maven-3.8.4 yb-debezium-maven-3.8.4
		sudo mv yb-debezium-maven-3.8.4 /opt/yb-voyager
		rm apache-maven-3.8.4-bin.tar.gz
	fi
	export PATH=/opt/yb-voyager/yb-debezium-maven-3.8.4/bin:$PATH
}

clean_debezium(){
	pushd `git rev-parse --show-toplevel` > /dev/null
	rm -rf debezium-server-voyager/target
	popd > /dev/null
}

install_debezium() {
	output "Installing debezium..." "$1"
	# download
	wget -nv "https://github.com/yugabyte/debezium/archive/$1.tar.gz" -O debezium.tar.gz 1>&2
	tar -xzvf debezium.tar.gz 1>&2
	# build
	cd "debezium-$1"
	mvn -ntp clean install -Dquick 1>&2

	# cleanup
	cd ..
	rm -r "debezium-$1"
	rm debezium.tar.gz
}

install_debezium_server() {
	output "Installing debezium-server..." "$1"
	# download
	wget -nv "https://github.com/yugabyte/debezium-server/archive/$1.tar.gz" -O debezium-server.tar.gz 1>&2
	tar -xzvf debezium-server.tar.gz 1>&2
	# build
	cd "debezium-server-$1"
	mvn -ntp clean install -Dquick 1>&2

	# cleanup
	cd ..
	rm -r "debezium-server-$1"
	rm debezium-server.tar.gz
}

install_debezium_server_voyager_plugin() {
	output "Installing debezium-server voyager plugin..." "$1"
	if [ "$1" = "2x" ] 
	then
		pom="pom.xml"
		version=${DEBEZIUM_LOCAL_VERSION}
	else
		pom="195pom.xml"
		version=${DEBEZIUM_LOCAL_VERSION_1X}
	fi
	# build
	pushd `git rev-parse --show-toplevel` > /dev/null
	cd debezium-server-voyager/debezium-server-voyagerexporter
	mvn -ntp clean install -Dquick -f ${pom} 1>&2
	cd ../debezium-server-voyager-dist
	mvn -ntp clean install -Dquick -f ${pom} 1>&2
	mvn -ntp package -Passembly -Dquick -f ${pom} 1>&2
	cd ../
	mkdir -p target
	cp "debezium-server-voyager-dist/target/debezium-server-voyager-dist-${version}.Final.tar.gz" target/

	popd > /dev/null
}

install_yb_client(){
	output "Installing yb client..."
	pushd `git rev-parse --show-toplevel` > /dev/null
	cd debezium-server-voyager/yb-client-cdc-stream-wrapper
	mvn -ntp clean package 1>&2
	popd > /dev/null
}

package_debezium_server(){
	output "Packaging debezium server..."
	pushd `git rev-parse --show-toplevel` > /dev/null

	cd debezium-server-voyager/target
	tar -xvzf "debezium-server-voyager-dist-${DEBEZIUM_LOCAL_VERSION}.Final.tar.gz" 1>&2
	rm "debezium-server-voyager-dist-${DEBEZIUM_LOCAL_VERSION}.Final.tar.gz"
	tar -xvzf "debezium-server-voyager-dist-${DEBEZIUM_LOCAL_VERSION_1X}.Final.tar.gz" -C debezium-server/ 1>&2
	rm "debezium-server-voyager-dist-${DEBEZIUM_LOCAL_VERSION_1X}.Final.tar.gz"
	mv debezium-server/debezium-server debezium-server/debezium-server-1.9.5
	wget -nv https://github.com/yugabyte/debezium-connector-yugabytedb/releases/download/v1.9.5.y.31/debezium-connector-yugabytedb-1.9.5.y.31.jar -P debezium-server/debezium-server-1.9.5/lib 1>&2
	mv ../yb-client-cdc-stream-wrapper/target/yb-client-cdc-stream-wrapper.jar debezium-server/debezium-server-1.9.5/
	
	output "Moving debezium-server to ${DEBEZIUM_LOCAL_INSTALLATION_DESTINATION}/debezium-server"
	# delete contents of DEBEZIUM_LOCAL_INSTALLATION_DESTINATION/debezium-server if exists. 
	# This is done to ensure that older version jars are not left behind in the lib dir.
	if [ -d "${DEBEZIUM_LOCAL_INSTALLATION_DESTINATION}/debezium-server" ]
	then 
		sudo rm -Rf "${DEBEZIUM_LOCAL_INSTALLATION_DESTINATION}/debezium-server"
	fi

	mv debezium-server "${DEBEZIUM_LOCAL_INSTALLATION_DESTINATION}/"	
	popd > /dev/null
}


main 2>> $LOG_FILE
{ set +x; } 2> /dev/null
