BEGIN;

DROP TABLE IF EXISTS public.subject_t CASCADE;
DROP TABLE IF EXISTS public.control_t CASCADE;

CREATE TABLE public.control_t (
	id   BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	note TEXT
);

CREATE TABLE public.subject_t (
	id   BIGSERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	note TEXT
);

ALTER TABLE public.control_t  REPLICA IDENTITY FULL;
ALTER TABLE public.subject_t REPLICA IDENTITY FULL;

COMMIT;
