#!/usr/bin/env bash

set -e
set -x

export TEST_NAME="analyze-schema"

export REPO_ROOT="${PWD}"
export SCRIPTS="${REPO_ROOT}/migtests/scripts"
export TESTS_DIR="${REPO_ROOT}/migtests/tests"
export TEST_DIR="${TESTS_DIR}/${TEST_NAME}"
export EXPORT_DIR="${TEST_DIR}/dummy-export-dir"

export PYTHONPATH="${REPO_ROOT}/migtests/lib"

source ${SCRIPTS}/functions.sh

main() {
	pushd ${TEST_DIR}
	[ -d ${EXPORT_DIR}/reports ] || mkdir ${EXPORT_DIR}/reports

	export version=$(yb-voyager version | awk -F'=' '/VERSION/ {print $2}')
	sqlite3 ${EXPORT_DIR}/metainfo/meta.db "UPDATE json_objects SET json_text = json_set(json_text, '$.VoyagerVersion', '$version') WHERE key='migration_status';"

	step "Run analyze schema"
	analyze_schema --output-format json

	step "Run validations."
	 "${TEST_DIR}/validate"
}

main
