#!/usr/bin/env python3

import json

def main():
	with open("dummy-export-dir/reports/report.json") as fh:
		report = json.load(fh)
		print(json.dumps(report, indent=4))

	with open("expected_issues.json") as fh:
		expected_issues = json.load(fh)
		print(json.dumps(expected_issues, indent=4))

	validate_report(report, expected_issues)


def validate_report(report, expected_issues):
	print("Ensure that all the expected issues are reported.")
	for expected_issue in expected_issues:
		assert expected_issue in report["issues"], f"expected issue is not reported: {expected_issue}"

	assert len(expected_issues) == len(report["issues"])


if __name__ == "__main__":
	main()
