#!/usr/bin/env bash

set -e
set -x

export TEST_NAME="txt-migration-test"

export REPO_ROOT="${PWD}"
export SCRIPTS="${REPO_ROOT}/migtests/scripts"
export TESTS_DIR="${REPO_ROOT}/migtests/tests"
export TEST_DIR="${TESTS_DIR}/${TEST_NAME}"
export EXPORT_DIR=${EXPORT_DIR:-"${TEST_DIR}/export-dir"}

export PYTHONPATH="${REPO_ROOT}/migtests/lib"

export DATA_FILE_NAME="txt-migration-test/SMSA.txt"

source ${SCRIPTS}/yugabytedb/env.sh
source ${SCRIPTS}/functions.sh

export TARGET_DB_NAME="migrate_txt"
export TARGET_TABLE_NAME="txt_table"

CMD="CREATE TABLE ${TARGET_TABLE_NAME} (
    City VARCHAR(50),
    city_state CHAR(8),
    Jan_temp SMALLINT,
    July_temp INTEGER,
    Relhum BIGINT,
    Rain INT,
    Mortality NUMERIC,
    Education REAL,
    Pop_density DOUBLE PRECISION,
    PNonWhite SMALLINT,
    Pwc NUMERIC,
    Pop TEXT,
    Pop_house INTEGER,
    Income TEXT,
    HcPot NUMERIC,
    NOxpot REAL,
    SO2pot DOUBLE PRECISION,
    NOx NUMERIC
);
CREATE UNIQUE INDEX CITY_IND on TXT_TEST(City);"

main() {
	mkdir -p ${EXPORT_DIR}

	pushd ${TEST_DIR}

	step "Create target database."
	run_ysql yugabyte "DROP DATABASE IF EXISTS ${TARGET_DB_NAME};"
	run_ysql yugabyte "CREATE DATABASE ${TARGET_DB_NAME}"

	step "Create target table."
	run_ysql ${TARGET_DB_NAME} "${CMD}"

	step "Import data file"
	import_data_file --data-dir ${TEST_DIR} --format text --delimiter '\t' \
		--file-table-map "${DATA_FILE_NAME}:${TARGET_TABLE_NAME}"

	step "Run validations."
	 "${TEST_DIR}/validate" FILE_IMPORT_DONE
}

main
