#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_ROW_COUNT = {
	'subpartitioning_test': 11,
	'subpartitioning_test_p0': 3,
	'subpartitioning_test_p1': 2,
	'subpartitioning_test_p2': 3,
	'subpartitioning_test_p3': 2,
	'subpartitioning_test_p4': 1,
	'subpartitioning_test_p5': 0,
}

def migration_completed_checks(tgt):
	table_list = tgt.get_table_names(schema="test_mysql_partitions")
	print("table_list:", table_list)
	assert len(table_list) == 19
	
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		cnt = tgt.get_row_count(table_name, schema_name="test_mysql_partitions")
		print(f"table_name: {table_name}, row_count: {cnt}")
		assert row_count == cnt


if __name__ == "__main__":
	main()