#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i schema.sql;"

chmod +x ./snapshot.sh
./snapshot.sh 1000

if [ -n "${SOURCE_REPLICA_DB_NAME}" ];
then
	echo "Initialising FF database"
    run_psql ${SOURCE_REPLICA_DB_NAME} "\i schema.sql;"
fi