#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Assigning permissions to the validate files"
chmod +x ${TEST_DIR}/validate
chmod +x ${TEST_DIR}/validateAfterChanges

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i pg_datatypes_schema.sql;"
run_psql ${SOURCE_DB_NAME} "\i pg_datatypes_data.sql;"

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM num_types;"

if [ -n "${SOURCE_REPLICA_DB_NAME}" ];
then
	echo "Initialising FF database"
    run_psql ${SOURCE_REPLICA_DB_NAME} "\i pg_datatypes_schema.sql;"
fi  