#!/usr/bin/env python3

import common
import os
import yb

#=============================================================================

def is_grpc_connector():
    """Check if gRPC connector is being used"""
    return os.environ.get('USE_YB_GRPC_CONNECTOR', 'false').lower() == 'true'

#=============================================================================
# Base expected row counts (for gRPC connector)
BASE_EXPECTED_ROW_COUNT = {
    'num_types': 3,
    'datatypes1': 3,
    'datetime_type': 3,
    'datatypes2': 5,
    'datetime_type2': 2,
    'null_and_default': 2,
    'decimal_types': 4,
    'hstore_example': 27,
    'tsvector_table': 4,
    'enum_array_table': 4,
    'composite_types': 4,
	'composite_array_types': 4,
	'domain_types': 5,
	'domain_array_types': 5,
	'range_types': 5,
	'range_array_types': 5,
	'extension_types': 5,
	'extension_arrays': 5,
	'audit_log': 2,
    'numeric_types': 3,
	'numeric_arrays': 3,
	'datetime_types': 3,
	'datetime_arrays': 2,
	'geometry_types': 3,
	'geometry_arrays': 2,
	'network_types': 3,
	'network_arrays': 2,
	'misc_types': 3,
	'misc_arrays': 2
}

# Base expected row counts for FF (for gRPC connector)
BASE_EXPECTED_ROW_COUNT_FF = {
    'num_types': 3,
    'datatypes1': 2,
    'datetime_type': 1,
    'datatypes2': 6,
    'datetime_type2': 3,
    'null_and_default': 2,
    'decimal_types': 4,
    'hstore_example': 27,
    'tsvector_table': 4,
    'enum_array_table': 4,
    'composite_types': 4,
	'composite_array_types': 4,
	'domain_types': 5,
	'domain_array_types': 5,
	'range_types': 5,
	'range_array_types': 5,
	'extension_types': 5,
	'extension_arrays': 5,
	'audit_log': 2,
    'numeric_types': 3,
	'numeric_arrays': 3,
	'datetime_types': 3,
	'datetime_arrays': 2,
	'geometry_types': 3,
	'geometry_arrays': 2,
	'network_types': 3,
	'network_arrays': 2,
	'misc_types': 3,
	'misc_arrays': 2
}

# Replacement row counts when logical replication connector is used
LOGICAL_REPLICATION_ROW_OVERRIDES = {
    'hstore_example': 29,
    'tsvector_table': 5,
    'enum_array_table': 5,
    'composite_types': 6,
    'composite_array_types': 6,
    'domain_types': 7,
    'domain_array_types': 7,
    'range_types': 7,
    'range_array_types': 7,
    'extension_types': 7,
    'extension_arrays': 7,
    'audit_log': 2,
    'numeric_types': 3,
	'numeric_arrays': 3,
	'datetime_types': 3,
	'datetime_arrays': 2,
	'geometry_types': 3,
	'geometry_arrays': 2,
	'network_types': 3,
	'network_arrays': 2,
	'misc_types': 3,
	'misc_arrays': 2
}

EXPECTED_SUM_OF_COLUMN = {
    'num_types': {
        'v1': '32556',
        'v2': '211369200',
        'v3': '1844675717304493978',
        'v4': '1570.685',
        'v5': '39691.3578',
        'v6': '$217,175.38'
    },
    'decimal_types': {
        'n1': '2853392251566501749938533440831300954025170802737098078636711923415133694412160070629816221840337665.109639922',
        'n2': '180349583731554025.26'
    },
}

EXPECTED_SUM_OF_COLUMN_FF = {
    'num_types': {
        'v1': '16401',
        'v2': '214783737',
        'v3': '1844674408679724160',
        'v4': '574.686',
        'v5': '79444.4418',
        'v6': '$227,070.58'
    },
    'decimal_types': {
        'n1': '531349381567983913051474631101346872050803974030268278014088484327035860106983140443622806995814770.993622164',
        'n2': '111797748546368966.60'
    },
}

EXPECTED_DISTINCT_VALUES = {
    'v2': ['1001100101', '0001010101', '0101010101', '1010101010', '0000101010'],
    'v5': ['0001010101', '0001010', '101010101010101010101010101010', '001010101', '1010101010101010101010']
}

EXPECTED_DISTINCT_VALUES_FF = {
    'v2': ['1001100101', '0001010101', '0101010101', '1111000011', '0000101010', '1101010101'],
    'v5': ['0001010101', '0001010', '00101010010101010101010101001', '1010101010101010101010',
           '10101010101010101', '01001010101010101000101010']
}

# Base expected hstore values (for gRPC connector and regular live migration)
EXPECTED_HSTORE_VALUES = [
    '"key1"=>"value1", "key2"=>"value2", "key3"=>"value3"',
    None,
    '',
    '"{\\"key1=value1, key2=value2\\"}"=>"{\\"key1=value1, key2={\\"key1=value1, key2=value2\\"}\\"}"',
    '""=>"emptykey"',
    '"emptyvalue"=>""',
    '"longkey"=>"{}"'.format('x'*10000),
    '"ключ"=>"значение"',
    '"emoji_😀"=>"😎🔥"',
    '"café"=>"naïve"',
    '"select"=>"statement"',
    '"dup"=>"first"',
    '"key with spaces"=>"value with spaces"',
    '" space_key "=>" space_value "',
    '"key\\"quote"=>"value\\"quote"',
    '"key\'single"=>"value\'single"',
    '"{\\"json_like_key\\":1}"=>"{\\"json_like_value\\":2}"',
	'"\\"{key1:value1,key2:value2}\\""=>"{\\"key1=value1, key2={\\"key1=value1, key2=value2\\"}\\"}"',
	'"\\"{\\"\\"key1\\"\\":\\"\\"value1\\"\\",\\"\\"key2\\"\\":\\"\\"value2\\"\\"}\\""=>"{\\"key1=value1, key2={\\"key1=value1, key2=value2\\"}\\"}"',
	'"key=,=>"=>"value\\\\n\\\\t"',
    '"k1"=>"v1", "k2"=>"v2", "k3"=>"v3"',
    '"key5"=>"value5", "key6"=>"value6"',
    '"multi_key1"=>"val1", "multi key 2"=>"value with spaces", "unicode_αβ"=>"Ωmega", "escaped\\"quote"=>"line1nline2"'
	]

# Logical replication hstore values for fall-forward/fall-back scenarios
EXPECTED_HSTORE_VALUES_LOGICAL_FF_FB = [
    '"key1"=>"value1", "key2"=>"value2", "key3"=>"value3"',
    None,
    '',
    '"{\\"key1=value1, key2=value2\\"}"=>"{\\"key1=value1, key2={\\"key1=value1, key2=value2\\"}\\"}"',
    '"longkey"=>"{}"'.format('x'*10000),
    '"ключ"=>"значение"',
    '"emoji_😀"=>"😎🔥"',
    '"café"=>"naïve"',
    '"select"=>"statement"',
    '"dup"=>"first"',
    '"key with spaces"=>"value with spaces"',
    '" space_key "=>" space_value "',
    '"key\\"quote"=>"value\\"quote"',
    '"key\'single"=>"value\'single"',
    '"{\\"json_like_key\\":1}"=>"{\\"json_like_value\\":2}"',
	'"\\"{\\"\\"key1\\"\\":\\"\\"value1\\"\\",\\"\\"key2\\"\\":\\"\\"value2\\"\\"}\\""=>"{\\"key1=value1, key2={\\"key1=value1, key2=value2\\"}\\"}"',
    '"key7"=>"value7", "key8"=>"value8"',
    '"multi_key1"=>"val1", "multi key 2"=>"value with spaces", "unicode_αβ"=>"Ωmega", "escaped\\"quote"=>"line1nline2"',
    '"f1"=>"1", "f2"=>"{\\"key1=value1, key2=value2\\"}"',
    '"empty_row"=>""',
    '"new_key"=>"new_val", "{\\"key1=value1, key2=value2\\"}"=>"{\\"key1=value1, key2={\\"key1=value1, key2=value2\\"}\\"}"'
	]

EXPECTED_COMPOSITE_TYPES_VALUES = ['(City1I,"Street 1I",1)', '(City2I,"Street 2I",2)', '(City3,"Street 3",3)', '(UpdatedCity,UpdatedStreet,99999)']

EXPECTED_COMPOSITE_TYPES_VALUES_LOGICAL_FF_FB = ['(City2I,"Street 2I",2)', '(UpdatedCity,UpdatedStreet,99999)', '(City4,"Street 4",4)', '(City5,"Street 5",5)', '(City6,"Street 6",6)']

EXPECTED_COMPOSITE_ARRAY_TYPES_VALUES = [
    '{"(CityA1I,\\"StreetA 1I\\",1)","(CityB1I,\\"StreetB 1I\\",2)"}',
    '{"(CityA2I,\\"StreetA 2I\\",2)","(CityB2I,\\"StreetB 2I\\",3)"}',
    '{"(CityA2,\\"StreetA 2\\",2)","(CityB2,\\"StreetB 2\\",3)"}',
    '{"(UpdatedCity1,UpdatedStreet1,11111)","(UpdatedCity2,UpdatedStreet2,22222)"}',
]

EXPECTED_COMPOSITE_ARRAY_TYPES_VALUES_LOGICAL_FF_FB = [
    '{"(CityA2I,\\"StreetA 2I\\",2)","(CityB2I,\\"StreetB 2I\\",3)"}',
    '{"(CityA2,\\"StreetA 2\\",2)","(CityB2,\\"StreetB 2\\",3)"}',
    '{"(UpdatedCity1,UpdatedStreet1,11111)","(UpdatedCity2,UpdatedStreet2,22222)"}',
    '{"(CityA5,\\"StreetA 5\\",5)","(CityB5,\\"StreetB 5\\",6)"}',
    '{"(CityA6,\\"StreetA 6\\",6)","(CityB6,\\"StreetB 6\\",7)"}',
    '{"(UpdatedCity4,UpdatedStreet4,44444)","(UpdatedCity5,UpdatedStreet5,55555)"}',
]

EXPECTED_DOMAIN_TYPES_SSN_VALUES = ['001-00-0001', '002-00-0002', '003-00-0003', '003-00-0006', '123-45-6789']
EXPECTED_DOMAIN_TYPES_EMAIL_VALUES = ['user1@example.com', 'user2@example.com', 'user3@example.com', 'user6@example.com', 'updated@example.com']
EXPECTED_DOMAIN_TYPES_RATING_VALUES = [1, 2, 3, 5, 5]
EXPECTED_DOMAIN_TYPES_PREFS_VALUES = ["{'theme': 'dark', 'version': '1'}", "{'theme': 'dark', 'version': '2'}", "{'theme': 'dark', 'version': '3'}", "{'theme': 'dark', 'version': '6'}", "{'theme': 'light', 'version': 'updated'}"]

EXPECTED_DOMAIN_TYPES_SSN_VALUES_LOGICAL_FF_FB = ['001-00-0001', '002-00-0002', '003-00-0003', '003-00-0006', '123-45-6789', '003-00-0009', '123-45-6789']
EXPECTED_DOMAIN_TYPES_EMAIL_VALUES_LOGICAL_FF_FB = ['user1@example.com', 'user2@example.com', 'user3@example.com', 'user6@example.com', 'updated@example.com', 'user9@example.com', 'updated@example.com']
EXPECTED_DOMAIN_TYPES_RATING_VALUES_LOGICAL_FF_FB = [1, 2, 3, 5, 5, 5, 5]
EXPECTED_DOMAIN_TYPES_PREFS_VALUES_LOGICAL_FF_FB = ["{'theme': 'dark', 'version': '1'}", "{'theme': 'dark', 'version': '2'}", "{'theme': 'dark', 'version': '3'}", "{'theme': 'dark', 'version': '6'}", "{'theme': 'light', 'version': 'updated'}", "{'theme': 'dark', 'version': '9'}", "{'theme': 'light', 'version': 'updated'}"]

EXPECTED_DOMAIN_ARRAY_TYPES_SSN_VALUES = ['{123-45-0001,987-65-0001}', '{123-45-0002,987-65-0002}', '{123-45-0003,987-65-0003}', '{123-45-0006,987-65-0006}', '{111-22-3333,444-55-6666}']
EXPECTED_DOMAIN_ARRAY_TYPES_PHONE_VALUES = ['{+91123456701,+91987654301}', '{+91123456702,+91987654302}', '{+91123456703,+91987654303}', '{+91123456706,+91987654306}', '{+911111111111,+922222222222}']
EXPECTED_DOMAIN_ARRAY_TYPES_NAME_VALUES = ['{"ABC DEF","GHI JKL"}', '{"MNO PQR","STU VWX"}', '{"ABC XYZ","DEF ABC"}', '{"ABCD XYZ","DEFG ABC"}', '{"Updated Person","Another Update"}']

EXPECTED_DOMAIN_ARRAY_TYPES_SSN_VALUES_LOGICAL_FF_FB = ['{123-45-0001,987-65-0001}', '{123-45-0002,987-65-0002}', '{123-45-0003,987-65-0003}', '{123-45-0006,987-65-0006}', '{111-22-3333,444-55-6666}', '{123-45-0009,987-65-0009}', '{111-22-3333,444-55-6666}']
EXPECTED_DOMAIN_ARRAY_TYPES_PHONE_VALUES_LOGICAL_FF_FB = ['{+91123456701,+91987654301}', '{+91123456702,+91987654302}', '{+91123456703,+91987654303}', '{+91123456706,+91987654306}', '{+911111111111,+922222222222}', '{+91123456709,+91987654309}', '{+911111111111,+922222222222}']
EXPECTED_DOMAIN_ARRAY_TYPES_NAME_VALUES_LOGICAL_FF_FB = ['{"ABC DEF","GHI JKL"}', '{"MNO PQR","STU VWX"}', '{"ABC XYZ","DEF ABC"}', '{"ABCD XYZ","DEFG ABC"}', '{"Updated Person","Another Update"}', '{"EFGH IJKL","UVWXYZ ABCD"}', '{"Updated Person","Another Update"}']

EXPECTED_RANGE_ARRAY_TYPES_PRICE_VALUES = ['{"[1,5)","[10,20)"}', '{"[1,5)","[10,20)"}', '{"[1,5)","[10,20)"}', '{"[1,5)","[10,20)"}', '{"[50,60)"}']
EXPECTED_RANGE_ARRAY_TYPES_DISCOUNT_VALUES = ['{"[0.5,1)","[1.5,2)"}', '{"[0.5,1)","[1.5,2)"}', '{"[0.5,1)","[1.5,2)"}', '{"[0.5,1)","[1.5,2)"}', '{"[0.1,0.2)"}']

EXPECTED_RANGE_ARRAY_TYPES_PRICE_VALUES_LOGICAL_FF_FB = ['{"[1,5)","[10,20)"}', '{"[1,5)","[10,20)"}', '{"[1,5)","[10,20)"}', '{"[1,5)","[10,20)"}', '{"[50,60)"}', '{"[2,6)","[12,22)"}', '{"[50,60)"}']
EXPECTED_RANGE_ARRAY_TYPES_DISCOUNT_VALUES_LOGICAL_FF_FB = ['{"[0.5,1)","[1.5,2)"}', '{"[0.5,1)","[1.5,2)"}', '{"[0.5,1)","[1.5,2)"}', '{"[0.5,1)","[1.5,2)"}', '{"[0.1,0.2)"}', '{"[0.6,1.1)","[1.2,2.3)"}', '{"[0.1,0.2)"}']

EXPECTED_EXTENSION_TYPES_HSTORE_VALUES = ['"key1"=>"1"', '"key2"=>"2"', '"key3"=>"3"', '"key5"=>"5"', '"updated"=>"1"']
EXPECTED_EXTENSION_TYPES_CITEXT_VALUES = ['text_1', 'text_2', 'text_3', 'text_5', 'updated_text']
EXPECTED_EXTENSION_TYPES_LTREE_VALUES = ['Top.1', 'Top.2', 'Top.3', 'Top.5', 'Updated.Node']

EXPECTED_EXTENSION_TYPES_HSTORE_VALUES_LOGICAL_FF_FB = ['"key1"=>"1"', '"key2"=>"2"', '"key3"=>"3"', '"key5"=>"5"', '"updated"=>"1"', '"key8"=>"8"', '"updated"=>"1"']
EXPECTED_EXTENSION_TYPES_CITEXT_VALUES_LOGICAL_FF_FB = ['text_1', 'text_2', 'text_3', 'text_5', 'updated_text', 'text_8', 'updated_text']
EXPECTED_EXTENSION_TYPES_LTREE_VALUES_LOGICAL_FF_FB = ['Top.1', 'Top.2', 'Top.3', 'Top.5', 'Updated.Node', 'Top.8', 'Updated.Node']

EXPECTED_EXTENSION_ARRAYS_HSTORE_VALUES = ['{"\\"key1\\"=>\\"1\\"","\\"value1\\"=>\\"1\\""}', '{"\\"key2\\"=>\\"2\\"","\\"value2\\"=>\\"2\\""}', '{"\\"key3\\"=>\\"3\\"","\\"value3\\"=>\\"3\\""}', '{"\\"key4\\"=>\\"4\\"","\\"value4\\"=>\\"4\\""}', '{"\\"a\\"=>\\"1\\"","\\"b\\"=>\\"2\\""}']
EXPECTED_EXTENSION_ARRAYS_CITEXT_VALUES = ['{text_1,sample_1}', '{text_2,sample_2}', '{text_3,sample_3}', '{text_4,sample_4}', '{updated1,updated2}']
EXPECTED_EXTENSION_ARRAYS_LTREE_VALUES = ['{Top.1,Category.1}', '{Top.2,Category.2}', '{Top.3,Category.3}', '{Top.4,Category.4}', '{Top.Science,Top.Arts}']

EXPECTED_EXTENSION_ARRAYS_HSTORE_VALUES_LOGICAL_FF_FB = ['{"\\"key1\\"=>\\"1\\"","\\"value1\\"=>\\"1\\""}', '{"\\"key2\\"=>\\"2\\"","\\"value2\\"=>\\"2\\""}', '{"\\"key3\\"=>\\"3\\"","\\"value3\\"=>\\"3\\""}', '{"\\"key4\\"=>\\"4\\"","\\"value4\\"=>\\"4\\""}', '{"\\"a\\"=>\\"1\\"","\\"b\\"=>\\"2\\""}', '{"\\"key9\\"=>\\"9\\"","\\"value9\\"=>\\"9\\""}', '{"\\"a\\"=>\\"1\\"","\\"b\\"=>\\"2\\""}']
EXPECTED_EXTENSION_ARRAYS_CITEXT_VALUES_LOGICAL_FF_FB = ['{text_1,sample_1}', '{text_2,sample_2}', '{text_3,sample_3}', '{text_4,sample_4}', '{updated1,updated2}', '{text_9,sample_9}', '{updated1,updated2}']
EXPECTED_EXTENSION_ARRAYS_LTREE_VALUES_LOGICAL_FF_FB = ['{Top.1,Category.1}', '{Top.2,Category.2}', '{Top.3,Category.3}', '{Top.4,Category.4}', '{Top.Science,Top.Arts}', '{Top.9,Category.9}', '{Top.Science,Top.Arts}']

EXPECTED_AUDIT_LOG_EMPLOYEES_VALUES = ['{"(Emp_1,active,emp_1@company.com)","(EmpAlt_1,inactive,empalt_1@company.com)"}', '{"(UpdatedEmp_A,active,updated_a@company.com)","(UpdatedEmp_B,terminated,updated_b@company.com)"}']
EXPECTED_AUDIT_LOG_CLIENTS_VALUES = ['{"(Client_1,north,client_1@example.com)","(ClientAlt_1,south,clientalt_1@example.com)"}', '{"(UpdatedClient_A,east,client_a_updated@example.com)","(UpdatedClient_B,west,client_b_updated@example.com)"}']
EXPECTED_AUDIT_LOG_TRANSACTION_REFS_VALUES = [[1, 2, 3], [100, 200, 300]]

EXPECTED_AUDIT_LOG_EMPLOYEES_VALUES_LOGICAL_FF_FB = ['{"(Emp_1,active,emp_1@company.com)","(EmpAlt_1,inactive,empalt_1@company.com)"}', '{"(FollowupEmp_1,inactive,followup1@company.com)","(FollowupEmp_2,active,followup2@company.com)"}']
EXPECTED_AUDIT_LOG_CLIENTS_VALUES_LOGICAL_FF_FB = ['{"(Client_1,north,client_1@example.com)","(ClientAlt_1,south,clientalt_1@example.com)"}','{"(FollowupClient_1,south,followupc1@example.com)","(FollowupClient_2,north,followupc2@example.com)"}']
EXPECTED_AUDIT_LOG_TRANSACTION_REFS_VALUES_LOGICAL_FF_FB = [[1, 2, 3], [50, 60, 70]]

EXPECTED_NUMERIC_TYPES_REAL_VALUES = [1.1, 7.7, 9.9]
EXPECTED_NUMERIC_TYPES_DOUBLE_VALUES = [1.2, 6.6, 8.8]
EXPECTED_NUMERIC_TYPES_SMALL_SERIAL_VALUES = [1, 10, 12]
EXPECTED_NUMERIC_TYPES_BIG_SERIAL_VALUES = [1, 11, 13]

EXPECTED_NUMERIC_TYPES_REAL_VALUES_LOGICAL_FF_FB = [9.9, 13.3, 15.5]
EXPECTED_NUMERIC_TYPES_DOUBLE_VALUES_LOGICAL_FF_FB = [8.8, 12.2, 14.4]
EXPECTED_NUMERIC_TYPES_SMALL_SERIAL_VALUES_LOGICAL_FF_FB = [10, 21, 23]
EXPECTED_NUMERIC_TYPES_BIG_SERIAL_VALUES_LOGICAL_FF_FB = [11, 22, 24]

EXPECTED_NUMERIC_ARRAYS_REAL_VALUES = [[1.1, 1.2, 1.3], [9.9, 8.8, 7.7], [3.3, 2.2, 1.1]]
EXPECTED_NUMERIC_ARRAYS_DOUBLE_VALUES = [[1.1, 1.2, 1.3], [6.6, 5.5, 4.4], [9.9, 9.1, 8.2]]

EXPECTED_NUMERIC_ARRAYS_REAL_VALUES_LOGICAL_FF_FB = [[1.1, 1.2, 1.3], [9.9, 8.8, 7.7], [11.1, 12.2, 13.3], [17.7, 18.8, 19.9]]
EXPECTED_NUMERIC_ARRAYS_DOUBLE_VALUES_LOGICAL_FF_FB = [[1.1, 1.2, 1.3], [6.6, 5.5, 4.4], [14.4, 15.5, 16.6], [21.1, 22.2, 23.3]]

EXPECTED_DATETIME_TYPES_TIMESTAMPTZ_VALUES = ['2024-12-01 05:52:33+00', '2026-06-10 08:45:00+00', '2027-12-31 22:00:00+00']
EXPECTED_DATETIME_TYPES_TIMEZONE_VALUES = ['09:30:15+05:30', '03:35:00+00', '23:59:59+02']
EXPECTED_DATETIME_TYPES_INTERVAL_VALUES = ['0:17:00', '11:00:00', '0:22:00']

EXPECTED_DATETIME_TYPES_TIMESTAMPTZ_VALUES_LOGICAL_FF_FB = ['2024-12-01 05:52:33+00', '2026-06-10 08:45:00+00', '2027-12-31 22:00:00+00']
EXPECTED_DATETIME_TYPES_TIMEZONE_VALUES_LOGICAL_FF_FB = ['09:30:15+05:30', '03:35:00+00', '23:59:59+02']
EXPECTED_DATETIME_TYPES_INTERVAL_VALUES_LOGICAL_FF_FB = ['0:41:00', '11:00:00', '9:00:00']

EXPECTED_DATETIME_ARRAYS_TIMESTAMPTZ_VALUES = ['2024-10-11 10:10:10+00', '2024-12-25 00:00:00+00', '2024-12-31 22:00:00+00', '2031-07-07 04:00:00+00', '2032-08-08 10:30:00+00']
EXPECTED_DATETIME_ARRAYS_TIMEZONE_VALUES = ['10:11:12+05', '23:45:00+02', '03:33:33-04', '07:00:00+05:30', '13:30:45+01', '22:10:00-02']
EXPECTED_DATETIME_ARRAYS_INTERVAL_VALUES = ['[datetime.timedelta(seconds=600), datetime.timedelta(seconds=10800), datetime.timedelta(days=2)]', '[datetime.timedelta(seconds=900), datetime.timedelta(days=1, seconds=10800)]']

EXPECTED_DATETIME_ARRAYS_TIMESTAMPTZ_VALUES_LOGICAL_FF_FB = ['2024-10-11 10:10:10+00', '2024-12-25 00:00:00+00', '2024-12-31 22:00:00+00', '2031-07-07 04:00:00+00', '2032-08-08 10:30:00+00']
EXPECTED_DATETIME_ARRAYS_TIMEZONE_VALUES_LOGICAL_FF_FB = ['10:11:12+05', '23:45:00+02', '03:33:33-04', '07:00:00+05:30', '13:30:45+01', '22:10:00-02']
EXPECTED_DATETIME_ARRAYS_INTERVAL_VALUES_LOGICAL_FF_FB = ['[datetime.timedelta(seconds=18000), datetime.timedelta(seconds=1980)]', '[datetime.timedelta(days=1), datetime.timedelta(seconds=2820)]']

EXPECTED_GEOMETRY_ARRAYS_POINT_VALUES = ['{"(8,8)","(9,9)"}', '{"(1,1)","(2,2)","(3,3)"}']
EXPECTED_GEOMETRY_ARRAYS_LINE_VALUES = ['{"{1,-1,0}","{1,-1,0}"}', '{"{1,-1,0}"}']
EXPECTED_GEOMETRY_ARRAYS_LSEG_VALUES = ['{"[(0,0),(5,5)]","[(1,2),(3,4)]"}', '{"[(6,6),(12,16)]"}']
EXPECTED_GEOMETRY_ARRAYS_BOX_VALUES = ['{(2,2),(0,0);(5,3),(1,1)}', '{(10,12),(4,4)}']
EXPECTED_GEOMETRY_ARRAYS_PATH_VALUES = ['{"[(0,0),(1,2),(3,1)]","[(2,2),(3,5)]"}', '{"[(5,5),(11,13)]"}']
EXPECTED_GEOMETRY_ARRAYS_POLYGON_VALUES = ['{"((0,0),(3,0),(3,3),(0,3))","((1,1),(4,1),(4,4),(1,4))"}', '{"((5,5),(12,5),(12,12),(5,12))"}']
EXPECTED_GEOMETRY_ARRAYS_CIRCLE_VALUES = ['{"<(1,1),2>","<(3,3),4>"}', '{"<(5,5),4>"}']

EXPECTED_GEOMETRY_ARRAYS_POINT_VALUES_LOGICAL_FF_FB = ['{"(11,11)","(12,12)","(13,13)"}', '{"(14,14)","(15,15)"}']
EXPECTED_GEOMETRY_ARRAYS_LINE_VALUES_LOGICAL_FF_FB = ['{"{1,-1,0}","{1,-1,0}"}', '{"{1,-1,0}"}']
EXPECTED_GEOMETRY_ARRAYS_LSEG_VALUES_LOGICAL_FF_FB = ['{"[(9,14),(20,30)]"}', '{"[(4,10),(14,18)]"}']
EXPECTED_GEOMETRY_ARRAYS_BOX_VALUES_LOGICAL_FF_FB = ['{(14,18),(6,6)}', '{(20,25),(8,8)}']
EXPECTED_GEOMETRY_ARRAYS_PATH_VALUES_LOGICAL_FF_FB = ['{"[(8,8),(14,20)]"}', '{"[(9,9),(18,28)]"}']
EXPECTED_GEOMETRY_ARRAYS_POLYGON_VALUES_LOGICAL_FF_FB = ['{"((6,6),(16,6),(16,16),(6,16))"}', '{"((7,7),(20,7),(20,20),(7,20))"}']
EXPECTED_GEOMETRY_ARRAYS_CIRCLE_VALUES_LOGICAL_FF_FB = ['{"<(9,9),5>"}', '{"<(7,7),4>","<(11,11),6>"}'] 

EXPECTED_NETWORK_TYPES_CIDR_VALUES = ['10.0.0.0/8', '8.8.0.0/16', '6.6.0.0/16']
EXPECTED_NETWORK_TYPES_INET_VALUES = ['10.1.2.3', '8.8.8.8', '6.6.6.6']
EXPECTED_NETWORK_TYPES_MACADDR_VALUES = ['aa:bb:cc:dd:ee:ff', 'aa:00:11:22:33:44', 'bb:22:33:44:55:66']
EXPECTED_NETWORK_TYPES_MACADDR8_VALUES = ['aa:bb:cc:ff:fe:dd:ee:ff', 'aa:00:11:ff:fe:22:33:44', 'bb:22:33:ff:fe:44:55:66']

EXPECTED_NETWORK_TYPES_CIDR_VALUES_LOGICAL_FF_FB = ['8.8.0.0/16', '9.9.0.0/16', '11.11.0.0/16']
EXPECTED_NETWORK_TYPES_INET_VALUES_LOGICAL_FF_FB = ['8.8.8.8', '11.11.11.11', '9.9.9.9']
EXPECTED_NETWORK_TYPES_MACADDR_VALUES_LOGICAL_FF_FB = ['aa:00:11:22:33:44', 'dd:55:66:77:88:99', 'cc:44:55:66:77:88']
EXPECTED_NETWORK_TYPES_MACADDR8_VALUES_LOGICAL_FF_FB = ['aa:00:11:ff:fe:22:33:44', 'cc:44:55:ff:fe:66:77:88', 'dd:55:66:ff:fe:77:88:99']

EXPECTED_NETWORK_ARRAYS_CIDR_VALUES = ["['7.0.0.0/8', '7.10.0.0/16']", "['10.0.0.0/8', '10.10.0.0/16', '10.20.30.0/24']"]
EXPECTED_NETWORK_ARRAYS_INET_VALUES = ["['10.0.0.1', '10.10.0.5', '10.20.30.99']", "['7.0.0.1', '7.10.0.5']"]
EXPECTED_NETWORK_ARRAYS_MACADDR_VALUES = ["['aa:bb:cc:11:22:33', 'aa:bb:cc:44:55:66', 'aa:bb:cc:77:88:99']", "['dd:11:22:33:44:55', 'dd:66:77:88:99:aa']"]
EXPECTED_NETWORK_ARRAYS_MACADDR8_VALUES = ['{dd:11:22:ff:fe:33:44:55,dd:66:77:ff:fe:88:99:aa}', '{aa:bb:cc:ff:fe:11:22:33,aa:bb:cc:ff:fe:44:55:66,aa:bb:cc:ff:fe:77:88:99}']

EXPECTED_NETWORK_ARRAYS_CIDR_VALUES_LOGICAL_FF_FB = ["['11.0.0.0/8', '11.20.0.0/16', '11.30.40.0/24']", "['12.0.0.0/8', '12.10.0.0/16']"]
EXPECTED_NETWORK_ARRAYS_INET_VALUES_LOGICAL_FF_FB = ["['11.0.0.1', '11.20.0.5', '11.30.40.99']", "['12.0.0.1', '12.10.0.5']"]
EXPECTED_NETWORK_ARRAYS_MACADDR_VALUES_LOGICAL_FF_FB = ["['ff:11:22:33:44:55', 'ff:66:77:88:99:aa']", "['ee:11:22:33:44:55', 'ee:66:77:88:99:aa', 'ee:bb:cc:dd:ee:ff']"]
EXPECTED_NETWORK_ARRAYS_MACADDR8_VALUES_LOGICAL_FF_FB = ['{ee:11:22:ff:fe:33:44:55,ee:66:77:ff:fe:88:99:aa,ee:bb:cc:ff:fe:dd:ee:ff}', '{ff:11:22:ff:fe:33:44:55,ff:66:77:ff:fe:88:99:aa}']

EXPECTED_MISC_ARRAYS_PG_LSN_VALUES = ['{0/DDD0000,0/EEE0002}', '{0/16B6C50,0/1FFAA00,0/ABC1234}']
EXPECTED_MISC_ARRAYS_TXID_SNAPSHOT_VALUES = ['{10:20:15,100:105:101,88:90:89}', '{700:705:702,800:810:805}']

EXPECTED_MISC_ARRAYS_PG_LSN_VALUES_LOGICAL_FF_FB = ['{0/111AAAA,0/222BBBB,0/333CCCC}', '{0/444DDDD,0/555EEEE}']
EXPECTED_MISC_ARRAYS_TXID_SNAPSHOT_VALUES_LOGICAL_FF_FB = ['{800:805:802,820:825:823,840:845:842}', '{860:865:862,880:885:882}']

#=============================================================================

def build_expected_values(ff_fb_enabled: bool):
    """Return expected values depending on migration type and connector"""
    if not ff_fb_enabled:
        return {
            "row_count": BASE_EXPECTED_ROW_COUNT.copy(),
            "sum_of_column": EXPECTED_SUM_OF_COLUMN.copy(),
            "distinct_values": EXPECTED_DISTINCT_VALUES.copy(),
            "hstore_values": EXPECTED_HSTORE_VALUES,
            "composite_types": EXPECTED_COMPOSITE_TYPES_VALUES,
            "composite_array_types": EXPECTED_COMPOSITE_ARRAY_TYPES_VALUES,
            "domain_ssn_types": EXPECTED_DOMAIN_TYPES_SSN_VALUES,
            "domain_email_types": EXPECTED_DOMAIN_TYPES_EMAIL_VALUES,
            "domain_rating_types": EXPECTED_DOMAIN_TYPES_RATING_VALUES,
            "domain_prefs_types": EXPECTED_DOMAIN_TYPES_PREFS_VALUES,
            "domain_ssn_array_types": EXPECTED_DOMAIN_ARRAY_TYPES_SSN_VALUES,
            "domain_phone_array_types": EXPECTED_DOMAIN_ARRAY_TYPES_PHONE_VALUES,
            "domain_name_array_types": EXPECTED_DOMAIN_ARRAY_TYPES_NAME_VALUES,
            "range_price_array_types": EXPECTED_RANGE_ARRAY_TYPES_PRICE_VALUES,
            "range_discount_array_types": EXPECTED_RANGE_ARRAY_TYPES_DISCOUNT_VALUES,
            "extension_hstore_types": EXPECTED_EXTENSION_TYPES_HSTORE_VALUES,
            "extension_citext_types": EXPECTED_EXTENSION_TYPES_CITEXT_VALUES,
            "extension_ltree_types": EXPECTED_EXTENSION_TYPES_LTREE_VALUES,
            "extension_hstore_array_types": EXPECTED_EXTENSION_ARRAYS_HSTORE_VALUES,
            "extension_citext_array_types": EXPECTED_EXTENSION_ARRAYS_CITEXT_VALUES,
            "extension_ltree_array_types": EXPECTED_EXTENSION_ARRAYS_LTREE_VALUES,
            "audit_log_employees": EXPECTED_AUDIT_LOG_EMPLOYEES_VALUES,
            "audit_log_clients": EXPECTED_AUDIT_LOG_CLIENTS_VALUES,
            "audit_log_transaction_refs": EXPECTED_AUDIT_LOG_TRANSACTION_REFS_VALUES,
            "numeric_real_types": EXPECTED_NUMERIC_TYPES_REAL_VALUES,
            "numeric_double_types": EXPECTED_NUMERIC_TYPES_DOUBLE_VALUES,
            "numeric_small_serial_types": EXPECTED_NUMERIC_TYPES_SMALL_SERIAL_VALUES,
            "numeric_big_serial_types": EXPECTED_NUMERIC_TYPES_BIG_SERIAL_VALUES,
            "numeric_real_arrays": EXPECTED_NUMERIC_ARRAYS_REAL_VALUES,
            "numeric_double_arrays": EXPECTED_NUMERIC_ARRAYS_DOUBLE_VALUES,
            "datetime_timestamptz_types": EXPECTED_DATETIME_TYPES_TIMESTAMPTZ_VALUES,
            "datetime_timetz_types": EXPECTED_DATETIME_TYPES_TIMEZONE_VALUES,
            "datetime_interval_types": EXPECTED_DATETIME_TYPES_INTERVAL_VALUES,
            "datetime_timestamptz_arrays": EXPECTED_DATETIME_ARRAYS_TIMESTAMPTZ_VALUES,
            "datetime_timetz_arrays": EXPECTED_DATETIME_ARRAYS_TIMEZONE_VALUES,
            "datetime_interval_arrays": EXPECTED_DATETIME_ARRAYS_INTERVAL_VALUES,
            "geometry_point_arrays": EXPECTED_GEOMETRY_ARRAYS_POINT_VALUES,
            "geometry_line_arrays": EXPECTED_GEOMETRY_ARRAYS_LINE_VALUES,
            "geometry_lseg_arrays": EXPECTED_GEOMETRY_ARRAYS_LSEG_VALUES,
            "geometry_box_arrays": EXPECTED_GEOMETRY_ARRAYS_BOX_VALUES,
            "geometry_path_arrays": EXPECTED_GEOMETRY_ARRAYS_PATH_VALUES,
            "geometry_polygon_arrays": EXPECTED_GEOMETRY_ARRAYS_POLYGON_VALUES,
            "geometry_circle_arrays": EXPECTED_GEOMETRY_ARRAYS_CIRCLE_VALUES,
            "network_cidr_types": EXPECTED_NETWORK_TYPES_CIDR_VALUES,
            "network_inet_types": EXPECTED_NETWORK_TYPES_INET_VALUES,
            "network_macaddr_types": EXPECTED_NETWORK_TYPES_MACADDR_VALUES,
            "network_macaddr8_types": EXPECTED_NETWORK_TYPES_MACADDR8_VALUES,
            "network_cidr_arrays": EXPECTED_NETWORK_ARRAYS_CIDR_VALUES,
            "network_inet_arrays": EXPECTED_NETWORK_ARRAYS_INET_VALUES,
            "network_macaddr_arrays": EXPECTED_NETWORK_ARRAYS_MACADDR_VALUES,
            "network_macaddr8_arrays": EXPECTED_NETWORK_ARRAYS_MACADDR8_VALUES,
            "misc_pg_lsn_arrays": EXPECTED_MISC_ARRAYS_PG_LSN_VALUES,
            "misc_txid_snapshot_arrays": EXPECTED_MISC_ARRAYS_TXID_SNAPSHOT_VALUES
        }

    # FF/FB expected values
    expected = {
        "row_count": BASE_EXPECTED_ROW_COUNT_FF.copy(),
        "sum_of_column": EXPECTED_SUM_OF_COLUMN_FF.copy(),
        "distinct_values": EXPECTED_DISTINCT_VALUES_FF.copy(),
        "hstore_values": EXPECTED_HSTORE_VALUES,
        "composite_types": EXPECTED_COMPOSITE_TYPES_VALUES,
        "composite_array_types": EXPECTED_COMPOSITE_ARRAY_TYPES_VALUES,
        "domain_ssn_types": EXPECTED_DOMAIN_TYPES_SSN_VALUES,
        "domain_email_types": EXPECTED_DOMAIN_TYPES_EMAIL_VALUES,
        "domain_rating_types": EXPECTED_DOMAIN_TYPES_RATING_VALUES,
        "domain_prefs_types": EXPECTED_DOMAIN_TYPES_PREFS_VALUES,
        "domain_ssn_array_types": EXPECTED_DOMAIN_ARRAY_TYPES_SSN_VALUES,
        "domain_phone_array_types": EXPECTED_DOMAIN_ARRAY_TYPES_PHONE_VALUES,
        "domain_name_array_types": EXPECTED_DOMAIN_ARRAY_TYPES_NAME_VALUES,
        "range_price_array_types": EXPECTED_RANGE_ARRAY_TYPES_PRICE_VALUES,
        "range_discount_array_types": EXPECTED_RANGE_ARRAY_TYPES_DISCOUNT_VALUES,
        "extension_hstore_types": EXPECTED_EXTENSION_TYPES_HSTORE_VALUES,
        "extension_citext_types": EXPECTED_EXTENSION_TYPES_CITEXT_VALUES,
        "extension_ltree_types": EXPECTED_EXTENSION_TYPES_LTREE_VALUES,
        "extension_hstore_array_types": EXPECTED_EXTENSION_ARRAYS_HSTORE_VALUES,
        "extension_citext_array_types": EXPECTED_EXTENSION_ARRAYS_CITEXT_VALUES,
        "extension_ltree_array_types": EXPECTED_EXTENSION_ARRAYS_LTREE_VALUES,
        "audit_log_employees": EXPECTED_AUDIT_LOG_EMPLOYEES_VALUES,
        "audit_log_clients": EXPECTED_AUDIT_LOG_CLIENTS_VALUES,
        "audit_log_transaction_refs": EXPECTED_AUDIT_LOG_TRANSACTION_REFS_VALUES,
        "numeric_real_types": EXPECTED_NUMERIC_TYPES_REAL_VALUES,
        "numeric_double_types": EXPECTED_NUMERIC_TYPES_DOUBLE_VALUES,
        "numeric_small_serial_types": EXPECTED_NUMERIC_TYPES_SMALL_SERIAL_VALUES,
        "numeric_big_serial_types": EXPECTED_NUMERIC_TYPES_BIG_SERIAL_VALUES,
        "numeric_real_arrays": EXPECTED_NUMERIC_ARRAYS_REAL_VALUES,
        "numeric_double_arrays": EXPECTED_NUMERIC_ARRAYS_DOUBLE_VALUES,
        "datetime_timestamptz_types": EXPECTED_DATETIME_TYPES_TIMESTAMPTZ_VALUES,
        "datetime_timetz_types": EXPECTED_DATETIME_TYPES_TIMEZONE_VALUES,
        "datetime_interval_types": EXPECTED_DATETIME_TYPES_INTERVAL_VALUES,
        "datetime_timestamptz_arrays": EXPECTED_DATETIME_ARRAYS_TIMESTAMPTZ_VALUES,
        "datetime_timetz_arrays": EXPECTED_DATETIME_ARRAYS_TIMEZONE_VALUES,
        "datetime_interval_arrays": EXPECTED_DATETIME_ARRAYS_INTERVAL_VALUES,
        "geometry_point_arrays": EXPECTED_GEOMETRY_ARRAYS_POINT_VALUES,
        "geometry_line_arrays": EXPECTED_GEOMETRY_ARRAYS_LINE_VALUES,
        "geometry_lseg_arrays": EXPECTED_GEOMETRY_ARRAYS_LSEG_VALUES,
        "geometry_box_arrays": EXPECTED_GEOMETRY_ARRAYS_BOX_VALUES,
        "geometry_path_arrays": EXPECTED_GEOMETRY_ARRAYS_PATH_VALUES,
        "geometry_polygon_arrays": EXPECTED_GEOMETRY_ARRAYS_POLYGON_VALUES,
        "geometry_circle_arrays": EXPECTED_GEOMETRY_ARRAYS_CIRCLE_VALUES,
        "network_cidr_types": EXPECTED_NETWORK_TYPES_CIDR_VALUES,
        "network_inet_types": EXPECTED_NETWORK_TYPES_INET_VALUES,
        "network_macaddr_types": EXPECTED_NETWORK_TYPES_MACADDR_VALUES,
        "network_macaddr8_types": EXPECTED_NETWORK_TYPES_MACADDR8_VALUES,
        "network_cidr_arrays": EXPECTED_NETWORK_ARRAYS_CIDR_VALUES,
        "network_inet_arrays": EXPECTED_NETWORK_ARRAYS_INET_VALUES,
        "network_macaddr_arrays": EXPECTED_NETWORK_ARRAYS_MACADDR_VALUES,
        "network_macaddr8_arrays": EXPECTED_NETWORK_ARRAYS_MACADDR8_VALUES,
        "misc_pg_lsn_arrays": EXPECTED_MISC_ARRAYS_PG_LSN_VALUES,
        "misc_txid_snapshot_arrays": EXPECTED_MISC_ARRAYS_TXID_SNAPSHOT_VALUES
    }

    # Override for logical replication
    if not is_grpc_connector():
        for table, replacement in LOGICAL_REPLICATION_ROW_OVERRIDES.items():
            expected["row_count"][table] = replacement
        expected["hstore_values"] = EXPECTED_HSTORE_VALUES_LOGICAL_FF_FB
        expected["composite_types"] = EXPECTED_COMPOSITE_TYPES_VALUES_LOGICAL_FF_FB
        expected["composite_array_types"] = EXPECTED_COMPOSITE_ARRAY_TYPES_VALUES_LOGICAL_FF_FB
        expected["domain_ssn_types"] = EXPECTED_DOMAIN_TYPES_SSN_VALUES_LOGICAL_FF_FB
        expected["domain_email_types"] = EXPECTED_DOMAIN_TYPES_EMAIL_VALUES_LOGICAL_FF_FB
        expected["domain_rating_types"] = EXPECTED_DOMAIN_TYPES_RATING_VALUES_LOGICAL_FF_FB
        expected["domain_prefs_types"] = EXPECTED_DOMAIN_TYPES_PREFS_VALUES_LOGICAL_FF_FB
        expected["domain_ssn_array_types"] = EXPECTED_DOMAIN_ARRAY_TYPES_SSN_VALUES_LOGICAL_FF_FB
        expected["domain_phone_array_types"] = EXPECTED_DOMAIN_ARRAY_TYPES_PHONE_VALUES_LOGICAL_FF_FB
        expected["domain_name_array_types"] = EXPECTED_DOMAIN_ARRAY_TYPES_NAME_VALUES_LOGICAL_FF_FB
        expected["range_price_array_types"] = EXPECTED_RANGE_ARRAY_TYPES_PRICE_VALUES_LOGICAL_FF_FB
        expected["range_discount_array_types"] = EXPECTED_RANGE_ARRAY_TYPES_DISCOUNT_VALUES_LOGICAL_FF_FB
        expected["extension_hstore_types"] = EXPECTED_EXTENSION_TYPES_HSTORE_VALUES_LOGICAL_FF_FB
        expected["extension_citext_types"] = EXPECTED_EXTENSION_TYPES_CITEXT_VALUES_LOGICAL_FF_FB
        expected["extension_ltree_types"] = EXPECTED_EXTENSION_TYPES_LTREE_VALUES_LOGICAL_FF_FB
        expected["extension_hstore_array_types"] = EXPECTED_EXTENSION_ARRAYS_HSTORE_VALUES_LOGICAL_FF_FB
        expected["extension_citext_array_types"] = EXPECTED_EXTENSION_ARRAYS_CITEXT_VALUES_LOGICAL_FF_FB
        expected["extension_ltree_array_types"] = EXPECTED_EXTENSION_ARRAYS_LTREE_VALUES_LOGICAL_FF_FB
        expected["audit_log_employees"] = EXPECTED_AUDIT_LOG_EMPLOYEES_VALUES_LOGICAL_FF_FB
        expected["audit_log_clients"] = EXPECTED_AUDIT_LOG_CLIENTS_VALUES_LOGICAL_FF_FB
        expected["audit_log_transaction_refs"] = EXPECTED_AUDIT_LOG_TRANSACTION_REFS_VALUES_LOGICAL_FF_FB
        expected["numeric_real_types"] = EXPECTED_NUMERIC_TYPES_REAL_VALUES_LOGICAL_FF_FB
        expected["numeric_double_types"] = EXPECTED_NUMERIC_TYPES_DOUBLE_VALUES_LOGICAL_FF_FB
        expected["numeric_small_serial_types"] = EXPECTED_NUMERIC_TYPES_SMALL_SERIAL_VALUES_LOGICAL_FF_FB
        expected["numeric_big_serial_types"] = EXPECTED_NUMERIC_TYPES_BIG_SERIAL_VALUES_LOGICAL_FF_FB
        expected["numeric_real_arrays"] = EXPECTED_NUMERIC_ARRAYS_REAL_VALUES_LOGICAL_FF_FB
        expected["numeric_double_arrays"] = EXPECTED_NUMERIC_ARRAYS_DOUBLE_VALUES_LOGICAL_FF_FB
        expected["datetime_timestamptz_types"] = EXPECTED_DATETIME_TYPES_TIMESTAMPTZ_VALUES_LOGICAL_FF_FB
        expected["datetime_timetz_types"] = EXPECTED_DATETIME_TYPES_TIMEZONE_VALUES_LOGICAL_FF_FB
        expected["datetime_interval_types"] = EXPECTED_DATETIME_TYPES_INTERVAL_VALUES_LOGICAL_FF_FB
        expected["datetime_timestamptz_arrays"] = EXPECTED_DATETIME_ARRAYS_TIMESTAMPTZ_VALUES_LOGICAL_FF_FB
        expected["datetime_timetz_arrays"] = EXPECTED_DATETIME_ARRAYS_TIMEZONE_VALUES_LOGICAL_FF_FB
        expected["datetime_interval_arrays"] = EXPECTED_DATETIME_ARRAYS_INTERVAL_VALUES_LOGICAL_FF_FB
        expected["geometry_point_arrays"] = EXPECTED_GEOMETRY_ARRAYS_POINT_VALUES_LOGICAL_FF_FB
        expected["geometry_line_arrays"] = EXPECTED_GEOMETRY_ARRAYS_LINE_VALUES_LOGICAL_FF_FB
        expected["geometry_lseg_arrays"] = EXPECTED_GEOMETRY_ARRAYS_LSEG_VALUES_LOGICAL_FF_FB
        expected["geometry_box_arrays"] = EXPECTED_GEOMETRY_ARRAYS_BOX_VALUES_LOGICAL_FF_FB
        expected["geometry_path_arrays"] = EXPECTED_GEOMETRY_ARRAYS_PATH_VALUES_LOGICAL_FF_FB
        expected["geometry_polygon_arrays"] = EXPECTED_GEOMETRY_ARRAYS_POLYGON_VALUES_LOGICAL_FF_FB
        expected["geometry_circle_arrays"] = EXPECTED_GEOMETRY_ARRAYS_CIRCLE_VALUES_LOGICAL_FF_FB
        expected["network_cidr_types"] = EXPECTED_NETWORK_TYPES_CIDR_VALUES_LOGICAL_FF_FB
        expected["network_inet_types"] = EXPECTED_NETWORK_TYPES_INET_VALUES_LOGICAL_FF_FB
        expected["network_macaddr_types"] = EXPECTED_NETWORK_TYPES_MACADDR_VALUES_LOGICAL_FF_FB
        expected["network_macaddr8_types"] = EXPECTED_NETWORK_TYPES_MACADDR8_VALUES_LOGICAL_FF_FB
        expected["network_cidr_arrays"] = EXPECTED_NETWORK_ARRAYS_CIDR_VALUES_LOGICAL_FF_FB
        expected["network_inet_arrays"] = EXPECTED_NETWORK_ARRAYS_INET_VALUES_LOGICAL_FF_FB
        expected["network_macaddr_arrays"] = EXPECTED_NETWORK_ARRAYS_MACADDR_VALUES_LOGICAL_FF_FB
        expected["network_macaddr8_arrays"] = EXPECTED_NETWORK_ARRAYS_MACADDR8_VALUES_LOGICAL_FF_FB
        expected["misc_pg_lsn_arrays"] = EXPECTED_MISC_ARRAYS_PG_LSN_VALUES_LOGICAL_FF_FB
        expected["misc_txid_snapshot_arrays"] = EXPECTED_MISC_ARRAYS_TXID_SNAPSHOT_VALUES_LOGICAL_FF_FB

    return expected

#=============================================================================

def run_migration_checks(db_type: str, expected, ff_fb_enabled: bool = False):
    """Run validation checks on the given db_type (yb, source, source_replica)"""
    connector_type = "gRPC" if is_grpc_connector() else "logical replication"
    msg = f"Running validation on {db_type}"
    if ff_fb_enabled:
        msg += f" with {connector_type} connector expectations"
    print(msg)

    yb.run_checks(lambda tgt: migration_completed_checks(tgt, expected), db_type=db_type)

def migration_completed_checks(tgt, expected):
    got_row_count = tgt.row_count_of_all_tables("public")
    for table_name, row_count in expected["row_count"].items():
        print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}, expected: {row_count}")
        assert row_count == got_row_count[table_name]

    for table_name, column_names_with_sum in expected["sum_of_column"].items():
        print(f"table_name: {table_name} ---- ")
        for column, sum_val in column_names_with_sum.items():
            col_sum = tgt.get_sum_of_column_of_table(table_name, column, "public")
            print(f"column_name: {column}, sum: {col_sum}")
            assert sum_val == str(col_sum)

    print("distinct_bit10_values:")
    expected_distinct_values = expected["distinct_values"]["v2"]
    tgt.assert_distinct_values_of_col(
        "datatypes2", "v2", "public",
        transform_func=str,
        expected_distinct_values=expected_distinct_values
    )

    print("distinct_bit_varying_values:")
    expected_distinct_values = expected["distinct_values"]["v5"]
    tgt.assert_distinct_values_of_col(
        "datatypes2", "v5", "public",
        None,
        expected_distinct_values=expected_distinct_values
    )

    print("hstore_example:")
    expected_hstore_values = expected["hstore_values"]
    tgt.assert_distinct_values_of_col("hstore_example", "data", "public",
                                      expected_distinct_values=expected_hstore_values)

    print("composite_types:")
    expected_composite_values = expected.get("composite_types", [])
    tgt.assert_distinct_values_of_col("composite_types", "address", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_composite_values)

    print("composite_array_types:")
    expected_composite_array_values = expected.get("composite_array_types", [])
    tgt.assert_distinct_values_of_col("composite_array_types", "addresses", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_composite_array_values)

    print("domain_ssn_types:")
    expected_domain_ssn_values = expected.get("domain_ssn_types", [])
    tgt.assert_distinct_values_of_col("domain_types", "ssn", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_domain_ssn_values)
    expected_domain_email_values = expected.get("domain_email_types", [])
    tgt.assert_distinct_values_of_col("domain_types", "email", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_domain_email_values)
    expected_domain_rating_values = expected.get("domain_rating_types", [])
    tgt.assert_distinct_values_of_col("domain_types", "rating", "public",
                                      expected_distinct_values=expected_domain_rating_values)
    expected_domain_prefs_values = expected.get("domain_prefs_types", [])
    tgt.assert_distinct_values_of_col("domain_types", "prefs", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_domain_prefs_values)

    print("domain_ssn_array_types:")
    expected_domain_ssn_array_values = expected.get("domain_ssn_array_types", [])
    tgt.assert_distinct_values_of_col("domain_array_types", "ssn_list", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_domain_ssn_array_values)
    expected_domain_phone_array_values = expected.get("domain_phone_array_types", [])
    tgt.assert_distinct_values_of_col("domain_array_types", "phone_list", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_domain_phone_array_values)
    expected_domain_name_array_values = expected.get("domain_name_array_types", [])
    tgt.assert_distinct_values_of_col("domain_array_types", "name_list", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_domain_name_array_values)

    print("range_array_types:")
    expected_range_price_array_values = expected.get("range_price_array_types", [])
    tgt.assert_distinct_values_of_col("range_array_types", "price_ranges", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_range_price_array_values)
    expected_range_discount_array_values = expected.get("range_discount_array_types", [])
    tgt.assert_distinct_values_of_col("range_array_types", "discount_ranges", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_range_discount_array_values)

    print("extension_types:")
    expected_ext_hstore_values = expected.get("extension_hstore_types", [])
    tgt.assert_distinct_values_of_col("extension_types", "col_hstore", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_ext_hstore_values)
    expected_ext_citext_values = expected.get("extension_citext_types", [])
    tgt.assert_distinct_values_of_col("extension_types", "col_citext", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_ext_citext_values)
    # ltree type doesn't support DISTINCT, cast to text instead
    expected_ext_ltree_values = expected.get("extension_ltree_types", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT col_ltree::text FROM public.extension_types")
    actual_ltree_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_ltree_values: {actual_ltree_values}")
    for ltree_value in actual_ltree_values:
        print(f"{ltree_value}")
        assert ltree_value in expected_ext_ltree_values, f"Unexpected ltree value: {ltree_value}"

    print("extension_arrays:")
    expected_ext_array_hstore_values = expected.get("extension_hstore_array_types", [])
    tgt.assert_distinct_values_of_col("extension_arrays", "col_hstore", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_ext_array_hstore_values)
    expected_ext_array_citext_values = expected.get("extension_citext_array_types", [])
    tgt.assert_distinct_values_of_col("extension_arrays", "col_citext", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_ext_array_citext_values)
    # ltree array type doesn't support DISTINCT, cast to text instead
    expected_ext_array_ltree_values = expected.get("extension_ltree_array_types", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT col_ltree::text FROM public.extension_arrays")
    actual_ltree_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_ltree_array_values: {actual_ltree_array_values}")
    for ltree_array_value in actual_ltree_array_values:
        print(f"{ltree_array_value}")
        assert ltree_array_value in expected_ext_array_ltree_values, f"Unexpected ltree array value: {ltree_array_value}"

    print("audit_log:")
    expected_involved_employees_values = expected.get("audit_log_employees", [])
    tgt.assert_distinct_values_of_col("audit_log", "involved_employees", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_involved_employees_values)
    expected_affected_clients_values = expected.get("audit_log_clients", [])
    tgt.assert_distinct_values_of_col("audit_log", "affected_clients", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_affected_clients_values)
    # transaction_refs returns Python list format, not PostgreSQL array string format
    expected_transaction_refs_values = expected.get("audit_log_transaction_refs", [])
    actual_transaction_refs = tgt.get_distinct_values_of_column_of_table("audit_log", "transaction_refs", "public")
    print(f"actual_transaction_refs: {actual_transaction_refs}")
    for transaction_ref in actual_transaction_refs:
        print(f"{transaction_ref}")
        assert transaction_ref in expected_transaction_refs_values, f"Unexpected transaction_refs value: {transaction_ref}"

    print("numeric_types:")
    expected_numeric_types_real_values = expected.get("numeric_real_types", [])
    tgt.assert_distinct_values_of_col("numeric_types", "real_col", "public",
                                      expected_distinct_values=expected_numeric_types_real_values)
    expected_numeric_types_double_values = expected.get("numeric_double_types", [])
    tgt.assert_distinct_values_of_col("numeric_types", "double_col", "public",
                                      expected_distinct_values=expected_numeric_types_double_values)
    expected_numeric_types_small_serial_values = expected.get("numeric_small_serial_types", [])
    tgt.assert_distinct_values_of_col("numeric_types", "small_serial_col", "public",
                                      expected_distinct_values=expected_numeric_types_small_serial_values)
    expected_numeric_types_big_serial_values = expected.get("numeric_big_serial_types", [])
    tgt.assert_distinct_values_of_col("numeric_types", "big_serial_col", "public",
                                      expected_distinct_values=expected_numeric_types_big_serial_values)

    print("numeric_arrays:")
    expected_numeric_arrays_real_values = expected.get("numeric_real_arrays", [])
    tgt.assert_distinct_values_of_col("numeric_arrays", "real_col", "public",
                                      expected_distinct_values=expected_numeric_arrays_real_values)
    expected_numeric_arrays_double_values = expected.get("numeric_double_arrays", [])
    tgt.assert_distinct_values_of_col("numeric_arrays", "double_col", "public",
                                      expected_distinct_values=expected_numeric_arrays_double_values)

    print("datetime_types:")
    actual_timestamptz_values = tgt.get_distinct_values_of_column_of_table("datetime_types", "timestamptz_col", "public")
    assert len(actual_timestamptz_values) == 3, f"Expected 3 distinct timestamptz values, got {len(actual_timestamptz_values)}"
    expected_datetime_types_interval_values = expected.get("datetime_interval_types", [])
    tgt.assert_distinct_values_of_col("datetime_types", "interval_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_datetime_types_interval_values)
    
    print("datetime_arrays:")
    actual_timestamptz_arrays = tgt.get_distinct_values_of_column_of_table("datetime_arrays", "timestamptz_col", "public")
    assert len(actual_timestamptz_arrays) == 2, f"Expected 2 distinct timestamptz arrays, got {len(actual_timestamptz_arrays)}"
    expected_datetime_arrays_interval_values = expected.get("datetime_interval_arrays", [])
    tgt.assert_distinct_values_of_col("datetime_arrays", "interval_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_datetime_arrays_interval_values)
    
    print("geometry_arrays:")  
    expected_geometry_arrays_point_values = expected.get("geometry_point_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT point_col::text FROM public.geometry_arrays")
    actual_point_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_point_array_values: {actual_point_array_values}")
    for point_array_value in actual_point_array_values:
        print(f"{point_array_value}")
        assert point_array_value in expected_geometry_arrays_point_values, f"Unexpected point array value: {point_array_value}"

    expected_geometry_arrays_line_values = expected.get("geometry_line_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT line_col::text FROM public.geometry_arrays")
    actual_line_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_line_array_values: {actual_line_array_values}")
    for line_array_value in actual_line_array_values:
        print(f"{line_array_value}")
        assert line_array_value in expected_geometry_arrays_line_values, f"Unexpected line array value: {line_array_value}"

    expected_geometry_arrays_lseg_values = expected.get("geometry_lseg_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT lseg_col::text FROM public.geometry_arrays")
    actual_lseg_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_lseg_array_values: {actual_lseg_array_values}")
    for lseg_array_value in actual_lseg_array_values:
        print(f"{lseg_array_value}")
        assert lseg_array_value in expected_geometry_arrays_lseg_values, f"Unexpected lseg array value: {lseg_array_value}"

    expected_geometry_arrays_box_values = expected.get("geometry_box_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT box_col::text FROM public.geometry_arrays")
    actual_box_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_box_array_values: {actual_box_array_values}")
    for box_array_value in actual_box_array_values:
        print(f"{box_array_value}")
        assert box_array_value in expected_geometry_arrays_box_values, f"Unexpected box array value: {box_array_value}"

    expected_geometry_arrays_path_values = expected.get("geometry_path_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT path_col::text FROM public.geometry_arrays")
    actual_path_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_path_array_values: {actual_path_array_values}")
    for path_array_value in actual_path_array_values:
        print(f"{path_array_value}")
        assert path_array_value in expected_geometry_arrays_path_values, f"Unexpected path array value: {path_array_value}"

    expected_geometry_arrays_polygon_values = expected.get("geometry_polygon_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT polygon_col::text FROM public.geometry_arrays")
    actual_polygon_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_polygon_array_values: {actual_polygon_array_values}")
    for polygon_array_value in actual_polygon_array_values:
        print(f"{polygon_array_value}")
        assert polygon_array_value in expected_geometry_arrays_polygon_values, f"Unexpected polygon array value: {polygon_array_value}"

    expected_geometry_arrays_circle_values = expected.get("geometry_circle_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT circle_col::text FROM public.geometry_arrays")
    actual_circle_array_values = [str(value[0]) for value in cur.fetchall()]
    print(f"actual_circle_array_values: {actual_circle_array_values}")
    for circle_array_value in actual_circle_array_values:
        print(f"{circle_array_value}")
        assert circle_array_value in expected_geometry_arrays_circle_values, f"Unexpected circle array value: {circle_array_value}"

    print("network_types:")
    expected_network_types_cidr_values = expected.get("network_cidr_types", [])
    tgt.assert_distinct_values_of_col("network_types", "cidr_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_types_cidr_values)
    expected_network_types_inet_values = expected.get("network_inet_types", [])
    tgt.assert_distinct_values_of_col("network_types", "inet_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_types_inet_values)
    expected_network_types_macaddr_values = expected.get("network_macaddr_types", [])
    tgt.assert_distinct_values_of_col("network_types", "macaddr_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_types_macaddr_values)
    expected_network_types_macaddr8_values = expected.get("network_macaddr8_types", [])
    tgt.assert_distinct_values_of_col("network_types", "macaddr8_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_types_macaddr8_values)
    
    print("network_arrays:")
    expected_network_arrays_cidr_values = expected.get("network_cidr_arrays", [])
    tgt.assert_distinct_values_of_col("network_arrays", "cidr_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_arrays_cidr_values)
    expected_network_arrays_inet_values = expected.get("network_inet_arrays", [])
    tgt.assert_distinct_values_of_col("network_arrays", "inet_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_arrays_inet_values)
    expected_network_arrays_macaddr_values = expected.get("network_macaddr_arrays", [])
    tgt.assert_distinct_values_of_col("network_arrays", "macaddr_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_arrays_macaddr_values)
    expected_network_arrays_macaddr8_values = expected.get("network_macaddr8_arrays", [])
    tgt.assert_distinct_values_of_col("network_arrays", "macaddr8_col", "public",
                                      transform_func=str,
                                      expected_distinct_values=expected_network_arrays_macaddr8_values)

    print("misc_arrays:")
    expected_misc_arrays_pg_lsn_values = expected.get("misc_pg_lsn_arrays", [])
    tgt.assert_distinct_values_of_col("misc_arrays", "pg_lsn_col", "public",
                                      expected_distinct_values=expected_misc_arrays_pg_lsn_values)
    # txid_snapshot array type doesn't support DISTINCT, so we cast to text first
    expected_misc_arrays_txid_snapshot_values = expected.get("misc_txid_snapshot_arrays", [])
    cur = tgt.conn.cursor()
    cur.execute("SELECT DISTINCT txid_snapshot_col::text FROM public.misc_arrays")
    actual_txid_snapshot_array_values = [str(value[0]) for value in cur.fetchall()]
    for txid_snapshot_array_value in actual_txid_snapshot_array_values:
        print(f"{txid_snapshot_array_value}")
        assert txid_snapshot_array_value in expected_misc_arrays_txid_snapshot_values, f"Unexpected txid_snapshot array value: {txid_snapshot_array_value}"

#=============================================================================

def main():
    test_type_flags = common.valparser()

    if test_type_flags['ff_enabled'] == 'true':
        expected = build_expected_values(ff_fb_enabled=True)
        run_migration_checks("yb", expected, ff_fb_enabled=True)
        run_migration_checks("source_replica", expected, ff_fb_enabled=True)

    elif test_type_flags['fb_enabled'] == 'true':
        expected = build_expected_values(ff_fb_enabled=True)
        run_migration_checks("yb", expected, ff_fb_enabled=True)
        run_migration_checks("source", expected, ff_fb_enabled=True)

    else:
        expected = build_expected_values(ff_fb_enabled=False)
        run_migration_checks("yb", expected, ff_fb_enabled=False)

#=============================================================================

if __name__ == "__main__":
	main()
