#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_EXTENSION_SET = set([("hstore",), ("pg_stat_statements",), ("plpgsql",)])

EXPECTED_INDEX_COUNT = {
	'osm_changeset': 5,
}

def migration_completed_checks(tgt):

	extension_list = tgt.fetch_all_pg_extension("public")
	print(f"extension_list: {extension_list}\n EXPECTED_EXTENSION_SET: {EXPECTED_EXTENSION_SET}")
	assert extension_list == EXPECTED_EXTENSION_SET

	table_list = tgt.get_table_names("public")
	print("table_list:", table_list)
	assert len(table_list) == 3

	get_index_cnt = tgt.get_count_index_on_table("public")
	for table_name, index_count in EXPECTED_INDEX_COUNT.items():
		print(f"table_name: {table_name}, index_count: {get_index_cnt[table_name]}")
		assert index_count == get_index_cnt[table_name]
	
	fetched_procedures_functions = tgt.fetch_all_procedures("public")
	print(f"count of fecthed procedures/functions - {len(fetched_procedures_functions)}")
	tgtVersion = tgt.get_target_version()
	print(f"target version: {tgtVersion}")
	
	# for PG15 merged versions (preview >= 2.25 or stable >= 2025.1), some extensions create more functions/procedures than in earlier versions.
	# Example hstore
	# 2024.2: 57 functions / procedures
	# 2.25+: 60 functions / procedures
	# Thus the change in count.

	if yb.has_pg15_merge(tgtVersion):
		assert len(fetched_procedures_functions) == 61
	else:
		assert len(fetched_procedures_functions) == 58


if __name__ == "__main__":
	main()
