#!/usr/bin/env python3

import yb


def main():
	yb.run_checks(migration_completed_checks)


# =============================================================================

EXPECTED_ROW_COUNT = {
	'members': 998
}

EXPECTED_INDEX_COUNT = {
	'members': 4
}


def migration_completed_checks(tgt):
	table_list = tgt.get_table_names("public")
	print("table_list:", table_list)
	assert len(table_list) == 1

	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	get_index_cnt = tgt.get_count_index_on_table("public")
	for table_name, index_count in EXPECTED_INDEX_COUNT.items():
		print(f"table_name: {table_name}, index_count: {get_index_cnt[table_name]}")
		assert index_count == get_index_cnt[table_name]

    UNIQUE_INDEX_CHECK = "INSERT INTO members (member_id, first_name, last_name, gender, email, dob) VALUES (1001, 'Pepi', 'Elce', 'F', 'pelce0@trellian.com', DATE '1984-03-04');"
    chk_err_default_constraint = tgt.run_query_and_chk_error(UNIQUE_INDEX_CHECK, 23505)
    assert chk_err_default_constraint == True

if __name__ == "__main__":
	main()