#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_ROW_COUNT = {
 	'bit_types': 4,   
	'bool_types': 6,  
	'date_time_types': 10, 
	'enum_types': 3,   
	'fixed_point_types': 3,
	'floating_point_types': 4, 
  	'int_types': 4,     
 	'json_types': 5,          
 	'string_types': 1,        
	'uuid_try': 3 
}

EXPECTED_SUM_OF_COLUMN = {
	'fixed_point_types': {
		'dec_type': '0.44566',
		'numeric_type': '37192.93689',
		'fixed_type': '26554.360',
		'd_us': '1277234.27'
	},
	'floating_point_types': {
		'double_type': '0.3477833',
		'id': '10',
		'real_type': '4.7999',
		'float_type': '123582.612'
	},
	'int_types': {
		'mint_u': '25165822',
		'iint_u': '4294967294',
		'sint_s': '65532',
		'iinteger_s': '-2',
		'iint_s': '-2',
		'sint_u': '65534',
		'tint_s': '-2',
		'bint_s': '-2',
		'iinteger_u':'4294967294',
		'bint_u': '18446744073709551614',
		'tint_u': '510',
		'mint_s': '-2'
	},
}

EXPECTED_ENUM_VALUES = ['low', 'high', 'med']

EXPECTED_DATA_TYPES = {
	'floating_point_types': {'double_type': 'double precision', 'real_type': 'double precision', 'id': 'bigint', 'float_type': 'double precision'},
 	'fixed_point_types': {'d_us': 'numeric', 'fixed_type': 'numeric', 'numeric_type': 'numeric', 'dec_type': 'numeric'}, 
  	'string_types': {'text_item': 'text', 'varchar_item': 'character varying', 'char_item': 'character', 'varbinary_item': 'bytea', 'longtext_item': 'text', 'binary_item': 'bytea', 'mediumtext_item': 'text'}, 
   	'date_time_types': {'date_time_type': 'timestamp without time zone', 'time_stamp_type': 'timestamp without time zone', 'date_type': 'timestamp without time zone', 'year_type': 'smallint', 'time_type': 'time without time zone'}, 
    'json_types': {'json_val': 'json'}, 
    'int_types': {'iint_u': 'bigint', 'mint_u': 'integer', 'tint_s': 'smallint', 'sint_u': 'integer', 'iint_s': 'bigint', 'iinteger_s': 'bigint', 'sint_s': 'integer', 'tint_u': 'smallint', 'bint_u': 'numeric', 'iinteger_u': 'bigint', 'bint_s': 'bigint', 'mint_s': 'integer'}, 
    'bool_types': {'val': 'smallint', 'id': 'bigint'}, 
    'enum_types': {'title': 'character varying', 'priority': 'USER-DEFINED', 'id': 'bigint'}, 
    'uuid_try': {'name': 'character varying', 'id': 'bytea'}, 
    'bit_types': {'bit_type': 'bit varying'} 
}

def migration_completed_checks(tgt):
	table_list = tgt.get_table_names("public")
	print("table_list:", table_list)
	assert len(table_list) == 10

	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	for table_name, column_names_with_sum in EXPECTED_SUM_OF_COLUMN.items():
		print(f"table_name: {table_name} ---- ")
		for column, sum in column_names_with_sum.items():
			col_sum = tgt.get_sum_of_column_of_table(table_name, column, "public")
			print(f"column_name: {column}, sum: {col_sum}")
			assert sum == str(col_sum)

	distinct_values_enum_types = tgt.get_distinct_values__of_column_of_table("enum_types", "priority", "public")
	print(f"distinct_enum_values:")
	for distinct_value in distinct_values_enum_types:
		print(f"{distinct_value}")
		assert distinct_value.lower() in EXPECTED_ENUM_VALUES

	distinct_values_bool_types = tgt.get_distinct_values__of_column_of_table("bool_types", "val", "public")
	print(f"distinct_bool_values:")
	for distinct_value in distinct_values_bool_types:
		print(f"{distinct_value}")
		assert distinct_value == 0 or distinct_value == 1
	
	fetched_datatypes_schema = tgt.fetch_datatypes_and_columns_of_all_tables_in_schema("public")
 
	print(fetched_datatypes_schema)
	for table_name, columns in fetched_datatypes_schema.items():
		print(f"table_name: {table_name} ---- ")
		for column_name, datatype in columns.items():
			print(f"column_name: {column_name}, datatype: {datatype}")
			assert datatype == EXPECTED_DATA_TYPES[table_name][column_name]

if __name__ == "__main__":
	main() 