# We use an already deployed RDS Oracle instance on docker for testing.

export SOURCE_DB_PORT=${SOURCE_DB_PORT:-1521}
export SOURCE_DB_USER=${SOURCE_DB_USER:-"ybvoyager"}
export SOURCE_DB_PASSWORD=${SOURCE_DB_PASSWORD:-"password"}
export SOURCE_DB_NAME=${SOURCE_DB_NAME:-"ORCLPDB1"}
export SOURCE_DB_HOST=${SOURCE_DB_HOST:-"localhost"}
export SOURCE_DB_USER_SCHEMA_OWNER=${SOURCE_DB_USER_SCHEMA_OWNER:-"TEST_SCHEMA"}
export SOURCE_DB_USER_SCHEMA_OWNER_PASSWORD=${SOURCE_DB_USER_SCHEMA_OWNER_PASSWORD:-"password"}
export SOURCE_DB_USER_SYS=${SOURCE_DB_USER_SYS:-"SYS"}
export SOURCE_DB_USER_SYS_PASSWORD=${SOURCE_DB_USER_SYS_PASSWORD:-"password"}
