export SOURCE_REPLICA_DB_NAME=${SOURCE_REPLICA_DB_NAME:-"ORCLPDB1"}
export SOURCE_REPLICA_DB_HOST=${SOURCE_REPLICA_DB_HOST:-"localhost"}
export SOURCE_REPLICA_DB_USER=${SOURCE_REPLICA_DB_USER:-"YBVOYAGER_FF"}
export SOURCE_REPLICA_DB_PASSWORD=${SOURCE_REPLICA_DB_PASSWORD:-"password"}
export SOURCE_REPLICA_DB_SCHEMA=${SOURCE_REPLICA_DB_SCHEMA:-"FF_SCHEMA"}