export FF_DB_NAME=${FF_DB_NAME:-"ORCLPDB1"}
export FF_DB_HOST=${FF_DB_HOST:-"localhost"}
export FF_DB_USER=${FF_DB_USER:-"YBVOYAGER_FF"}
export FF_DB_PASSWORD=${FF_DB_PASSWORD:-"password"}
export FF_DB_SCHEMA=${FF_DB_SCHEMA:-"FF_SCHEMA"}