CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ORCLCDB/logminer_tbs.dbf'
    SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE USER c##ybvoyager IDENTIFIED BY password
    DEFAULT TABLESPACE logminer_tbs
    QUOTA UNLIMITED ON logminer_tbs
    CONTAINER=ALL;

  GRANT CREATE SESSION TO c##ybvoyager CONTAINER=ALL; 
  GRANT SET CONTAINER TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$DATABASE to c##ybvoyager CONTAINER=ALL; 
  GRANT FLASHBACK ANY TABLE TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ANY TABLE TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT_CATALOG_ROLE TO c##ybvoyager CONTAINER=ALL; 
  GRANT EXECUTE_CATALOG_ROLE TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ANY TRANSACTION TO c##ybvoyager CONTAINER=ALL; 
  GRANT LOGMINING TO c##ybvoyager CONTAINER=ALL; 

  GRANT CREATE TABLE TO c##ybvoyager CONTAINER=ALL; 
  GRANT LOCK ANY TABLE TO c##ybvoyager CONTAINER=ALL; 
  GRANT CREATE SEQUENCE TO c##ybvoyager CONTAINER=ALL; 

  GRANT EXECUTE ON DBMS_LOGMNR TO c##ybvoyager CONTAINER=ALL; 
  GRANT EXECUTE ON DBMS_LOGMNR_D TO c##ybvoyager CONTAINER=ALL; 

  GRANT SELECT ON V_$LOG TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$LOG_HISTORY TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$LOGMNR_LOGS TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$LOGFILE TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$ARCHIVED_LOG TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$TRANSACTION TO c##ybvoyager CONTAINER=ALL; 

  GRANT SELECT ON V_$MYSTAT TO c##ybvoyager CONTAINER=ALL; 
  GRANT SELECT ON V_$STATNAME TO c##ybvoyager CONTAINER=ALL; 

  ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
  ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;