export SOURCE_DB_HOST=${SOURCE_DB_HOST:-"localhost"}
export SOURCE_DB_PORT=${SOURCE_DB_PORT:-3306}
export SOURCE_DB_USER=${SOURCE_DB_USER:-"ybvoyager"}
export SOURCE_DB_PASSWORD=${SOURCE_DB_PASSWORD:-"Password#123"}
