export SOURCE_DB_HOST=${SOURCE_DB_HOST:-"127.0.0.1"}
export SOURCE_DB_PORT=${SOURCE_DB_PORT:-3306}
export SOURCE_DB_USER=${SOURCE_DB_USER:-"root"}
export SOURCE_DB_PASSWORD=${SOURCE_DB_PASSWORD:-"root"}
export NO_DATA_SCHEMA=${NO_DATA_SCHEMA:-false}
