#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(file_import_done_checks)

def file_import_done_checks(tgt):
	row_count = tgt.get_row_count("txt_table")
	print(f"row_count: {row_count}")
	assert row_count == 60

if __name__ == "__main__":
	main()