#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

run_psql "${SOURCE_DB_NAME}" "\i pg_basic_assessment_report_test.sql"

echo "End of init-db script"