#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."
psql_import_file ${SOURCE_DB_NAME} partitionTables.sql

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM sales_region"
