#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

for schema in TEST_SCHEMA TEST_SCHEMA2; do
    export SOURCE_DB_SCHEMA=${schema}
    run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TESTS_DIR}/oracle/utils/delete_full_schema
done