export SOURCE_DB_TYPE="oracle"
export SOURCE_DB_SCHEMA1=${SOURCE_DB_SCHEMA1:-"TEST_SCHEMA"}
export SOURCE_DB_SCHEMA2=${SOURCE_DB_SCHEMA2:-"TEST_SCHEMA2"}
export SOURCE_DB_ORACLE_TNS_ALIAS=${SOURCE_DB_ORACLE_TNS_ALIAS:-"ORCLPDB1SSL"}