#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Deleting existing data in source database"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TESTS_DIR}/oracle/utils/delete_full_schema

echo "Initialising source database 1 & inserting data"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../assessment-report-test/oracle_assessment_report.sql

echo "Initialising source database 2 & inserting data"

cat > create-schema2.sql << EOF
		CREATE USER TEST_SCHEMA2 identified by "password";
        GRANT ALL PRIVILEGES TO TEST_SCHEMA2;
EOF
	run_sqlplus_as_sys ${SOURCE_DB_NAME} "create-schema2.sql"

export SOURCE_DB_USER_SCHEMA_OWNER="TEST_SCHEMA2"

run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../partitions/partition_schema.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../partitions/partition_data.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../misc-tests/schema.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../views-mviews/views_schema_data.sql
