#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

export SOURCE_DB_SCHEMA="TEST_SCHEMA"

create_source_db ${SOURCE_DB_SCHEMA}

./cleanup-db

echo "Initialising source database 1 & inserting data"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../assessment-report-test/oracle_assessment_report.sql

echo "Initialising source database 2 & inserting data"

export SOURCE_DB_SCHEMA="TEST_SCHEMA2"

create_source_db ${SOURCE_DB_SCHEMA}

run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../partitions/partition_schema.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../partitions/partition_data.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../misc-tests/schema.sql
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TEST_DIR}/../views-mviews/views_schema_data.sql
