version: 1
name: live-migration-basic
run_id: lm_${DATE}_${RANDOM}

env:
  LOG_LEVEL: info
  MAX_QUEUE_SEGMENT_BYTES: 400

export_dir: /var/lib/voyager/export-dir
artifacts_dir: /var/lib/voyager/artifacts/${run_id}

source:
  type: postgresql
  host: 127.0.0.1
  port: 5432
  database: sakila
  user: postgres
  password: postgres

target:
  type: yugabytedb
  host: 127.0.0.1
  port: 5433
  database: idx
  user: ybvoyager
  password: ybvoyager

voyager:
  # Additional flags
  export_data:
    flags:
      export-type: snapshot-and-changes
      disable-pb: true
  import_data:
    flags:
      disable-pb: true
      max-retries-streaming: 15
      enable-adaptive-parallelism: true
  cutover_to_target:
    flags:
      prepare-for-fall-back: false
      use-yb-grpc-connector: false
  export_from_target:
    flags:
      disable-pb: true
  import_to_source_or_replica:
    flags:
      disable-pb: true
      max-retries-streaming: 15

generator:
  # Inline event generator configuration (single source of truth)
  config:
    connection:
      host: 127.0.0.1
      port: 5432
      database: sakila
      user: postgres
      password: postgres
    generator:
      schema_name: public
      manual_table_list: []
      exclude_table_list: []
      num_iterations: -1
      wait_after_operations: 0
      wait_duration_seconds: 0
      table_weights: {}
      operation_weights: { INSERT: 3, UPDATE: 2, DELETE: 1 }
      random_seed: 12345
      faker_seed: 12345
      insert_rows: 4
      update_rows: 2
      delete_rows: 1
      insert_max_retries: 50
      update_max_retries: 3

  # Fallback: use existing on-disk generator config
  # config_path: /home/ubuntu/yb-voyager/migtests/scripts/event-generator/event-generator.yaml
  
dvt:
  enabled: true
  mode: counts_then_sampled_rows

stages:
  # 1) Create source schema
  - name: create_source_schema
    action: run_sql
    sql_path: /opt/tests/init-db.sql

  # 2) Schema Migration
  - name: export_schema_from_source
    action: voyager_export_schema

  - name: import_schema_on_target
    action: voyager_import_schema

  # 3) Load snapshot on source (baseline rows)
  - name: load_snapshot_on_source
    action: run_sql
    sql_path: /opt/tests/seed-snapshot.sql

  # 4) Start event generator (all events mode)
  - name: start_event_generator
    action: generator_start

  # 5) Start export-data and import-data
  - name: start_exporter
    action: voyager_export_start
  - name: start_importer
    action: voyager_import_start

  # 6) Begin resumptions on import side (during snapshot ingestion)
  - name: start_import_resumptions
    action: start_resumptions   # orchestrator will call start_resumptions_for_stage
    resumption:
      import_data:
        max_restarts: 25
        min_interrupt_seconds: 20
        max_interrupt_seconds: 45
        min_restart_wait_seconds: 15
        max_restart_wait_seconds: 30

  # 7) Wait for exporter to reach streaming (CDC)
  - name: wait_exporter_streaming
    action: wait_for
    condition: exporter_in_streaming_phase

  # 8) Start resumptions on export side (during CDC)
  - name: start_export_resumptions
    action: start_resumptions   # orchestrator will call start_resumptions_for_stage
    resumption:
      export_data:
        max_restarts: 10
        min_interrupt_seconds: 30
        max_interrupt_seconds: 60
        min_restart_wait_seconds: 20
        max_restart_wait_seconds: 40

  # 9) Stop event generator
  - name: stop_event_generator
    action: generator_stop
    graceful_timeout_sec: 60

  # 10) Let exporter backlog drain to zero
  - name: insert_backlog_marker
    action: run_sql
    target: source
    sql_path: /opt/tests/insert-marker.sql

  - name: wait_backlog_zero
    action: wait_for
    condition: remaining_events_eq_0
    timeout_sec: 3600

  # 11) Initiate cutover
  - name: cutover_to_target
    action: voyager_cutover

  # 12b) Wait for cutover completion
  - name: wait_cutover_completed
    action: wait_for
    condition: cutover_to_target_status_completed
    timeout_sec: 1800

  # 13) Validate source vs target
  - name: validate
    action: dvt_run

  # 14) Cleanup
  - name: cleanup_source_cutover_table
    action: run_sql
    sql_path: /opt/tests/cleanup.sql


