#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i pg_misc_objects2.sql;"

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM ext_test;"
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM foo;"
