#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Creating ${SOURCE_DB_NAME} database on source"
run_psql postgres "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_psql postgres "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Creating ${SOURCE_DB_NAME} database on target"
run_ysql yugabyte "DROP DATABASE IF EXISTS ${SOURCE_DB_NAME};"
run_ysql yugabyte "CREATE DATABASE ${SOURCE_DB_NAME};"

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i ../../pg/datatypes/pg_datatypes_schema.sql;"
run_psql ${SOURCE_DB_NAME} "\i ../../pg/datatypes/pg_datatypes_data.sql;"

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM num_types;"