export SOURCE_DB_TYPE="oracle"
export SOURCE_DB_SCHEMA=${SOURCE_DB_SCHEMA:-"TEST_SCHEMA"}
export TARGET_DB_NAME=${TARGET_DB_NAME:-"live_test"}
export TARGET_DB_SCHEMA=${TARGET_DB_SCHEMA:-"test_schema"}
