#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Assigning permissions to the validate files"
chmod +x ${TEST_DIR}/validate
chmod +x ${TEST_DIR}/validateAfterChanges

echo "Deleting existing data in source and FF database"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${TESTS_DIR}/oracle/utils/delete_full_schema
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${FF_DB_SCHEMA} ${FF_DB_PASSWORD} ${TESTS_DIR}/oracle/utils/delete_full_schema

echo "Initialising source database & inserting data"
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${SOURCE_DB_SCHEMA} ${SOURCE_DB_PASSWORD} snapshot_schema
run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${SOURCE_DB_SCHEMA} ${SOURCE_DB_PASSWORD} snapshot_data

if [ "${FF_DB_SCHEMA}" != "" ]
then
	run_sqlplus_as_schema_owner ${SOURCE_DB_NAME} ${FF_DB_SCHEMA} ${FF_DB_PASSWORD} snapshot_schema
fi