#!/usr/bin/env python3

import os
import yb
import collections
import oracle

def main():
	migration_completed_checks_yb()
	if os.environ.get("FF_DB_SCHEMA") is not None:
		migration_completed_checks_oracle()

EXPECTED_ROW_COUNT = {
	'x':5
}

EXPECTED_SUM_OF_COLUMN = {
	'x': {
		'id': '18',
		'id2': '43'
	}
}

if os.environ.get("FF_DB_SCHEMA") is not None:

	EXPECTED_ROW_COUNT = {
		'x':7
	}

	EXPECTED_SUM_OF_COLUMN = {
		'x': {
			'id': '133',
			'id2': '53'
		}
	}

def migration_completed_checks_yb():
	print("Running tests on YB")
	global db_schema
	db_schema="public"
	yb.run_checks(migration_completed_checks)

def migration_completed_checks_oracle():
	print("Running tests on Oracle")
	global db_schema
	db_schema = os.environ.get("FF_DB_SCHEMA")
	oracle.run_checks(migration_completed_checks)

def migration_completed_checks(tgt):
	# Validation to check for matching row counts
	got_row_count = tgt.row_count_of_all_tables(db_schema)
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	for table_name, column_names_with_sum in EXPECTED_SUM_OF_COLUMN.items():
		print(f"table_name: {db_schema}.{table_name} ---- ")
		for column, sum in column_names_with_sum.items():
			col_sum = tgt.get_sum_of_column_of_table(table_name, column, db_schema)
			print(f"column_name: {column}, sum: {col_sum}")
			assert sum == str(col_sum)

if __name__ == "__main__":
	main()