#!/usr/bin/env python3

import common
import os
import yb
import collections
import oracle

def main():
	test_type_flags = common.valparser()
	
	migration_completed_checks_yb()

	if test_type_flags['ff_enabled'] == 'true':
		migration_completed_checks_ff()

EXPECTED_ROW_COUNT = {
	'x':3,
	'user_table': 8,
	'date_time_types': 4,
}

EXPECTED_SUM_OF_COLUMN = {
	'x': {
		'id': '6',
		'id2': '9'
	},
	'user_table': {
		'id': '36',
	},
	'date_time_types': {
		'id': '10',
	}
}

def migration_completed_checks_yb():
	print("Running tests on YB")
	global db_schema
	db_schema="test_schema"
	yb.run_checks(migration_completed_checks)
	yb.run_checks(YB_specific_checks)

def YB_specific_checks(tgt):
	yb.verify_colocation(tgt, "oracle")

def migration_completed_checks_ff():
	print("Running tests on Oracle source replica")
	global db_schema
	db_schema = os.environ.get("SOURCE_REPLICA_DB_SCHEMA")
	oracle.run_checks(migration_completed_checks, db_type="source_replica")

def migration_completed_checks(tgt):
	# Validation to check for matching row counts
	got_row_count = tgt.row_count_of_all_tables(db_schema)
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	for table_name, column_names_with_sum in EXPECTED_SUM_OF_COLUMN.items():
		print(f"table_name: {db_schema}.{table_name} ---- ")
		for column, sum in column_names_with_sum.items():
			col_sum = tgt.get_sum_of_column_of_table(table_name, column, db_schema)
			print(f"column_name: {column}, sum: {col_sum}")
			assert sum == str(col_sum)

if __name__ == "__main__":
	main()