//go:build integration

/*
Copyright (c) YugabyteDB, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package srcdb

import (
	"fmt"
	"slices"
	"testing"

	"github.com/samber/lo"
	"github.com/stretchr/testify/require"
	"gotest.tools/assert"

	"github.com/yugabyte/yb-voyager/yb-voyager/src/utils"
	"github.com/yugabyte/yb-voyager/yb-voyager/src/utils/sqlname"
	testutils "github.com/yugabyte/yb-voyager/yb-voyager/test/utils"
)

func TestPostgresGetAllTableNames(t *testing.T) {
	testPostgresSource.TestContainer.ExecuteSqls(
		`CREATE SCHEMA test_schema;`,
		`CREATE TABLE test_schema.foo (
		id INT PRIMARY KEY,
		name VARCHAR
	);`,
		`INSERT into test_schema.foo values (1, 'abc'), (2, 'xyz');`,
		`CREATE TABLE test_schema.bar (
		id INT PRIMARY KEY,
		name VARCHAR
	);`,
		`INSERT into test_schema.bar values (1, 'abc'), (2, 'xyz');`,
		`CREATE TABLE test_schema.non_pk1(
		id INT,
		name VARCHAR(255)
	);`)
	defer testPostgresSource.TestContainer.ExecuteSqls(`DROP SCHEMA test_schema CASCADE;`)

	sqlname.SourceDBType = "postgresql"
	testPostgresSource.Source.Schemas = []sqlname.Identifier{sqlname.NewIdentifier("postgresql", "test_schema")} // used in query of GetAllTableNames()

	// Test GetAllTableNames
	_ = testPostgresSource.DB().Connect()
	actualTables := testPostgresSource.DB().GetAllTableNames()
	expectedTables := []*sqlname.SourceName{
		sqlname.NewSourceName("test_schema", "foo"),
		sqlname.NewSourceName("test_schema", "bar"),
		sqlname.NewSourceName("test_schema", "non_pk1"),
	}
	assert.Equal(t, len(expectedTables), len(actualTables), "Expected number of tables to match")
	testutils.AssertEqualSourceNameSlices(t, expectedTables, actualTables)
}

func TestPostgresGetColumnsWithSupportedTypes_TimetzExcluded(t *testing.T) {
	testPostgresSource.TestContainer.ExecuteSqls(
		`CREATE SCHEMA test_schema;`,
		`CREATE TABLE test_schema.timetz_table (
			id INT PRIMARY KEY,
			reminder_at TIMETZ
		);`,
	)
	defer testPostgresSource.TestContainer.ExecuteSqls(`DROP SCHEMA test_schema CASCADE;`)

	sqlname.SourceDBType = "postgresql"
	tableList := []sqlname.NameTuple{
		testutils.CreateNameTupleWithSourceName("test_schema.timetz_table", "test_schema", testPostgresSource.DBType),
	}

	_ = testPostgresSource.DB().Connect()
	defer testPostgresSource.DB().Disconnect()

	pgDB := testPostgresSource.DB().(*PostgreSQL)
	supportedCols, unsupportedCols, err := pgDB.GetColumnsWithSupportedTypes(tableList, true, true)
	assert.NilError(t, err, "Expected no error")

	supported, exists := supportedCols.Get(tableList[0])
	assert.Equal(t, true, exists, "Expected test_schema.timetz_table in supported map")
	testutils.AssertEqualStringSlices(t, []string{"id"}, supported)

	unsupported, exists := unsupportedCols.Get(tableList[0])
	assert.Equal(t, true, exists, "Expected test_schema.timetz_table in unsupported map")
	testutils.AssertEqualStringSlices(t, []string{"reminder_at"}, unsupported)
}

func TestPGGetColumnToSequenceMap(t *testing.T) {

	testPostgresSource.TestContainer.ExecuteSqls(
		`CREATE SCHEMA IF NOT EXISTS public;`,

		`CREATE SCHEMA IF NOT EXISTS custom_schema;`,

		//-- 1. SERIAL column (implicit)
		`CREATE TABLE public.serial_table (
			id SERIAL PRIMARY KEY,
			name TEXT
		);`,

		//-- 2. BIGSERIAL column
		`CREATE TABLE public.bigserial_table (
			id BIGSERIAL PRIMARY KEY,
			description TEXT
		);`,

		//-- 3. IDENTITY columns (Generated Always)
		`CREATE TABLE public.identity_always_table (
			id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			info TEXT
		);`,

		//-- 4. IDENTITY columns (Generated By Default)
		`CREATE TABLE public.identity_default_table (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			comments TEXT
		);`,

		//-- 5. DEFAULT nextval() with a manually created seq
		`CREATE SEQUENCE public.manual_seq START 1000;`,

		`CREATE TABLE public.default_nextval_table (
			id BIGINT NOT NULL DEFAULT nextval('public.manual_seq'),
			value TEXT
		);`,

		//-- 6. Same as above but cross-schema
		`CREATE SEQUENCE custom_schema.cross_schema_seq;`,

		`CREATE TABLE public.cross_schema_default_seq_table (
			id BIGINT NOT NULL DEFAULT nextval('custom_schema.cross_schema_seq'),
			payload TEXT
		);`,

		//-- 7. A table with a manually owned by sequence (DEFAULT)
		`CREATE SEQUENCE public.manual_linked_seq;`,

		`CREATE TABLE public.manual_linked_table (
			id BIGINT NOT NULL,
			meta TEXT
		);`,
		`ALTER TABLE public.manual_linked_table ALTER COLUMN id SET DEFAULT nextval('public.manual_linked_seq');`,
		`ALTER SEQUENCE public.manual_linked_seq OWNED BY  public.manual_linked_table.id;`,

		//--8 table with manually owned sequence on text column
		`CREATE SEQUENCE custom_schema.user_code_seq
		START WITH 1
		INCREMENT BY 1;`,

		`CREATE OR REPLACE FUNCTION generate_user_code() RETURNS TEXT AS $$
		DECLARE
			new_code TEXT;
		BEGIN
			SELECT 'USR' || LPAD(nextval('custom_schema.user_code_seq')::TEXT, 4, '0') 
			INTO new_code;
			RETURN new_code;
		END;
		$$ LANGUAGE plpgsql;

		CREATE TABLE custom_schema.users (
			user_id int PRIMARY KEY,
			user_code TEXT UNIQUE,
			name TEXT
		);`,

		`ALTER TABLE ONLY custom_schema.users ALTER COLUMN user_code SET DEFAULT generate_user_code();`,

		`ALTER SEQUENCE custom_schema.user_code_seq OWNED BY custom_schema.users.user_code;`,

		//--9 normal sequences not attached to tables
		`CREATE SEQUENCE seq1_unattached;`,
		`CREATE SEQUENCE custom_schema.seq2_unattached;`,

		//--10 manually linked sequence to multiple columns
		`CREATE SEQUENCE public.manual_linked_seq_another ;`,

		`CREATE TABLE public.manual_linked_table_1 (
			id BIGINT NOT NULL,
			meta TEXT
		);`,
		`ALTER TABLE public.manual_linked_table_1 ALTER COLUMN id SET DEFAULT nextval('public.manual_linked_seq_another');`,

		`CREATE TABLE public.manual_linked_table_2 (
			id BIGINT NOT NULL,
			meta TEXT
		);`,
		`ALTER TABLE public.manual_linked_table_2 ALTER COLUMN id SET DEFAULT nextval('public.manual_linked_seq_another');`,
	)
	defer testPostgresSource.TestContainer.ExecuteSqls(
		`DROP TABLE  public.serial_table;`,
		`DROP TABLE  public.bigserial_table;`,
		`DROP TABLE  public.identity_always_table;`,
		`DROP TABLE  public.identity_default_table;`,
		`DROP TABLE  public.default_nextval_table;`,
		`DROP TABLE  public.cross_schema_default_seq_table;`,
		`DROP TABLE  public.manual_linked_table;`,
		`DROP TABLE  public.manual_linked_table_1;`,
		`DROP TABLE  public.manual_linked_table_2;`,
		`DROP SEQUENCE IF EXISTS public.manual_linked_seq_another;`,
		`DROP TABLE  custom_schema.users;`,
		`DROP SEQUENCE  public.seq1_unattached;`,
		`DROP SEQUENCE IF EXISTS custom_schema.user_code_seq;`,
		`DROP FUNCTION generate_user_code;`,
		`DROP SEQUENCE manual_seq;`,
		`DROP SCHEMA custom_schema CASCADE;`)

	sqlname.SourceDBType = "postgresql"
	tableList := []sqlname.NameTuple{
		testutils.CreateNameTupleWithSourceName("public.serial_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.bigserial_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.identity_always_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.identity_default_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.default_nextval_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.cross_schema_default_seq_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.manual_linked_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("custom_schema.users", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.manual_linked_table_1", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.manual_linked_table_2", "public", testPostgresSource.DBType),
	}
	testPostgresSource.Source.Schemas = sqlname.ParseIdentifiersFromString("postgresql", "public|custom_schema", "|")

	// Test GetColumnToSequenceMap
	_ = testPostgresSource.DB().Connect()
	defer testPostgresSource.DB().Disconnect()

	fmt.Print("----- Full table list case ----- \n")
	actualColumnToSequenceMap := testPostgresSource.DB().GetColumnToSequenceMap(tableList)
	expectedColumnToSequenceMap := map[string]string{
		"public.serial_table.id":                   `"public"."serial_table_id_seq"`,
		"public.bigserial_table.id":                `"public"."bigserial_table_id_seq"`,
		"public.identity_always_table.id":          `"public"."identity_always_table_id_seq"`,
		"public.identity_default_table.id":         `"public"."identity_default_table_id_seq"`,
		"public.default_nextval_table.id":          `"public"."manual_seq"`,
		"public.cross_schema_default_seq_table.id": `"custom_schema"."cross_schema_seq"`,
		"public.manual_linked_table.id":            `"public"."manual_linked_seq"`,
		"custom_schema.users.user_code":            `"custom_schema"."user_code_seq"`,
		"public.manual_linked_table_1.id":          `"public"."manual_linked_seq_another"`,
		"public.manual_linked_table_2.id":          `"public"."manual_linked_seq_another"`,
	}
	assert.Equal(t, len(lo.Keys(actualColumnToSequenceMap)), len(lo.Keys(expectedColumnToSequenceMap)), "Expected number of tables to match")
	//asssert key val
	for key, val := range actualColumnToSequenceMap {
		expectedVal, ok := expectedColumnToSequenceMap[key]
		assert.Equal(t, ok, true)
		assert.Equal(t, expectedVal, val)
	}
	fmt.Print("Full table list case completed!\n")

	//case with less tables
	tableList = []sqlname.NameTuple{
		testutils.CreateNameTupleWithSourceName("public.serial_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.bigserial_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.identity_always_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.cross_schema_default_seq_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.manual_linked_table", "public", testPostgresSource.DBType),
		testutils.CreateNameTupleWithSourceName("public.manual_linked_table_1", "public", testPostgresSource.DBType),
	}
	testPostgresSource.Source.Schemas = sqlname.ParseIdentifiersFromString("postgresql", "public|custom_schema", "|")

	// Test GetColumnToSequenceMap

	fmt.Print("----- Subset of table list case ----- \n")
	actualColumnToSequenceMap = testPostgresSource.DB().GetColumnToSequenceMap(tableList)
	expectedColumnToSequenceMap = map[string]string{
		"public.serial_table.id":                   `"public"."serial_table_id_seq"`,
		"public.bigserial_table.id":                `"public"."bigserial_table_id_seq"`,
		"public.identity_always_table.id":          `"public"."identity_always_table_id_seq"`,
		"public.cross_schema_default_seq_table.id": `"custom_schema"."cross_schema_seq"`,
		"public.manual_linked_table.id":            `"public"."manual_linked_seq"`,
		"public.manual_linked_table_1.id":          `"public"."manual_linked_seq_another"`,
	}
	assert.Equal(t, len(lo.Keys(actualColumnToSequenceMap)), len(lo.Keys(expectedColumnToSequenceMap)), "Expected number of tables to match")
	//asssert key val
	for key, val := range actualColumnToSequenceMap {
		expectedVal, ok := expectedColumnToSequenceMap[key]
		assert.Equal(t, ok, true)
		assert.Equal(t, expectedVal, val)
	}
	fmt.Print("Subset of table list case completed!\n")
}

func TestPostgresGetNonPKTables(t *testing.T) {
	testPostgresSource.TestContainer.ExecuteSqls(
		`CREATE SCHEMA test_schema;`,
		`CREATE TABLE test_schema.table1 (
		id SERIAL PRIMARY KEY,
		name VARCHAR(100)
	);`,
		`CREATE TABLE test_schema.table2 (
		id SERIAL PRIMARY KEY,
		email VARCHAR(100)
	);`,
		`CREATE TABLE test_schema.non_pk1(
		id INT,
		name VARCHAR(255)
	);`,
		`CREATE TABLE test_schema.non_pk2(
		id INT,
		name VARCHAR(255)
	);`)
	defer testPostgresSource.TestContainer.ExecuteSqls(`DROP SCHEMA test_schema CASCADE;`)
	testPostgresSource.Schemas = []sqlname.Identifier{sqlname.NewIdentifier("postgresql", "test_schema")}

	// Test GetNonPKTables
	_ = testPostgresSource.DB().Connect()
	actualTables, err := testPostgresSource.DB().GetNonPKTables()
	assert.NilError(t, err, "Expected nil but non nil error: %v", err)

	expectedTables := []string{`"test_schema"."non_pk2"`, `"test_schema"."non_pk1"`} // func returns table.Qualified.Quoted
	testutils.AssertEqualStringSlices(t, expectedTables, actualTables)
}

func TestPostgresGetPrimaryKeyColumns(t *testing.T) {
	testPostgresSource.TestContainer.ExecuteSqls(
		`CREATE SCHEMA test_schema;`,
		`CREATE SCHEMA "TestSchemaCase";`,

		// Single-column PK.
		`CREATE TABLE test_schema.simple_pk (
			id SERIAL PRIMARY KEY,
			name VARCHAR(100)
		);`,

		// Composite PK declared as (region, id) so the result must preserve
		// that exact order; (region, id) and (id, region) are different keys
		// and the live-migration guardrail compares the slices for equality.
		`CREATE TABLE "TestSchemaCase".composite_pk (
			region TEXT NOT NULL,
			id INT NOT NULL,
			payload TEXT,
			PRIMARY KEY (region, id)
		);`,

		// Table with no PK -- must be absent from the resulting map (not an error).
		`CREATE TABLE test_schema.no_pk (
			id INT,
			data TEXT
		);`,

		// Case-sensitive (quoted) schema and table to exercise identifier matching.
		`CREATE TABLE "TestSchemaCase"."Orders" (
			order_id INT PRIMARY KEY,
			note TEXT
		);`,
	)
	defer testPostgresSource.TestContainer.ExecuteSqls(
		`DROP SCHEMA test_schema CASCADE;`,
		`DROP SCHEMA "TestSchemaCase" CASCADE;`,
	)
	testPostgresSource.Schemas = []sqlname.Identifier{
		sqlname.NewIdentifier("postgresql", "test_schema"),
		sqlname.NewIdentifier("postgresql", "TestSchemaCase"),
	}

	inputTables := []sqlname.NameTuple{
		testutils.CreateNameTupleWithSourceName("test_schema.simple_pk", "test_schema", "postgresql"),
		testutils.CreateNameTupleWithSourceName("\"TestSchemaCase\".composite_pk", "TestSchemaCase", "postgresql"),
		testutils.CreateNameTupleWithSourceName("test_schema.no_pk", "test_schema", "postgresql"),
		testutils.CreateNameTupleWithSourceName(`"TestSchemaCase"."Orders"`, "TestSchemaCase", "postgresql"),
	}

	_ = testPostgresSource.DB().Connect()
	actualPKColumns, err := testPostgresSource.DB().GetPrimaryKeyColumns(inputTables)
	assert.NilError(t, err, "Expected nil but non nil error: %v", err)

	expectedPKColumns := utils.NewStructMap[sqlname.NameTuple, []string]()
	expectedPKColumns.Put(testutils.CreateNameTupleWithSourceName("test_schema.simple_pk", "test_schema", "postgresql"), []string{"id"})
	expectedPKColumns.Put(testutils.CreateNameTupleWithSourceName("\"TestSchemaCase\".composite_pk", "TestSchemaCase", "postgresql"), []string{"region", "id"})
	expectedPKColumns.Put(testutils.CreateNameTupleWithSourceName(`"TestSchemaCase"."Orders"`, "TestSchemaCase", "postgresql"), []string{"order_id"})

	expectedPKColumns.IterKV(func(table sqlname.NameTuple, expectedColumns []string) (bool, error) {
		actualColumns, exists := actualPKColumns.Get(table)
		if !exists {
			t.Errorf("Expected table %s not found in actual PK columns map", table.ForOutput())
			return true, nil
		}
		// Order matters for PKs -- compare positionally instead of as sets.
		if !slices.Equal(expectedColumns, actualColumns) {
			t.Errorf("PK columns mismatch for %s. Expected: %v, Actual: %v",
				table.ForOutput(), expectedColumns, actualColumns)
		}
		return true, nil
	})

	// no_pk has no primary key, so it must be absent from the result map.
	noPKTable := testutils.CreateNameTupleWithSourceName("test_schema.no_pk", "test_schema", "postgresql")
	if cols, exists := actualPKColumns.Get(noPKTable); exists {
		t.Errorf("Table %s has no PK and should be absent from result map; got %v",
			noPKTable.ForOutput(), cols)
	}
}

func TestGetGeneratedStoredColumns(t *testing.T) {
	testPostgresSource.TestContainer.ExecuteSqls(
		`CREATE SCHEMA test_generated_stored;`,
		`CREATE TABLE test_generated_stored.probe (
			id INT,
			val INT GENERATED ALWAYS AS (id + 1) STORED
		);`,
		`CREATE TABLE test_generated_stored.plain (id INT, data TEXT);`,
		`CREATE TABLE test_generated_stored.identity_only (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, data TEXT);`,
		`CREATE TABLE test_generated_stored.with_generated (id INT, qty INT, price NUMERIC, amount NUMERIC GENERATED ALWAYS AS (qty * price) STORED);`,
		`CREATE TABLE test_generated_stored."MixedCase" (id INT, "Length" INT, "Width" INT, "Area" INT GENERATED ALWAYS AS ("Length" * "Width") STORED);`,
		`CREATE TABLE test_generated_stored.two_generated (id INT, a INT, b INT, sum_ab INT GENERATED ALWAYS AS (a + b) STORED, prod_ab INT GENERATED ALWAYS AS (a * b) STORED);`,
		`CREATE TABLE test_generated_stored.uk_on_generated (id INT, amount INT GENERATED ALWAYS AS (id + 1) STORED, UNIQUE (amount));`,
		`CREATE TABLE test_generated_stored.uk_index_on_generated (id INT, amount INT GENERATED ALWAYS AS (id + 1) STORED);`,
		`CREATE UNIQUE INDEX idx_uk_index_on_generated ON test_generated_stored.uk_index_on_generated (amount);`,
		`CREATE TABLE test_generated_stored.partitioned (
			id INT,
			data TEXT,
			qty INT,
			amount INT GENERATED ALWAYS AS (qty + 1) STORED
		) PARTITION BY LIST (data);`,
		`CREATE TABLE test_generated_stored.partitioned_l PARTITION OF test_generated_stored.partitioned FOR VALUES IN ('London');`,
		`CREATE TABLE test_generated_stored.partitioned_s PARTITION OF test_generated_stored.partitioned FOR VALUES IN ('Sydney');`,
	)
	defer testPostgresSource.TestContainer.ExecuteSqls(`DROP SCHEMA test_generated_stored CASCADE;`)

	testPostgresSource.Schemas = []sqlname.Identifier{sqlname.NewIdentifier("postgresql", "test_generated_stored")}
	_ = testPostgresSource.DB().Connect()

	newTuple := func(name string) sqlname.NameTuple {
		return testutils.CreateNameTupleWithSourceName(name, "test_generated_stored", "postgresql")
	}
	plain := newTuple("test_generated_stored.plain")
	identityOnly := newTuple("test_generated_stored.identity_only")
	withGenerated := newTuple("test_generated_stored.with_generated")
	mixedCase := newTuple(`test_generated_stored."MixedCase"`)
	twoGenerated := newTuple("test_generated_stored.two_generated")
	probe := newTuple("test_generated_stored.probe")
	ukOnGenerated := newTuple("test_generated_stored.uk_on_generated")
	ukIndexOnGenerated := newTuple("test_generated_stored.uk_index_on_generated")
	partitioned := newTuple("test_generated_stored.partitioned")

	tableList := []sqlname.NameTuple{
		plain, identityOnly, withGenerated, mixedCase, twoGenerated,
		probe, ukOnGenerated, ukIndexOnGenerated, partitioned,
	}

	empty, err := testPostgresSource.DB().GetGeneratedStoredColumns(nil)
	require.NoError(t, err)
	require.Empty(t, empty.Keys())

	got, err := testPostgresSource.DB().GetGeneratedStoredColumns(tableList)
	require.NoError(t, err)

	_, ok := got.Get(plain)
	require.False(t, ok, "plain table should not appear")
	_, ok = got.Get(identityOnly)
	require.False(t, ok, "identity-only table should not appear (IDENTITY is not a STORED generated column)")

	// The source-side API returns only the STORED generated column names per table. Whether a
	// column is part of a unique index is resolved later in the cmd layer against the target,
	// so it is not asserted here (uk_* tables just confirm generated columns are still detected).
	assertGeneratedStoredColumns(t, got, probe, []string{"val"})
	assertGeneratedStoredColumns(t, got, withGenerated, []string{"amount"})
	assertGeneratedStoredColumns(t, got, mixedCase, []string{"Area"})
	assertGeneratedStoredColumns(t, got, twoGenerated, []string{"sum_ab", "prod_ab"})
	assertGeneratedStoredColumns(t, got, ukOnGenerated, []string{"amount"})
	assertGeneratedStoredColumns(t, got, ukIndexOnGenerated, []string{"amount"})
	assertGeneratedStoredColumns(t, got, partitioned, []string{"amount"})
}

func assertGeneratedStoredColumns(t *testing.T, got *utils.StructMap[sqlname.NameTuple, []string], table sqlname.NameTuple, expected []string) {
	t.Helper()
	cols, ok := got.Get(table)
	require.True(t, ok, "expected generated columns for %s", table.ForOutput())
	require.ElementsMatch(t, expected, cols)
}
