drop table if exists large_col_table;

CREATE TABLE large_col_table (
    id SERIAL PRIMARY KEY, 
    text_col_1 TEXT, 
    text_col_2 TEXT, 
    text_col_3 TEXT, 
    text_col_4 TEXT, 
    text_col_5 TEXT, 
    text_col_6 TEXT, 
    text_col_7 TEXT, 
    text_col_8 TEXT, 
    text_col_9 TEXT, 
    text_col_10 TEXT, 
    text_col_11 TEXT, 
    text_col_12 TEXT, 
    text_col_13 TEXT, 
    text_col_14 TEXT, 
    text_col_15 TEXT, 
    text_col_16 TEXT, 
    text_col_17 TEXT, 
    json_col_1 JSON, 
    json_col_2 JSON, 
    json_col_3 JSON, 
    json_col_4 JSON, 
    jsonb_col_1 JSONB, 
    jsonb_col_2 JSONB, 
    jsonb_col_3 JSONB, 
    jsonb_col_4 JSONB, 
    int_arr_col_1 INTEGER[], 
    int_arr_col_2 INTEGER[], 
    int_arr_col_3 INTEGER[], 
    int_arr_col_4 INTEGER[], 
    int_arr_col_5 INTEGER[], 
    char_arr_col_1 VARCHAR[], 
    char_arr_col_2 VARCHAR[], 
    char_arr_col_3 VARCHAR[], 
    char_arr_col_4 VARCHAR[], 
    char_arr_col_5 VARCHAR[], 
    smallint_col SMALLINT, 
    bigint_col BIGINT, 
    boolean_col BOOLEAN, 
    date_col DATE, 
    time_col TIME, 
    ts_col TIMESTAMP, 
    int_col INTEGER, 
    double_col DOUBLE PRECISION, 
    numeric_col NUMERIC(10,2), 
    uuid_col UUID
);

-- Set the temp file limit to 5GB to avoid the error "ERROR: temp file limit exceeded" while row_hash_validations in tests
ALTER DATABASE test_db SET temp_file_limit = 5242880; -- 5GB
ALTER DATABASE ff_db SET temp_file_limit = 5242880; -- 5GB
