#!/usr/bin/env bash

set -e
set -x

export TEST_NAME="import-file"

export REPO_ROOT="${PWD}"
export SCRIPTS="${REPO_ROOT}/migtests/scripts"
export TESTS_DIR="${REPO_ROOT}/migtests/tests"
export TEST_DIR="${TESTS_DIR}/${TEST_NAME}"
export EXPORT_DIR=${EXPORT_DIR:-"${TEST_DIR}/export-dir"}

export PYTHONPATH="${REPO_ROOT}/migtests/lib"

source ${SCRIPTS}/yugabytedb/env.sh
source ${SCRIPTS}/functions.sh

export TARGET_DB_NAME="testdb"

main() {
	rm -rf ${EXPORT_DIR}
	mkdir -p ${EXPORT_DIR}

	pushd ${TEST_DIR}

	step "Create target database."
	run_ysql yugabyte "DROP DATABASE IF EXISTS ${TARGET_DB_NAME};"
	run_ysql yugabyte "CREATE DATABASE ${TARGET_DB_NAME}"

	step "Unzip the data file."
	[ -f OneMRows.text ] || gunzip -c OneMRows.text.gz > OneMRows.text

	step "Create target table."
	ysql_import_file ${TARGET_DB_NAME} schema.sql

	step "Import data file: OneMRows.text -> one_m_rows"
	import_data_file --data-dir ${TEST_DIR} --format text --delimiter '|' \
		--file-table-map "OneMRows.text:one_m_rows"

	step "Import data file: FY2021_Survey.csv -> survey"
	import_data_file --data-dir ${TEST_DIR} --format csv --delimiter ',' \
		--file-table-map "FY2021_Survey.csv:survey" --has-header

	step "Import data file: SMSA.txt -> smsa"
	import_data_file --data-dir ${TEST_DIR} --format text --delimiter '\t' \
			--file-table-map "SMSA.txt:smsa"

	# Test for multiple table files import
	step "Import data file: FY2021_Survey.csv -> survey2 and FY2021_Survey.csv -> survey3"
	import_data_file --data-dir ${TEST_DIR} --format csv --delimiter ',' \
		--file-table-map "FY2021_Survey.csv:survey2,FY2021_Survey.csv:survey3" \
		--has-header --batch-size 1000

	# Test for fileOpts Flags having quote_char as single quote
	step "Import data file: t1_quote_char.csv -> t1_quote_char"
	import_data_file --data-dir ${TEST_DIR} --format csv --delimiter '|' \
			--file-table-map "t1_quote_char.csv:t1_quote_char" --file-opts "quote_char='"

	# Test for fileOpts Flags having quote_char as single quote and escape_char as single quote
	step "Import data file: t1_quote_escape_char1.csv -> t1_quote_escape_char1"
	import_data_file --data-dir ${TEST_DIR} --format csv --delimiter '|' \
			--file-table-map "t1_quote_escape_char1.csv:t1_quote_escape_char1" --file-opts "quote_char=',escape_char='"

	# Test for fileOpts Flags having quote_char as single quote and escape_char as backslash
	step "Import data file: t1_quote_escape_char2.csv -> t1_quote_escape_char2"
	import_data_file --data-dir ${TEST_DIR} --format csv --delimiter '|' \
			--file-table-map "t1_quote_escape_char2.csv:t1_quote_escape_char2" --file-opts "quote_char=',escape_char=\\"
	

	step "Run validations."
	 "${TEST_DIR}/validate"
}

main
