#!/usr/bin/env bash

set -e
set -x

export TEST_NAME="import-file"

export REPO_ROOT="${PWD}"
export SCRIPTS="${REPO_ROOT}/migtests/scripts"
export TESTS_DIR="${REPO_ROOT}/migtests/tests"
export TEST_DIR="${TESTS_DIR}/${TEST_NAME}"
export EXPORT_DIR=${EXPORT_DIR:-"${TEST_DIR}/export-dir"}

export PYTHONPATH="${REPO_ROOT}/migtests/lib"

source ${SCRIPTS}/yugabytedb/env.sh
source ${SCRIPTS}/functions.sh

export TARGET_DB_NAME="testdb"

main() {
	rm -rf ${EXPORT_DIR}
	mkdir -p ${EXPORT_DIR}

	pushd ${TEST_DIR}

	step "Create target database."
	run_ysql yugabyte "DROP DATABASE IF EXISTS ${TARGET_DB_NAME};"
	run_ysql yugabyte "CREATE DATABASE ${TARGET_DB_NAME}"

	step "Unzip the data file."
	[ -f OneMRows.text ] || gunzip -c OneMRows.text.gz > OneMRows.text

	step "Create target table."
	ysql_import_file ${TARGET_DB_NAME} schema.sql

	step "Import data file: OneMRows.text -> one_m_rows"
	import_data_file --data-dir ${TEST_DIR} --format text --delimiter '|' \
		--file-table-map "OneMRows.text:one_m_rows"

	step "Import data file: FY2021_Survey.csv -> survey"
	import_data_file --data-dir ${TEST_DIR} --format csv --delimiter ',' \
		--file-table-map "FY2021_Survey.csv:survey" --has-header

	step "Import data file: SMSA.txt -> smsa"
	import_data_file --data-dir ${TEST_DIR} --format text --delimiter '\t' \
			--file-table-map "SMSA.txt:smsa"

	step "Run validations."
	 "${TEST_DIR}/validate"
}

main
