#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)
	yb.run_checks(YB_specific_checks)

#=============================================================================

EXPECTED_ROW_COUNT = {
	'single_index_test': 4,
	'mult_index_test': 1000,
	'outunique_index_test': 4,
	'desc_index_test': 3,
	'partial_index_test': 13,
	'exp_index_test': 13,
	'hash_index_test': 4,
	'covering_index_test': 1000,
	'gin_index_test': 1000
}

EXPECTED_INDEX_COUNT = {
	'single_index_test': 2,
	'mult_index_test': 1,
	'outunique_index_test': 2,
	'desc_index_test': 2,
	'partial_index_test': 2,
	'exp_index_test': 2,
	'hash_index_test': 2,
	'covering_index_test': 1,
	'gin_index_test': 1,
}

def YB_specific_checks(tgt):
	yb.verify_colocation(tgt, "postgresql")

def migration_completed_checks(tgt):
	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]



if __name__ == "__main__":
	main()