#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)
	yb.run_checks(YB_specific_checks)

#=============================================================================

EXPECTED_ROW_COUNT = {
	'public': {
		'OrderItemTable':34,
	},
	'CaseSensitiveSchema': {
		'OrderTable':15,
		'AuditLogTable':14,
		'CustomerTable':10,
	}
}

def YB_specific_checks(tgt):
	yb.verify_colocation(tgt, "postgresql")

def migration_completed_checks(tgt):
	table_list = tgt.get_table_names("public")
	print("table_list:", table_list)
	assert len(table_list) == 1

	table_list = tgt.get_table_names("\"CaseSensitiveSchema\"")
	print("table_list:", table_list)
	assert len(table_list) == 3


	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT['public'].items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

	got_row_count = tgt.row_count_of_all_tables("CaseSensitiveSchema")
	for table_name, row_count in EXPECTED_ROW_COUNT['CaseSensitiveSchema'].items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]

if __name__ == "__main__":
	main()