#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)

EXPECTED_ROW_COUNT = {
	'trunc_test': 1,
 	'test_timezone': 1,
}

def migration_completed_checks(tgt):
	# Validation to check for matching row counts
	got_row_count = tgt.row_count_of_all_tables("public")
	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		print(f"table_name: {table_name}, row_count: {got_row_count[table_name]}")
		assert row_count == got_row_count[table_name]
	
	function_count = tgt.get_functions_count("public")
	assert function_count == 2
	assert set(tgt.fetch_all_function_names("public")) == set(["trunc_date", "trunc_time_stamp"])

if __name__ == "__main__":
	main()
