--Multi-column, Unique & Function Index Schema
-- DROP TABLE members;
CREATE TABLE members(
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

-- DROP INDEX members_name_i;
-- DROP INDEX members_email_i;
-- DROP INDEX members_last_name_fi;
CREATE INDEX members_name_i ON members(last_name,first_name);
CREATE UNIQUE INDEX members_email_i ON members(email);
CREATE INDEX members_last_name_fi ON members(UPPER(last_name));

COMMIT;
