#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Delete all tables and schema objects"
run_sqlplus ${SOURCE_DB_NAME} oracle-tests/schema_deletion

echo "Initialising source database"
run_sqlplus ${SOURCE_DB_NAME} index.sql

echo "Populating data in source database"
run_sqlplus ${SOURCE_DB_NAME} index_data.sql
