#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)

EXPECTED_M_VIEW = ["employee_mv_immediate"]

EXPECTED_ROW_COUNT = {
	'view_table1': 10,
	'view_table2': 9,
	'v1': 6,
	'v2': 9,
	'v3': 9,
	'whitespace view':10
}

#=============================================================================

def migration_completed_checks(tgt):
	table_list = tgt.get_objects_of_type("MVIEW")
	assert len(table_list) == len(EXPECTED_M_VIEW)
	assert set(table_list) == set(EXPECTED_M_VIEW)

	# REFRESH MATERIALIZED VIEW employee_mv_immediate;
	REFRESH_M_VIEW_QUERY = "REFRESH MATERIALIZED VIEW public.employee_mv_immediate;"
	tgt.run_query_and_chk_error(REFRESH_M_VIEW_QUERY, None)
	mv_row_count = tgt.get_row_count("employee_mv_immediate")
	print("MVIEW row count: {}".format(mv_row_count))
	assert mv_row_count == 12

	view_list = tgt.get_objects_of_type("VIEW", "public")
	print("view_list:", view_list)
	assert len(view_list) == 5

	for table_name, row_count in EXPECTED_ROW_COUNT.items():
		count = tgt.get_row_count(table_name, "public")
		print(f"table_name: {table_name}, row_count: {count}")
		assert row_count == count
	
if __name__ == "__main__":
	main()