export SOURCE_DB_TYPE="oracle"
export SOURCE_DB_SCHEMA=${SOURCE_DB_SCHEMA:-"TEST_SCHEMA"}
export TARGET_DB_NAME=${TARGET_DB_NAME:-"oracle_sequences_test"}
export RUN_SNAPSHOT_VALIDATIONS=${RUN_SNAPSHOT_VALIDATIONS:-"false"}
