drop table identity_demo_generated_always;

CREATE TABLE identity_demo_generated_always (
    id NUMBER GENERATED ALWAYS AS IDENTITY,
    description VARCHAR2(100) NOT NULL
);

INSERT INTO identity_demo_generated_always(description)
VALUES('Random description for the test');

INSERT INTO identity_demo_generated_always(description)
VALUES('Random description for the test');

select * from identity_demo_generated_always;


drop table identity_demo_generated_by_def;

CREATE  TABLE identity_demo_generated_by_def  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR2(100) not null
  );

INSERT INTO identity_demo_generated_by_def(description)
VALUES('Random description for the test');

INSERT INTO identity_demo_generated_by_def(id,description)
VALUES(2, 'Random description for the test');

INSERT INTO identity_demo_generated_by_def(id,description)
VALUES(5, 'Random description for the test');

select * from identity_demo_generated_by_def;

DROP TABLE identity_demo_with_null;

CREATE  TABLE identity_demo_with_null  (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    description VARCHAR2(100) not null
  );

INSERT INTO identity_demo_with_null(description)
VALUES('Oracle identity column demo with null');

INSERT INTO identity_demo_with_null
VALUES(null,'Oracle identity column demo with null');

select * from identity_demo_with_null;

drop table identity_demo_generated_always_start_with;

CREATE TABLE identity_demo_generated_always_start_with (
    id NUMBER GENERATED ALWAYS AS IDENTITY start with 101,
    description VARCHAR2(100) NOT NULL
);

INSERT INTO identity_demo_generated_always_start_with(description)
VALUES('Random description for the test');

select * from identity_demo_generated_always_start_with;

drop table identity_demo_generated_by_def_start_with;

CREATE  TABLE identity_demo_generated_by_def_start_with  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY start with 101,
    description VARCHAR2(100) not null
  );

INSERT INTO identity_demo_generated_by_def_start_with(description)
VALUES('Random description for the test');

INSERT INTO identity_demo_generated_by_def_start_with(id,description)
VALUES(2, 'Random description for the test');

INSERT INTO identity_demo_generated_by_def_start_with(description)
VALUES('Random description for the test');

select * from identity_demo_generated_by_def_start_with;

drop table identity_demo_generated_by_def_inc_by;

CREATE  TABLE identity_demo_generated_by_def_inc_by  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY increment by 101,
    description VARCHAR2(100) not null
  );

INSERT INTO identity_demo_generated_by_def_inc_by(description)
VALUES('Random description for the test');

INSERT INTO identity_demo_generated_by_def_inc_by(id,description)
VALUES(2, 'Random description for the test');

INSERT INTO identity_demo_generated_by_def_inc_by(description)
VALUES('Random description for the test');

select * from identity_demo_generated_by_def_inc_by;

drop table identity_demo_generated_by_def_st_with_inc_by;

CREATE  TABLE identity_demo_generated_by_def_st_with_inc_by  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY start with 5 increment by 101,
    description VARCHAR2(100) not null
  );

INSERT INTO identity_demo_generated_by_def_st_with_inc_by(description)
VALUES('Random description for the test');

INSERT INTO identity_demo_generated_by_def_st_with_inc_by(id,description)
VALUES(4, 'Random description for the test');

INSERT INTO identity_demo_generated_by_def_st_with_inc_by(description)
VALUES('Random description for the test');

select * from identity_demo_generated_by_def_st_with_inc_by;

commit;