drop table identity_demo_generated_always;

CREATE TABLE identity_demo_generated_always (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL
);

drop table identity_demo_generated_by_def;

CREATE  TABLE identity_demo_generated_by_def  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) not null
  );

DROP TABLE identity_demo_with_null;

CREATE  TABLE identity_demo_with_null  (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) not null
  );

drop table identity_demo_generated_always_start_with;

CREATE TABLE identity_demo_generated_always_start_with (
    id NUMBER GENERATED ALWAYS AS IDENTITY start with 101 PRIMARY KEY,
    description VARCHAR2(100) NOT NULL
);

drop table identity_demo_generated_by_def_start_with;

CREATE  TABLE identity_demo_generated_by_def_start_with  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY start with 101 PRIMARY KEY,
    description VARCHAR2(100) not null
  );

drop table identity_demo_generated_by_def_inc_by;

CREATE  TABLE identity_demo_generated_by_def_inc_by  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY increment by 101 PRIMARY KEY,
    description VARCHAR2(100) not null
  );

drop table identity_demo_generated_by_def_st_with_inc_by;

CREATE  TABLE identity_demo_generated_by_def_st_with_inc_by  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY start with 5 increment by 101 PRIMARY KEY,
    description VARCHAR2(100) not null
  );

drop table empty_identity_demo_generated_always;

CREATE TABLE empty_identity_demo_generated_always (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) NOT NULL
);

drop table empty_identity_demo_generated_by_def;

CREATE  TABLE empty_identity_demo_generated_by_def  (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(100) not null
  );

commit;