#!/usr/bin/env python3

import yb

def main():
	yb.run_checks(migration_completed_checks)


#=============================================================================

EXPECTED_EXTENSION_SET = set([("btree_gist",), ("pg_stat_statements",), ("plpgsql",), ("dblink",), ("hstore",), ("uuid-ossp",)])

EXPECTED_TRIGGER_LIST = [
		"report_tsv_update","trg_check_exclusion_constraints","report_tsv_update","trg_check_exclusion_constraints"
		]

EXPECTED_INDEX_COUNT = {
	'agents': 1,
	'countries': 1,
	'reports': 2,
	'secret_missions': 1
}


def migration_completed_checks(tgt):

	extension_list = tgt.fetch_all_pg_extension("public")
	print(f"extension_list: {extension_list}\n EXPECTED_EXTENSION_SET: {EXPECTED_EXTENSION_SET}")
	assert extension_list == EXPECTED_EXTENSION_SET

	table_list = tgt.get_table_names("public")
	print("table_list:", table_list)
	assert len(table_list) == 9

	fetched_triggers = tgt.fetch_all_triggers("public")
	print(f"fetched triggers list: {fetched_triggers}\n Expected triggers: {EXPECTED_TRIGGER_LIST}")
	assert sorted(fetched_triggers) == sorted(EXPECTED_TRIGGER_LIST), "Fetched triggers do not match expected triggers"

	QUERY_CHK_TYPES_DOMAINS = "select count(typname) from pg_type where typname in ('currency');"
	cnt_type_domain = tgt.execute_query(QUERY_CHK_TYPES_DOMAINS)
	print(f"count returned - {cnt_type_domain}")
	assert cnt_type_domain == 1

	fetched_procedures_functions = tgt.fetch_all_procedures("public")
	print(f"count of fecthed procedures/functions - {len(fetched_procedures_functions)}")
	tgtVersion = tgt.get_target_version()
	print(f"target version: {tgtVersion}")
	
	# for PG15 merged versions like 2.25, some extensions create more functions/procedures than in earlier versions.
	# Example hstore
	# 2024.2: 57 functions / procedures
	# 2.25: 60 functions / procedures
	# Thus the change in count.

	if "2.25" in tgtVersion:
		assert len(fetched_procedures_functions) == 300
	else:
		assert len(fetched_procedures_functions) == 288

	get_index_cnt = tgt.get_count_index_on_table("public")
	for table_name, index_count in EXPECTED_INDEX_COUNT.items():
		print(f"table_name: {table_name}, index_count: {get_index_cnt[table_name]}")
		assert index_count == get_index_cnt[table_name]

if __name__ == "__main__":
	main()
