name: "PG 17: Migration Tests (Config File Workflow)"

on:
  push:
    branches: ['main', '*.*-dev', '*.*.*-dev']
  pull_request:
    branches: [main]

jobs:
  run-pg-17-migration-tests:
    strategy:
      matrix:
        version: [2024.2.4.0-b89, 2.20.10.0-b29, 2.25.2.0-b359, 2025.1.0.0-b168, 2024.1.6.1-b2]
        BETA_FAST_DATA_EXPORT: [0, 1]
        test_group:
          - offline
          - live-migration
        exclude:
          # Exclude BETA_FAST_DATA_EXPORT=1 for live migration tests (redundant/not-required)
          - BETA_FAST_DATA_EXPORT: 1
            test_group: live-migration

    env:
      BETA_FAST_DATA_EXPORT: ${{ matrix.BETA_FAST_DATA_EXPORT }}
      YB_VOYAGER_SEND_DIAGNOSTICS: 0
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        # https://github.com/actions/setup-java
        with:
          distribution: "temurin"
          java-version: "17"
          check-latest: true

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: "Enable postgres with wal_level as logical and install postgis"
        run: |
          docker exec ${{ job.services.postgres.id }} sh -c "echo 'wal_level=logical' >> /var/lib/postgresql/data/postgresql.conf"
          docker exec ${{ job.services.postgres.id }} sh -c "apt-get update && apt-get install -y postgresql-17-postgis-3"
          docker restart ${{ job.services.postgres.id }}
          
          # Wait for PostgreSQL to be ready with health check instead of fixed sleep
          echo "Waiting for PostgreSQL to be ready after restart..."
          timeout 30s bash -c 'until docker exec ${{ job.services.postgres.id }} pg_isready > /dev/null 2>&1; do 
            echo "PostgreSQL not ready yet, waiting 1 second..."
            sleep 1
          done'
          echo "PostgreSQL is ready!"

      - name: Install python3 and psycopg2
        run: |
          sudo apt install -y python3
          sudo apt install -y libpq-dev
          sudo apt install python3-psycopg2

      - name: Run installer script to setup voyager
        run: |
          cd installer_scripts
          yes | ./install-yb-voyager --install-from-local-source --only-pg-support
          sudo rm /usr/bin/pg_dump
          sudo ln -s /usr/lib/postgresql/17/bin/pg_dump /usr/bin/pg_dump
          sudo rm /usr/bin/pg_restore
          sudo ln -s /usr/lib/postgresql/17/bin/pg_restore /usr/bin/pg_restore
          pg_dump --version
          pg_restore --version
          psql --version
        env:
          ON_INSTALLER_ERROR_OUTPUT_LOG: Y

      - name: Test PostgreSQL Connection
        run: |
          psql "postgresql://postgres:postgres@127.0.0.1:5432/postgres" -c "SELECT version();"

      - name: Create PostgreSQL user
        run: |
          ./migtests/scripts/postgresql/create_pg_user

      - name: Start YugabyteDB cluster
        run: |
          docker run -d --name yugabytedb --hostname yb-cluster-test\
            -p7000:7000 -p9000:9000 -p15433:15433 -p5433:5433 -p9042:9042 \
            yugabytedb/yugabyte:${{ matrix.version }} \
            bin/yugabyted start --tserver_flags="ysql_hba_conf_csv={host all yugabyte all trust,host all all all md5}" --background=false --ui=false --callhome=false 
          
          # Wait for YugabyteDB to be ready with health check
          echo "Waiting for YugabyteDB to be ready..."
          timeout 60s bash -c 'until psql "postgresql://yugabyte:@127.0.0.1:5433/yugabyte" -c "SELECT 1" > /dev/null 2>&1; do 
            echo "YugabyteDB not ready yet, waiting 2 seconds..."
            sleep 2
          done'
          echo "YugabyteDB is ready!"

      - name: Test YugabyteDB connection
        run: |
          psql "postgresql://yugabyte:@127.0.0.1:5433/yugabyte" -c "SELECT version();"

      - name: Create YugabyteDB user
        run: |
          ./migtests/scripts/yugabytedb/create_yb_user

      - name: Enable yb-cluster-test name resolution
        run: |
          docker_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' yugabytedb)
          echo "$docker_ip	yb-cluster-test" | sudo tee -a /etc/hosts
          psql "postgresql://yugabyte@yb-cluster-test:5433/yugabyte" -c "SELECT version();"

      - name: "TEST: PG sample schemas (sakila)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/sakila

      - name: "TEST: PG sample schemas (osm)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/osm

      - name: "TEST: PG sample schemas (omnibus)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/omnibus

      - name: "TEST: PG sample schemas (adventureworks)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/adventureworks

      - name: "TEST: PG sample schemas (sample-is)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/sample-is

      - name: "TEST: PG sample schemas (pgtbrus)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/pgtbrus

      - name: "TEST: PG sample schemas (stackexchange)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-schema-migration.sh pg/stackexchange

      - name: "TEST: pg-table-list-flags-test (table-list and exclude-table-list)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/table-list-flags-tests --run-via-config-file

      - name: "TEST: pg-table-list-file-path-test (table-list-file-path and exclude-table-list-file-path)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/table-list-flags-tests env-file-path-flags.sh --run-via-config-file

      - name: "TEST: pg-case-sensitivity-single-table"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test-export-data.sh pg/case-sensitivity-single-table

      - name: "TEST: pg-dvdrental"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/dvdrental --run-via-config-file

      - name: "TEST: pg-datatypes"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/datatypes --run-via-config-file

      - name: "TEST: pg-constraints"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/constraints --run-via-config-file

      - name: "TEST: pg-sequences"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/sequences --run-via-config-file

      - name: "TEST: pg-sequences with table list"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/sequences env-with-table-list.sh --run-via-config-file

      - name: "TEST: pg-indexes"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/indexes --run-via-config-file

      - name: "TEST: pg-partitions"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/partitions --run-via-config-file

      - name: "TEST: pg-partitions with (table-list)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: EXPORT_TABLE_LIST='customers,sales,emp,p2.boston,p2.london,p2.sydney,range_columns_partition_test,sales_region,test_partitions_sequences' migtests/scripts/run-test.sh pg/partitions --run-via-config-file

      # Broken for v2.15 and v2.16: https://github.com/yugabyte/yugabyte-db/issues/14529
      # Fixed in 2.17.1.0-b368
      - name: "TEST: pg-partitions-with-indexes"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/partitions-with-indexes --run-via-config-file

      - name: "TEST: pg-views-and-rules"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/views-and-rules --run-via-config-file

      - name: "TEST: pg-misc-objects-1 (Types, case-sensitive-table-name, Domain)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/misc-objects-1 --run-via-config-file

      - name: "TEST: pg-misc-objects-2 (Aggregates, Procedures, triggers, functions, extensions, inline comments)"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/misc-objects-2 --run-via-config-file

      - name: "TEST: pg-dependent-ddls"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/dependent-ddls --run-via-config-file

      - name: "TEST: pg-multiple-schemas"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/multiple-schemas --run-via-config-file

      - name: "TEST: pg-codependent-schemas"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/codependent-schemas --run-via-config-file

      - name: "TEST: pg-sample-schema-emp"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/sample-employee --run-via-config-file

      - name: "TEST: pg-hasura-ecommerce"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/hasura-ecommerce --run-via-config-file

      - name: "TEST: pg-case-sensitivity-reserved-words-offline"
        if: ${{ !cancelled() && matrix.test_group == 'offline' }}
        run: migtests/scripts/run-test.sh pg/case-sensitivity-reserved-words --run-via-config-file

      - name: "TEST: pg-basic-non-public-live-migration-test"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: migtests/scripts/live-migration-run-test.sh pg/basic-non-public-live-test --run-via-config-file

      - name: "TEST: pg-basic-public-fall-forward-test"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: migtests/scripts/live-migration-fallf-run-test.sh pg/basic-public-live-test --run-via-config-file

      - name: "TEST: pg-datatypes-fall-forward-test"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: migtests/scripts/live-migration-fallf-run-test.sh pg/datatypes --run-via-config-file

      # - name: "TEST: pg-basic-non-public-fall-back-test"
      #   run: migtests/scripts/live-migration-fallb-run-test.sh pg/basic-non-public-live-test --run-via-config-file

      - name: "TEST: pg-datatypes-fall-back-test"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: migtests/scripts/live-migration-fallb-run-test.sh pg/datatypes --run-via-config-file

      # case sensitive table names are not yet supported in live migration, to restricting test only to a few tables.
      - name: "TEST: pg-live-migration-multiple-schemas"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: EXPORT_TABLE_LIST="ext_test,tt,audit,recipients,session_log,schema2.ext_test,schema2.tt,schema2.audit,schema2.recipients,schema2.session_log" migtests/scripts/live-migration-run-test.sh  pg/multiple-schemas --run-via-config-file

      - name: "TEST: pg-unique-key-conflicts-test"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: migtests/scripts/live-migration-fallf-run-test.sh pg/unique-key-conflicts-test --run-via-config-file

      - name: "TEST: pg-live-migration-partitions-fall-forward"
        if: ${{ !cancelled() && matrix.test_group == 'live-migration' }}
        run: migtests/scripts/live-migration-fallf-run-test.sh pg/partitions --run-via-config-file