name: Test Prepare Versions

on:
  workflow_dispatch:  # Manual trigger for testing
  push:
    branches: [main]
    paths:
      - '.github/workflows/prepare-versions.yml'
      - 'yb-voyager/testdata/yb-versions.json'

jobs:
  prepare-versions:
    uses: ./.github/workflows/prepare-versions.yml

  test-matrix-generation:
    needs: [prepare-versions]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        yb_version: ${{ fromJSON(needs.prepare-versions.outputs.yb_versions) }}
        test_type: ["unit", "integration"]
    steps:
      - name: Test matrix values
        run: |
          echo "=== Matrix Test Results ==="
          echo "YB Version: ${{ matrix.yb_version }}"
          echo "Test Type: ${{ matrix.test_type }}"
          echo "Latest Stable: ${{ needs.prepare-versions.outputs.yb_latest_stable }}"
          echo "Total matrix jobs: $(echo '${{ fromJSON(needs.prepare-versions.outputs.yb_versions) }}' | jq 'length') versions × 2 test types = $(($(echo '${{ fromJSON(needs.prepare-versions.outputs.yb_versions) }}' | jq 'length') * 2)) jobs"
          
      - name: Verify YB version format
        run: |
          echo "Verifying YB version format: ${{ matrix.yb_version }}"
          if [[ "${{ matrix.yb_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+-b[0-9]+$ ]]; then
            echo "✅ YB version format is valid"
          else
            echo "❌ YB version format is invalid"
            exit 1
          fi

  test-single-version:
    needs: [prepare-versions]
    runs-on: ubuntu-22.04
    steps:
      - name: Test single version access
        run: |
          echo "=== Single Version Test ==="
          echo "All versions: ${{ needs.prepare-versions.outputs.yb_versions }}"
          echo "Latest stable: ${{ needs.prepare-versions.outputs.yb_latest_stable }}"
          
          # Test that we can parse the JSON
          versions_json='${{ needs.prepare-versions.outputs.yb_versions }}'
          echo "Parsed versions:"
          echo "$versions_json" | jq -r '.[]' | while read version; do
            echo "  - $version"
          done

  test-expected-job-count:
    needs: [prepare-versions]
    runs-on: ubuntu-22.04
    steps:
      - name: Calculate expected job counts
        run: |
          echo "=== Expected Job Counts ==="
          versions_count=$(echo '${{ needs.prepare-versions.outputs.yb_versions }}' | jq 'length')
          echo "Number of YB versions: $versions_count"
          echo ""
          echo "Expected job counts for each workflow:"
          echo "  - MySQL tests: $versions_count versions × 2 BETA_FAST_DATA_EXPORT = $((versions_count * 2)) jobs"
          echo "  - PG-17 tests: $versions_count versions × 2 BETA_FAST_DATA_EXPORT × 2 test_groups = $((versions_count * 4)) jobs (minus 5 exclusions = $((versions_count * 4 - 5)) jobs)"
          echo "  - PG-13 tests: $versions_count versions × 2 BETA_FAST_DATA_EXPORT × 2 test_groups = $((versions_count * 4)) jobs (minus 5 exclusions = $((versions_count * 4 - 5)) jobs)"
          echo "  - Issue tests: $versions_count versions = $versions_count jobs"
          echo ""
          echo "Total expected jobs: ~$((versions_count * 2 + versions_count * 4 - 5 + versions_count * 4 - 5 + versions_count)) jobs"
