#!/usr/bin/env bash

set -e
set -x

source ${SCRIPTS}/functions.sh

echo "Initialising source database."

run_psql ${SOURCE_DB_NAME} "\i ${TEST_DIR}/../misc-objects-1/schema.sql;"

echo "Check source database."
run_psql ${SOURCE_DB_NAME} "SELECT count(*) FROM orders;"
